### ISSUE TITLE
deal with images versions

### ISSUE THREAD

**Issue by devozanges** [liip/LiipImagineBundle#1002]
Is there a way for this bundle to support an image version ID. for example, I have a photo sometimes updated, but it keeps the same name on the server. I would like to be able to attach an identifier (timestamp for example) to imagine_filter so that it overwrites the old image in the cache only if it is necessary. Or if it is not possible (what I think), how to deal with this kind of case. 

Thank you

**Comment by trsteel88** [comment]
I'd suggest using a runtime config so it generates a unique path per config.

**Comment by rudak** [comment]
Ok, I am checking this idea but I dont see how to change path in the [runtime option](https://github.com/liip/LiipImagineBundle#runtime-options) part of the doc.
