### ISSUE TITLE
Feature request: cache ttl (lifetime) in cacheResolver

### ISSUE THREAD

**Issue by yamilovs** [liip/LiipImagineBundle#1003]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 1.9.1

Hello guys!
In our project we using `redis` as a part of `Cache Resolver`. It works perfectly, but we have one issue.
After a while we got "old" records. Its happens, because `Cache Resolver` only saves data by calling
```php
$this->cache->save($indexKey, $index);
```
and ignoring third argument - `$lifeTime`. Is it true? or i just misunderstood something?

If it is, i think, it must be a configurable parameter.

Thanks in advance!

**Comment by michellesanver** [comment]
@yamilovs This feature request is quite old, is it still a need from your side?

**Comment by yamilovs** [comment]
Hello @michellesanver!

Sorry for the long answer. Yep this issue is actual, but i think i can make a PR myself.

So far we clean the redis keys automatically by a crontab daemon.
