### ISSUE TITLE
Question about CacheManager::getBrowserPath()

### ISSUE THREAD

**Issue by clemdesign** [liip/LiipImagineBundle#1005]
| Q | A
| --- | ---
| Bug Report? | maybe
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9

Hi, 
I have a question related to an issue that I try to resolve but it's maybe a mis-understanding of myself. 

> My issue

When I update my avatar with form, I call in backend the `CacheManager::remove($path)` (In order to clean cache for the old avatar).
Then, I render the profile with avatar and the tag `<img src="{{ user.getAvatarPath|imagine_filter('avatar_200') }}" alt="Avatar" >`
So, I get correctly the cache avatar path but as no file is stored in cache directory, I get 404 error.

To resolve it, I run the command `php bin/console liip:imagine:cache:resolve data/avatar/0000000001.jpg --filters=avatar_200`.

Then all works.

Then, I remove manually the avatar file in cache directory.

After a refresh of page, I get 404 error again for the avatar.

> My first level analysis and the question

In `CacheManager::getBrowserPath()`, there is 

    return $this->isStored($path, $filter, $resolver) ?
        $this->resolve($path, $filter, $resolver) :
        $this->generateUrl($path, $filter, array(), $resolver)
    ;

When I run debugger, the condition is considered as false so `generateUrl` is called. But should not on call `resolve` in case of path considered not stored?

Thank you

**Comment by clemdesign** [comment]
So, I thought that `CacheManager::resolve()` was doing the same thing that `php bin/console liip:imagine:cache:resolve`, but I misunderstood.

After more investigation, to resolve my issue in backend, I shall to execute the following instruction after `CacheManager::remove($path)`:

    $this->cacheManager->store($this->filterManager->applyFilter($this->dataManager->find($filter, $path), $filter), $path, $filter);

Is there not a better way to regenerate cache media after a `remove` action?

Thank you

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
