### ISSUE TITLE
Symfony 3.3 Flex

### ISSUE THREAD

**Issue by kironet** [liip/LiipImagineBundle#1014]
| Q | A
| --- | ---
| Imagine Bundle Version | 1.9

Hey,

I've installed this bundle with flex and this is my config.

```
liip_imagine :
    # configure resolvers
    resolvers :
        # setup the default resolver
        default :
            # use the default web path
            web_path : ~

    filter_sets:
        270x270:
            quality: 90
            jpeg_quality: 90
            png_compression_level: 9
            png_compression_filter: ~
            format: jpg
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [270, 270]
                    mode: inset
                strip: ~
                interlace:
                    mode: plane
                background: { size: [270, 270], color: '#fff' }
```

twig:
`{% set path = asset('build/shared/img/apple/models/' ~ product.categories|first.image) %}`
`<img class="" src="{{ path | imagine_filter('270x270') }}" alt="{{ product.name }}" title="{{ product.name }}">`

error:

> No route found for "GET /media/cache/270x270/build/shared/img/apple/models/macbook-12.jpg"

if I try to load image without filter, everything works = path to image is ok.

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
