### ISSUE TITLE
[Symfony 4.0] ProcessBuilder is removed

### ISSUE THREAD

**Issue by fabianbloching** [liip/LiipImagineBundle#1024]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| Imagine Bundle Version | 2.x

With the symfony 4.0 release, the ProcessBuilder is removed. 

The ImagineBundle still uses the ProcessBuilder here:

- https://github.com/liip/LiipImagineBundle/blob/610d4f5af28a290848399b38de23226130a27411/Imagine/Filter/PostProcessor/MozJpegPostProcessor.php#L88

- https://github.com/liip/LiipImagineBundle/blob/610d4f5af28a290848399b38de23226130a27411/Imagine/Filter/PostProcessor/OptiPngPostProcessor.php#L96

- https://github.com/liip/LiipImagineBundle/blob/610d4f5af28a290848399b38de23226130a27411/Imagine/Filter/PostProcessor/PngquantPostProcessor.php#L86

- https://github.com/liip/LiipImagineBundle/blob/610d4f5af28a290848399b38de23226130a27411/Imagine/Filter/PostProcessor/JpegOptimPostProcessor.php#L144

I try to create a pull request for this issue.

**Comment by maximgubar** [comment]
@fabianbloching can we consider this issue as solved ?

**Comment by sebastianblum** [comment]
yes, this works since pr #1025 . you can close this issue.
