### ISSUE TITLE
Generate image filtered from controler (or service)

### ISSUE THREAD

**Issue by shakealot** [liip/LiipImagineBundle#1028]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9.1

I need to generate a thumbnail from within a service and use that thumbnail inside a PDF, so i need the binary to be generated, and to get the absolute url.
I've tried using the imagineCacheManager->getBrowserPath() function, but it seems like the file will only be generated when you go to the relative url.
I succeeded to use the thumbnail by using the command liip:imagine:cache:resolve, but the image is uploaded from a Backoffice, I cant wait the user to upload an image and then use that command

**Comment by cedricziel** [comment]
I suggest looking into the command to understand how cached images are generated - it's actually pretty easy.

**Comment by shakealot** [comment]
Thank you ! I've been able to generate the thumbnail :)

**Comment by VKarich** [comment]
Great! And where is the answer ?
