### ISSUE TITLE
2.0 release?

### ISSUE THREAD

**Issue by pamil** [liip/LiipImagineBundle#1052]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | -

Is there anything that needs to be done before tagging a 2.0 release?

**Comment by robfrawley** [comment]
See https://github.com/liip/LiipImagineBundle/milestone/6

**Comment by robfrawley** [comment]
@pamil I also meant to mention that at the moment, we are shooting for a release date of March 5th for the `2.0` release, which I believe is notated on the milestone page. Basically, whatever isn't done prior will be pushed back to `2.1`, unless one of the "blocker" PRs aren't completed, in which case the date may slip, but we're trying our best to hit that mark.

**Comment by pamil** [comment]
Thanks for information! 🎉

**Comment by secit-pl** [comment]
Any update on this?

**Comment by robfrawley** [comment]
Been working on some things all week that we would really like to get into `2.0`, and assuming progress continues as it has been, the current date on the [milestone page](https://github.com/liip/LiipImagineBundle/milestone/6) is accurate: this Friday.

**Comment by mssimi** [comment]
Hey, any news on this?

**Comment by robfrawley** [comment]
Finalizing a release as we speak.

**Comment by pamil** [comment]
Can I be of some help? I'll be testing `^2.0@dev` on Sylius soon.

**Comment by maximgubar** [comment]
@pamil, @secit-pl, @mssimi [2.0.0](https://github.com/liip/LiipImagineBundle/releases/tag/2.0.0) has been released
