### ISSUE TITLE
Support for Symfony 4

### ISSUE THREAD

**Issue by jeroendesloovere** [liip/LiipImagineBundle#1064]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | latest

Can you guys please bump the composer.json of liip/imagine-bundle, so it works with the latest symfony bundles: 
- `symfony/asset` version to support `^4.0`
- `symfony/framework-bundle` version to support `^4.0`
- `symfony/process` version to support `^4.0`
- `symfony/templating` version to support `^4.0`
- `symfony/filesystem` version to support `^4.0`
- `symfony/finder` version to support `^4.0`
- `symfony/options-resolver` version to support `^4.0`
- `symfony/translation` version to support `^4.0`

So we can use `liip/imagine-bundle` in the latest symfony version...

**Comment by cedricziel** [comment]
V2.0 is close to being released and supports symfony 4 already.

**Comment by robfrawley** [comment]
Check our [milestones page](https://github.com/liip/LiipImagineBundle/milestones) for expected release dates.

**Comment by tacman** [comment]
is there a dev branch for 2.0 we can use that works with Symfony 4?

**Comment by robfrawley** [comment]
You can simply use `~2.0@dev` in your `composer.json` file. Be careful when running `composer update` though, as some breaking changes will be pushed before the final `2.0` release next week.

**Comment by nickicool** [comment]
Then i try install:
`composer require liip/imagine-bundle 2.0`

I give error:
`Package liip/imagine-bundle at version 2.0 has a PHP requirement incompatible with your PHP version (7.1.3.0)`

I use Symfony 4.0.2, and cant use PHP < 7.1
Help pls install.

**Comment by cedricziel** [comment]
you would typically run `composer require liip/imagine-bundle:~2.0@dev`.

Are you sure that the interpreter at `which php` is 7.1?

**Comment by nickicool** [comment]
Thank you! `composer require "liip/imagine-bundle:~2.0@dev"` work!

**Comment by stephanvierkant** [comment]
Any idea when a stable release is expected?

This issue is a duplicate of #1017, isn't it?

**Comment by jeroendesloovere** [comment]
Closing this one because the solution is to temporary use `composer require "liip/imagine-bundle:~2.0@dev"`
