### ISSUE TITLE
Need help changing web default to public_html

### ISSUE THREAD

**Issue by flyboy67109** [liip/LiipImagineBundle#1068]
| Q 
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? |no
| RFC? | n/a
| Imagine Bundle Version | 2.?

I'm getting the following error when access images on a shared server:
Root image path not resolvable "/home6/lylecran/app/../web"

Because it's a shared server, my root is now public_html and not web. need help changing the config file so my images will resolve.

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
