### ISSUE TITLE
PostProcessors timeout

### ISSUE THREAD

**Issue by proArtex** [liip/LiipImagineBundle#1070]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 2.0

OptiPngPostProcessor creates and runs new Process($processArguments) in processWithConfiguration() method, but it doesn't contain 4th argument $timeout in constructor, so it becomes 60s by default. This postprocessor may take over 60s, so it would be great to have ability to configure timeout of processors in some way.

**Comment by robfrawley** [comment]
This is already in the works in #993. We'll see if we can't get it in the 2.0.0 release.
