### ISSUE TITLE
RAW Support (auto-extract JPG)

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1073]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| Imagine Bundle Version | 2.0

I have a raw file (Fuji's RAF) with an embedded jpg.  Is there a filter to automatically extracting that jpeg to the liip cache for display?  I'm hoping to simply call {{ asset('raw_file.RAF') | imagine_filter('thumbnail') }}

**Comment by robfrawley** [comment]
There is no official support for any image conversions (png to jpg, raw to jpg, or otherwise). I'd love for someone to implement conversion support, though.

**Comment by tacman** [comment]
Conversion of RAW isn't practical, but extracting the jpeg and displaying
it is doable.

**Comment by tacman** [comment]
Having a hard time attaching it here, as there's a 10MB limit.  

Try these links:

https://s3.amazonaws.com/photos.survos.com/_zacatecas/AguasCalientes1/Sat+Feb+17+11%3A06%3A18+2018.RAF

https://s3.amazonaws.com/photos.survos.com/SHP-RAW.dng

I'll post a few more in a bit, fighting with s3 permissions.

**Comment by robfrawley** [comment]
Thanks. More would be great. Try Google Drive. Otherwise, feel free to e-mail them to me at the following address (replacing `AT` with `@` and `DOT` with `.`):

```
github AT src DOT run
```

**Comment by robfrawley** [comment]
@tacman I won't have any time after this weekend to look into this, so please follow the instructions in the above comment and submit up to 10 or so Fuji RAF RAW files. Thanks.
