### ISSUE TITLE
Injecting FileSystemLocator service

### ISSUE THREAD

**Issue by silverbackdan** [liip/LiipImagineBundle#1078]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 2.0-dev

I'm creating an OS reusable bundle that uses this bundle. I'd like to use the FIleSystemLocator service in another service of mine. When injecting I get 
```
Argument 1 passed to Liip\ImagineBundle\Binary\Locator\FileSystemLocator::__construct() must be of the type array, string given ...
```

An empty string is being passed instead of the root directories array. It seems to work fine until I try to inject the service `liip_imagine.binary.locator.filesystem`

Is this an Imagine bug or Symfony do you think? SF version 4.0.6 - I have traced and see that the locator factory is setting to inject the root directories into the service, but perhaps there's something I'm missing when trying to use the service?

**Comment by cedricziel** [comment]
As far as I read it, that's precisely what is supposed to happen. The factory service will add the required arguments. (Empty argument is added here: https://github.com/liip/LiipImagineBundle/blob/8c2284483267131c1a589c7a9da6af5323a70f0a/Resources/config/imagine.xml#L266 and crunched through the compiler pass here: https://github.com/liip/LiipImagineBundle/blob/8c2284483267131c1a589c7a9da6af5323a70f0a/DependencyInjection/Factory/Loader/FileSystemLoaderFactory.php#L177).

This ensures that there's a locator that's stuffed with the correct loader. What is your use case?

**Comment by silverbackdan** [comment]
I see. I had a look and can see that too now. Thanks for the very fast response!

I am saving a file path in a database. This is an absolute path. If it is an image, and supported by Imagine resizing I want it to resize. I need to either convert the absolute filepath into one which is relative to one of the base directories that are configured in this bundle or have the ability to get the root directories that are configured in the bundle so I can detect whether the absolute filepath is within one of the configured base/root directories.

**Comment by cedricziel** [comment]
You should read the service definition in your own compiler pass. I think that's the sanest way of doing it.

**Comment by silverbackdan** [comment]
If I try to read the service definition in my compiler pass it wouldn't have the constructor params with the root paths would it? Or are you referring to the loader service `liip_imagine.binary.loader.default`?

Do you think a PR would be well received which add a function to the locator which will check if the path is absolute and then if it is within the defined root paths?

**Comment by cedricziel** [comment]
Why can't you use the chainloader instead?

**Comment by silverbackdan** [comment]
I could create my own loader and add to a chain and then adjust the config. It seems like rather a lot for something that may perhaps be a more common requirement.

It'd just be modifying this method:
```php
    /**
     * @param string $path
     *
     * @return string|null
     */
    private function locateUsingRootPathsSearch(string $path): ?string
    {
        $isAbsolutePath = 0 === mb_strpos($path, '/');
        
        foreach ($this->roots as $root) {
            if (null !== $absolute = $this->generateAbsolutePath($root, $path)) {
                return $absolute;
            } elseif ($isAbsolutePath && strpos($path, $root) === 0) {
                return $path;
            }
        }

        return null;
    }
```

But if you'd say that I should just use the chainloader I can go away and do that

**Comment by silverbackdan** [comment]
As you're being kind enough to reply so fast I just wanted to say that I'm looking at data loaders now and just making sure I can get the root directories configured in a custom loader. I wasn't sure that is possible, but I'm taking a look through the solution you've suggested now.

**Comment by silverbackdan** [comment]
You are right though in your first suggestion, just fetching the loader arguments to get the locator arguments in my own compiler pass gives me access to the root paths and I can inject those into my own bundle's services as necessary.

I'm happy to raise a PR with the above adjustments to the loader method if you think it'd be beneficial for others - for me, I'll crack on and thank you very much.

**Comment by cedricziel** [comment]
Thanks for the feedback - i think it's sane to use it in your own pass. Happy coding!
