### ISSUE TITLE
How do I know the size of a resized image?

### ISSUE THREAD

**Issue by petr-buchin** [liip/LiipImagineBundle#1080]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 2.0.0

I'm using stream loader to load image from Amazon S3 bucket, and AWS S3 cache adapter to upload resized image to another bucket.
I'm also using relative resize by width. 
How do I know dimensions of the resized image?

The possible solution is to download original image from bucket, use local loader to load image, save it's dimensions and aspect ratio, and calculate new dimensions after resize.
But I would like to get this dimensions without repeating calculations, which already had been made by this bundle.
Is it possible?

**Comment by robfrawley** [comment]
You can inject the [`FilterService`](https://github.com/liip/LiipImagineBundle/blob/2.0/Service/FilterService.php) into a controller or service of your own and use the [`createFilteredBinary`](https://github.com/liip/LiipImagineBundle/blob/2.0/Service/FilterService.php#L143) method to request a [`BinaryInterface`](https://github.com/liip/LiipImagineBundle/blob/2.0/Binary/BinaryInterface.php) instance.

**Comment by petr-buchin** [comment]
@robfrawley, thank you for your answer, but I see that this method is private. 
But using a dirty hack with reflection I can or `Closure::call()` I can use the private method.

But also I have the question:
If I call `createFilteredBinary` first, and then call `FilterService::getUrlOfFilteredImage()` - will image be downloaded from bucket once or twice?

**Comment by robfrawley** [comment]
My bad; I forgot that method wasn't public. Calling `createFilteredBinary` and `getUrlOfFilteredImage` will request the cached image twice, which can be an expensive operation if the image is cached on Amazon S3.

You can alternatively inject the [`DataManager`](https://github.com/liip/LiipImagineBundle/blob/2.0/Imagine/Data/DataManager.php), [`FilterManager`](https://github.com/liip/LiipImagineBundle/blob/2.0/Imagine/Filter/FilterManager.php), and [`CacheManager`](https://github.com/liip/LiipImagineBundle/blob/2.0/Imagine/Cache/CacheManager.php) to essentially duplicate the logic inside [`FilterService`](https://github.com/liip/LiipImagineBundle/blob/2.0/Service/FilterService.php), then you can create your own logic to handle multiple calls to the same image with an array caching layer something in your own service.

**Comment by petr-buchin** [comment]
@robfrawley thank you, I'll give it a try!
