### ISSUE TITLE
Display image instead of downloading it?

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1081]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 2.0-dev

```html
                    {% set thumbUrl = asset(i.urlPath) | imagine_filter('my_widen_filter') %}
                    <a href="{{ thumbUrl }}">
                        <img src="{{ thumbUrl }}" title="{{ thumbUrl }}" />
                    </a>
```

When I click on the image, I'd like to open a page that displays the image, rather than downloading it (I'll right-click if I want to do that).  Is there a class or something I can set to get this behavior?  Or even better, a config setting to make that the default?  I know it's messy because the first time the image is called it might have to generate the thumbnail.

**Comment by cedricziel** [comment]
Well the thumbnail generation will redirect the browser to the final location of the cached file. If you want to display a file, just embed it, as you did.

Could you describe the actual behaviour?

**Comment by tacman** [comment]
When I click on that link, instead of opening a new page I get
