### ISSUE TITLE
Add a background to image

### ISSUE THREAD

**Issue by marvin-SL** [liip/LiipImagineBundle#1085]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.8.0

Is there a way to add a background to the image ? 
If I upload an image of 400x200, and upscale it to minimum 800x600, the result will be ugly. I want to add a default background of 800x600 and paste the 400x200 image on it . I didn't find anything related to that in the doc, maybe it's not supported.

thanks

**Comment by robfrawley** [comment]
You can add a [color background](http://symfony.com/doc/master/bundles/LiipImagineBundle/filters/general.html#background) or a [custom filter](http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html#custom-filters) if you want to overlay images or perform another complicated transformation.

**Comment by marvin-SL** [comment]
Thank you
