### ISSUE TITLE
Change Default Branch to `2.0`

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#1088]
@lsmith77 Can we change the default branch from `1.0` to `2.0` now that `2.0.0` has been released?

**Comment by lsmith77** [comment]
@maximgubar can you take care of this? thank you!

@robfrawley Maxim, fellow Liiper, plans to help support the maintenance of this Bundle.

**Comment by robfrawley** [comment]
@lsmith77 Sounds great!

**Comment by maximgubar** [comment]
done
