### ISSUE TITLE
post_processors symfony 4 not working

### ISSUE THREAD

**Issue by drbeef12** [liip/LiipImagineBundle#1093]
Hi there,

I'm a beginner, so maybe my question is stupid, but I can't find a solution for my problem.
What I'm trying to do is adding a post_processors to my imagine.yml

Im using Symfony 4 and liip/imagine-bundle:2.0.x-dev

With the post_precoessors in my yml file:
/media/cache/resolve/hero_small/test.jpg
without it works:
/images/cache/hero_small/test.jpg

Below my configuration:
`liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: images/cache

    loaders:
        default:
            filesystem:
                data_root: "uploads/images/"
                bundle_resources:
                    enabled: true

    driver:               "gd"
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    # define your filter sets under this option
    filter_sets:

        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        hero_small:

            # set your image quality defaults
            jpeg_quality:          75
            png_compression_level: 7

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                upscale:
                    min: [1600, 400]

                thumbnail:
                    size: [1600, 400]
                    mode: outbound
                    allow_upscale: true

            post_processors:
                optipng:
                    strip_all: true
                    level: 5

                jpegoptim:
                    strip_all: true
                    max: 70
                    progressive: true
`

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
