### ISSUE TITLE
Image url with spaces lead to exception in SteamLoader.php file

### ISSUE THREAD

**Issue by aspyropoulos** [liip/LiipImagineBundle#1097]
When the name of an image has spaces the URL path cannot be fetched leading to a NotLoadableException exception at line 65 SteamLoader.php file.

i.e. https://test.domain.com/image url with spaces.jpg 

Using:
- Symfony 3.4.4
- PHP 7.2.5

### Actual result
![liip_image](https://user-images.githubusercontent.com/17390755/40317204-7e62359c-5d29-11e8-8b3f-5d41237e477c.png)

**Comment by franmomu** [comment]
mmm I think this is fixed since a while ago, [there is a test for that](https://github.com/liip/LiipImagineBundle/blob/master/Tests/Functional/Controller/ImagineControllerTest.php#L170).
