### ISSUE TITLE
Problem with thumbnail from to wide pictures

### ISSUE THREAD

**Issue by TELLO0815** [liip/LiipImagineBundle#1106]
I get error if i make thumbnails from pictures if they are to wide in there original size. Like to make thumbnail from picture 2.500 x 1.500 pixel is possible. But from 5.500 x 3.500 pixel i get error.
This has nothing to do with the data-size. From small 5.5 MB is o.k. , but from big 2,5 MB is not working.

Is this a problem of the php setting for the script runtime?

ERROR:
```

(1/1) OutOfMemoryExceptionError: Allowed memory size of 134217728 bytes exhausted (tried to allocate 48771073 bytes)
--
in Image.php (line 617)


```

**Comment by TELLO0815** [comment]
memory_limit -1 is fixing my problem.

**Comment by qlerebours** [comment]
This answer is not a solution to the problem, there are many reasons why it's not always possible to set memory limit to -1 ...

**Comment by dbu** [comment]
@qlerebours you are welcome to post other solutions if you find any. its probably an issue with the imagine library, not the LiipImagineBundle.

**Comment by qlerebours** [comment]
The only solution I found is to restricting image upload to files lighter than 1Mo... I use the bundle with Sylius. 1 Mo is enough for e-shop pictures
