### ISSUE TITLE
doc need update 

### ISSUE THREAD

**Issue by lcp0578** [liip/LiipImagineBundle#1109]
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml" #not routing.xml

**Comment by maximgubar** [comment]
@lcp0578 could you please specify which doc needs to be updated ?

**Comment by lcp0578** [comment]
@maximgubar http://symfony.com/doc/master/bundles/LiipImagineBundle/installation.html#step-3-register-the-bundle-s-routes
thx

**Comment by maximgubar** [comment]
@lcp0578 thank you for clarifying, as you can see in the source code of [doc](https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/installation.rst#step-3-register-the-bundles-routes) everything is up to date since 7 May 2017.
we will try to update the doc on SF side as well.

**Comment by lcp0578** [comment]
@maximgubar great work +_+.
