### ISSUE TITLE
DataManager: careless handling of LoderInterface->find() return values

### ISSUE THREAD

**Issue by sandrinr** [liip/LiipImagineBundle#1113]
The `LoaderInterface->find()` method requires the implementor to return a `BinaryInterface` or a string. The `DataManager->find()` method, however, also allows non `BinaryInterface` or `string` returns of an image loader.

```php
        $binary = $loader->find($path);
        if (!$binary instanceof BinaryInterface) {
            $mimeType = $this->mimeTypeGuesser->guess($binary);
            $binary = new Binary(
                $binary,
                $mimeType,
                $this->extensionGuesser->guess($mimeType)
            );
        }
```

Our old loaders returned an Imagine `Image` object. They are not of type `BinaryInterface`. With the code above this `Image` object is just wrapped by a `Binary` object. The problem is now that the `SimpleMimeTypeGuesser` guesser, which is also used in the code above, stores the "binary" to the disk using:

```php
file_put_contents($tmpFile, $binary);
```

This code implicitly transforms `$binary` to a string. The Imagine `Image` object does this like that:

```php
    public function __toString()
    {
        return $this->get('png');
    }
```

As you can see the image is converted to PNG and therefore the resulting transformed image will always be a PNG and not be sensitive to the input type.

I understand that this is somewhat a specific problem but I guess for people migrating from an ancient version of the LiipImagineBundle to a current one (like us) this might be a common issue because operating on the Imagine `Images` was common then in image loaders. There might even be some apps out there which silently convert all their images to PNG, regardless of the input format.

So it might be worth making this check in the `DataManager->find()` method more strict as in if the loader's return value is not a `string` or a `BinaryInterface` then throw an error.

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
