### ISSUE TITLE
assets with version configured

### ISSUE THREAD

**Issue by TiMESPLiNTER** [liip/LiipImagineBundle#1116]
### Preconditions

1. Set a version under `framework.assets.version`
2. Require the image using like `asset(i.imagePath) | imagine_filter('item_list')` in twig

### Steps to reproduce

1. View a page where the image is embedded like mentioned above
2. The url then is `http://exmaple.com/media/cache/resolve/filter/IMG_6776.jpg%3Fv5`
3. The imagine twig extension then tries to find the file `IMG_6776.jpg%3Fv5` which obviously does not exist

### Expected result

1. It should work and any query parameters should be ignored

### Actual result

1. The image can not be displayed

**Comment by rejinka** [comment]
This also filters away the scheme. We use gaufrettes StreamWrapper to reference files like app://images/some_image.jpg
