### ISSUE TITLE
Not found image with apostrophe in filename

### ISSUE THREAD

**Issue by davidromani** [liip/LiipImagineBundle#1118]
There is a "Source image could not be found" exception on `liip/imagine-bundle/Controller/ImagineController.php line 110` when a filename contains an apostrophe character like this https://www.fileformat.info/info/unicode/char/02bc/index.htm

### Preconditions

```
$ composer show liip/imagine-bundle
name     : liip/imagine-bundle
descrip. : This bundle provides an image manipulation abstraction toolkit for Symfony-based projects.
keywords : bundle, image, imagine, liip, manipulation, photos, pictures, symfony, transformation
versions : * 1.9.1

$ php -v
PHP 7.2.8 (cli) (built: Jul 20 2018 12:45:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.1, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies
```

### Steps to reproduce

1. use VichUploaderBundle to upload a file with an apostrophe char like this: "56af7226afae4_test_d’arenys.JPG" in an entity attribute
2. use LiipImagineBundle to render a thumbnail version of the image

### Expected result

1. a thumbnail image rendered in the responsed webpage

### Actual result

1. missing image resource (404)

**Comment by toriqo** [comment]
nah, this crappy bundle throws that error randomly even with perfectly fine images/file names :)

**Comment by dbu** [comment]
yep, if you find the call to `random()` that throws errors when the file name is perfect, you get bonus points

**Comment by toriqo** [comment]
No need to. I just refresh the page displaying 10 photos using this bundle and I get the same error for about half the images. On every refresh, I get the error for different images, so one image works on one page load, on the next is 404 👍🏻
