### ISSUE TITLE
Is it possible to use an absolute path instead of a loader?

### ISSUE THREAD

**Issue by sdespont** [liip/LiipImagineBundle#1119]
I need to create thumbnails from sets of images not stored in a public folder. The images are stored in different places, so I have to create `loaders` and `filters` for every images locations in my config. 

Is there a way to not use a `loader` but specify the absolute path to create thumbnail?

```
private function renderThumbnail(string $filter, string $filename)
{
    // Is it possible to use an absolute path instead of the file name? 
    // At this time, it is not possible because filters depends on loader to find the image.
    $image = $this->imageDataManager->find($filter, $filename);
    $response = $this->imageFilterManager->applyFilter($image, $filter);
    return $response->getContent();
}
```

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
