### ISSUE TITLE
AmazonS3 not Found in AmazonS3Resolver 

### ISSUE THREAD

**Issue by OsvalGuiany** [liip/LiipImagineBundle#1123]
Hello, I want to cache my images in S3 with liip-imagine.I followed the  [Symfony documentation on liip-imagine](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolver/aws_s3.html). But when I register the resolver service, I have the following error when I debug the container.

Fatal error: Class 'AmazonS3' not found in /opt/lampp/htdocs/Application/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php on line 265

In AutowirePass.php line 265:
                                                                 
  Attempted to load class "AmazonS3" from the global namespace.  
  Did you forget a "use" statement? 

please I want your help.

**Comment by cedricziel** [comment]
I guess something is outdated. Have you tried the other AWS resolver? http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolver/amazons3.html

**Comment by OsvalGuiany** [comment]
I tried it and it works well. Thank.
