### ISSUE TITLE
Resize / Upload multiple images in the same time into my S3 Bucket

### ISSUE THREAD

**Issue by pavelmocean** [liip/LiipImagineBundle#1124]
**Is your feature request related to a problem? Please describe.**
I use Liip Imagine with gaufrette and Aws cache adapter.
The thing is that upload to S3 bucket takes pretty much (3 seconds).

What I do:
 - upload an image
 - resize it into multiple sizes + upload to S3 by calling "getUrlOfFilteredImage" method
![image](https://user-images.githubusercontent.com/37793174/44862252-f753f280-ac82-11e8-9430-9deb1b716c2d.png)

Problems:
 - as you can see, it takes pretty much time

Questions:
 - is there a way to do this resize/upload in parallel?  - it would help a lot

Proposal:
 - I've seen that in Aws sdk there is a method "putObjectAsync"
 - is there a way to use this one?

I really don't know what else to do, I've played with the bundle settings for over two weeks, and this paralel upload will really speed up my api., or maybe you have other suggestions ?

Thanks.

**Comment by dbu** [comment]
from the architecture of this bundle, i don't see how we could do this. however, if you use the async mechanism to warm up the cache when a file is added (enqueue, or symfony messenger added in #1360) you could maybe warmup a local cache and then sync it to S3 - or if you warmup async, you can parallelize by having multiple workers and the delay is not as much of a problem.
