### ISSUE TITLE
Pre and Post store events

### ISSUE THREAD

**Issue by loevgaard** [liip/LiipImagineBundle#1126]
**Is your feature request related to a problem? Please describe.**
I use LiipImagineBundle with Sylius and need to update the product entity when an image is stored, but right now I have to do that using filters or post processors, which is kind of a hacky way to do it.

**Describe the solution you'd like**
Wrap this line: https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/CacheManager.php#L218 with `PRE_STORE` and `POST_STORE` events.

**Comment by dbu** [comment]
duplicate of #1280
