### ISSUE TITLE
What is the best way to protect source images?

### ISSUE THREAD

**Issue by bocharsky-bw** [liip/LiipImagineBundle#1129]
I add a watermark for images at runtime with this bundle. What if I want to hide all source images that do not have the watermark? I mean, I want to protect source image leaking. I wonder what is the best way to protect source images from being downloaded?

For example, I upload source images to `public/uploads/images/`, but this folder is public, so everyone who can guess the link to the source images can download them. And guess the link is easy, e.g. base on a thumbnail link like `http://localhost:8000/media/cache/squared_thumbnail/uploads/images/default.jpg` I can guess the proper link to the source image is `http://localhost:8000/uploads/images/default.jpg`.

I suppose I cannot just upload images to a not public directory, because LiipImagineBundle won't work as it requires publicly accessible images for making thumbnails, etc.

Any suggestions? Thanks

**Comment by maximgubar** [comment]
@bocharsky-bw as soon as you expose images or send them somehow to client - they are public and can be saved. the question itself is more copyright-related. try to look towards services like https://pixray.com/ or similar.
