### ISSUE TITLE
Undocumented upgrade path for ImagineController extension

### ISSUE THREAD

**Issue by garak** [liip/LiipImagineBundle#1130]
I'm using LiipImagineBundle 1.9 and trying to upgrade to latest (currently 2.1)
I see that `ImagineController` changed a lot, but UPGRADE.md doesn't provide an upgrade path.
So, in 1.9 I'm extending `ImagineController` and overriding `filterAction`. It looks like this is not possible anymore, since such controller now has private injected services (anyway, it's not marked as final).
I found that commit 58603f326ccea75ed7577aad5d768746b411e274 is supposed to document such change, but unfortunately it looks like it lacks a lot of information.

I guess that I need to define my own `ImagineController` without extending original one, is that the advised way?
Anyway, I think that UPGRADE.md should mention such change.

**Comment by michellesanver** [comment]
Thanks, I'll look at the changes and see if I can update our documentation.

**Comment by garak** [comment]
Hi, just found myself in another upgrade and with same problem.
Any news?

**Comment by garak** [comment]
I finally found a decent solution, decorating ImagineController with a service of mine.
