### ISSUE TITLE
 FilterService->createFilteredBinary() is private

### ISSUE THREAD

**Issue by atomicus** [liip/LiipImagineBundle#1134]
Upgrade guide to 2.0 states that ` createFilteredBinary()` on FilterService was added (along with `getUrlOfFilteredImageWithRuntimeFilters()`).

But, it's private, so there's no real use for that now - and this would be really useful in case of using the bundle to process images without actually displaying them.

It looks that it's simple error, if so, I'm happy to provide PR.

**Comment by michellesanver** [comment]
It sounds useful to have this be public, if you still want to provide that PR it would be great @atomicus! Thanks a lot. And if you no longer want to do that, this would be an excellent first issue for someone to pick up.

**Comment by atomicus** [comment]
Sure, I'll do it, just need to dust it off.

**Comment by emancypage** [comment]
I am waiting for this feature! :)

**Comment by dbu** [comment]
i am cleaning up old issues. if somebody wants to work on this, please reopen the issue.
