### ISSUE TITLE
data_root ignored on windows with xampp

### ISSUE THREAD

**Issue by Doccos** [liip/LiipImagineBundle#1136]
my Config:
`liip_imagine:

  driver: "gd"
  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%/upload/'
  filter_sets:
thumbnails
    profile_max:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [120, 120]
          mode:          outbound
          allow_upscale: true
    news_preview:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [190, 140]
          mode:          inset`

output from php console debug:config liip_imagine:

`
liip_imagine:
    driver: gd
    loaders:
        default:
            filesystem:
                data_root:
                    - 'C:\xampp\htdocs\akb/upload/'
                locator: filesystem
                bundle_resources:
                    enabled: false
                    access_control_type: blacklist
                    access_control_list: {  }
    filter_sets:
        profile_max:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                auto_rotate: {  }
                strip: {  }
                thumbnail:
                    size:
                        - 120
                        - 120
                    mode: outbound
                    allow_upscale: true
            quality: 100
            png_compression_filter: null
            format: null
            animated: false
            cache: null
            data_loader: null
            default_image: null
            post_processors: {  }
        news_preview:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                auto_rotate: {  }
                strip: {  }
                thumbnail:
                    size:
                        - 190
                        - 140
                    mode: inset
            quality: 100
            png_compression_filter: null
            format: null
            animated: false
            cache: null
            data_loader: null
            default_image: null
            post_processors: {  }`

but i get the error: `Source image for path "akb/public/news/3.jpg" could not be found`

why does it look in the public directory ?
it should look in the akb/upload/news/ directory

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
