### ISSUE TITLE
Set strict depepnedcy of "enqueue/enqueue-bundle": "0.8.*"

### ISSUE THREAD

**Issue by andrew-svirin** [liip/LiipImagineBundle#1140]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by robfrawley** [comment]
Why the change? The current value of `^0.8` is functionally equivalent to `0.8.*`. Why drop support for `^0.7`? Do we rely on any breaking changes between the two versions?

**Comment by AndriySvirin** [comment]
Hi, 0.7 did not tried. but tried 0.9. i dd not know how it was installed, but it is very different with 0.8 and documentedless

**Comment by franmomu** [comment]
I guess this can be closed https://github.com/liip/LiipImagineBundle/pull/1207

**Comment by dbu** [comment]
thanks
