### ISSUE TITLE
Configure enqueue

### ISSUE THREAD

**Issue by andrew-svirin** [liip/LiipImagineBundle#1142]
### Preconditions

1. Symfony 4. 
2. Enqueue 0.8 with Filestorage

### Steps to reproduce

1. Run enqueue background process for render caches. (enqueue:consume)
2. Look on permissions on files (user:user) (0 -rw------- 1 user      user         0 Nov 30 08:53 liip_imagine_resolve_cache)
3. Add cache build request (Fail: Permissions denied)

### Expected result

1. Setup correct permissions for edit

### Actual result

1. [Screenshot, logs]

**Comment by AndriySvirin** [comment]
Do i need to set permissions on file manually after run enqueue:consume ?

**Comment by michellesanver** [comment]
Hi @andrew-svirin, is this still an issue for you?

**Comment by andrew-svirin** [comment]
Hi @michellesanver thanks for asking. I do not supporting this project and can not to check. Issue can be closed.

**Comment by michellesanver** [comment]
Thanks for the quick answer @andrew-svirin, closing the issue. 👍
