### ISSUE TITLE
Resolve Paths On Configuration / Ignore Non-existing Paths

### ISSUE THREAD

**Issue by kiler129** [liip/LiipImagineBundle#1144]
**Is your feature request related to a problem? Please describe.**
In symlinked environments (e.g. using Deployer) setting paths is tricky. Currently we basically configure path to `%kernel.project_dir%/public/media`, but on the production this path is symlinked to shared folder. This causes problems, since the library thinks that we're attempting write outside of the configured root (well, it's right actually).

This is hard for testing on local with production environment specified where structure of directories is not exactly the same in terms of symlinks.

**Describe the solution you'd like**
I see two solutions:
1. Resolving symlinks specified in `data_root` when we load settings (so effectively on DIC build)
2. Adding option to ignore missing directories so that I can set `['%kernel.project_dir%/public', '%kernel.project_dir%/../shared/public/media']`

**Describe alternatives you've considered**
Creating symlinks on local works, doing a small hack where I register my own service with name `liip_imagine.binary.locator.filesystem` which implements 2nd solution also produces expected result.
I was thinking about adding an option to define custom filesystem locators (since currently `locator` on `filesystem` loader is hardcoded to only accept `['filesystem', 'filesystem_insecure']` and I will like to use this loader due to other options available).

**Comment by robfrawley** [comment]
> I was thinking about adding an option to define custom filesystem locators.

:+1:

**Comment by dimonx3** [comment]
I also have such a problem

**Comment by dbu** [comment]
i am cleaning up old issues.  if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
