### ISSUE TITLE
SymfonyFramework::getContainerResolvableRootWebPath fails on SF 3.4 with flex directory structure

### ISSUE THREAD

**Issue by scuben** [liip/LiipImagineBundle#1145]
When using SF 3.4 with the flex directory structure `SymfonyFramework::getContainerResolvableRootWebPath()` returns the `web` path which is wrong.

**Comment by robfrawley** [comment]
Have time to submit a PR?

**Comment by scuben** [comment]
Maybe. How should it be done? Checking for existence of the public directory and return that if it exists and otherwise return web?

**Comment by scuben** [comment]
@robfrawley may you give me a short answer about how the way should be to tackle that issue?

**Comment by franmomu** [comment]
As far as I know, `SymfonyFramework::getContainerResolvableRootWebPath()` is only used as default value for some options, so you can configure those options directly.
