### ISSUE TITLE
Nginx + Symfony 4

### ISSUE THREAD

**Issue by JacobDelcroix** [liip/LiipImagineBundle#1151]
Hello guys,

I'm using "liip/imagine-bundle": "^2.1" and I can't get it working on production with Nginx...
I use the recommended Nginx Symfony configuration https://symfony.com/doc/current/setup/web_server_configuration.html#nginx but all LiipImagine routes give me 404.

All is fine on my local desktop (Apache).

Can someone help me to configure Nginx to work with this bundle ?

Best regards,
Jacob.

**Comment by broiniac** [comment]
Hi,
can You please try to replace:
```
location / {
    # try to serve file directly, fallback to index.php
    try_files $uri /index.php$is_args$args;
}
```
with this:
```
location / {
    try_files $uri @rewrite_framework_symfony;
}

location @rewrite_framework_symfony {
    rewrite ^(.*)$ /index.php/$1 last;
}
```
Did it work?

PS: Don't forget to restart nginx after editing it's config.

**Comment by JacobDelcroix** [comment]
Hi and thanks for your reply.

Here is my Nginx conf:

> location / {
>     try_files $uri @rewrite_framework_symfony;
> }
> 
> location @rewrite_framework_symfony {
>     rewrite ^(.*)$ /index.php/$1 last;
> }
> 
> location ~ ^/index\.php(/|$) {
> 	fastcgi_pass unix:/run/php/php7.3-fpm.sock;
> 	fastcgi_split_path_info ^(.+\.php)(/.*)$;
> 	include fastcgi_params;
> 	fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
> 	fastcgi_param DOCUMENT_ROOT $realpath_root;
> 	internal;
> }

But it's not working :(

Here is a 404 error: http://beta.japanread.net/media/cache/resolve/manga_medium/images/mangas/cover/pg%2067.jpg
But the original file is working http://beta.japanread.net/images/mangas/cover/pg%2067.jpg

Everything is working as expected on my local and preprod environment (Apache)

**Comment by robfrawley** [comment]
Give https://github.com/liip/LiipImagineBundle/issues/784#issuecomment-320150743 a read.
