### ISSUE TITLE
There is no extension able to load the configuration (Symfony 4). 

### ISSUE THREAD

**Issue by heigold1** [liip/LiipImagineBundle#1155]
Hi, 

I'm probably not setting this up right, but I'm getting the following error and I think it has to do with my bundles.php file: 

There is no extension able to load the configuration for "_liip_imagine" (in /var/www/vhosts/------.com/config/packages/routing.yaml). Looked for namespace "_liip_imagine", found "framework", "doctrine_cache", "sensio_framework_extra", "doctrine", "doctrine_migrations", "security", "swiftmailer", "web_profiler", "twig", "monolog", "debug", "web_server", "maker", "doctrine_fixtures", "aws", "knp_paginator", "fos_js_routing" in /var/www/vhosts/--------.com/config/packages/routing.yaml (which is loaded in resource "/var/www/vhosts/-------.com/config/packages/routing.yaml").

So obviously it is going through my \config\bundles.php and looking for the liip entry there. 

How do I add it to the \config\bundles.php file?

**Comment by robfrawley** [comment]
The configuration index for this bundle is `liip_imagine` and **not** `_liip_imagine` *(remove the leading underscore in your configuration).

**Comment by ruffineEliane** [comment]
There is no extension able to load the configuration for "app" (in "D:\LeadGeneration\lead-backend\config/packages/routing.yaml"). Looked   
  for namespace "app", found ""framework", "twig", "security", "doctrine", "doctrine_migrations", "nelmio_cors", "api_platform"".

**Comment by dbu** [comment]
not sure what you mean, but this seems to be in the routing configuration. sounds like a mistake not related to this bundle. have you maybe instead of trying to define route configuration put a symfony configuration into that file?
