### ISSUE TITLE
Cached images are not loaded in dev environment

### ISSUE THREAD

**Issue by molarro** [liip/LiipImagineBundle#1159]
If I am in `dev` environment (`app_dev.php`) cached images are not found - they are found only if I am in `prod` environment, i.e. http://website.com/media/cache/resolve/item_img_preview_6/uploads/gallery/5c6c.jpg - works, but http://website.com/app_dev.php/media/... - not working. 

### Preconditions

1. Symfony 3.4.
2. LiipImagineBundle version - 2.1.0
3. Docker is used. 
4. `intercept_redirects `is set to `false` in `config_dev.yml`

### Expected result

Cached images are loaded both in `dev` and `prod` environment.

**Comment by michellesanver** [comment]
I wonder if this is somehow related? https://github.com/liip/LiipImagineBundle/issues/1133 🤔

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
