### ISSUE TITLE
Driver error report 

### ISSUE THREAD

**Issue by Raneomik** [liip/LiipImagineBundle#1167]
Hello,

I'm currently experimenting LiipImagine filter rendering, with its standart configuration and "gd" driver, in a Docker container, and I forgot one  important line to configure the GD extension. And I had the following error :
```
Uncaught PHP Exception RuntimeException: "Unable to create image for path "<original_image_file_path>" and filter "<imagine_filter>". Message was "Unable to open image "<original_image_file_path>" at /var/www/html/vendor/liip/imagine-bundle/Controller/ImagineController.php line 86 {"exception":"[object] (RuntimeException(code: 0): Unable to create image for path \""<original_image_file_path>"\" and filter \"<imagine_filter>\". Message was \"Unable to open image <original_image_file_path>\" at /var/www/html/vendor/liip/imagine-bundle/Controller/ImagineController.php:86, Imagine\\Exception\\RuntimeException(code: 0): Unable to open image <original_image_file_path> at /var/www/html/vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php:96)"} []
```
And I didn't know why it is `Unable to open image <original_image_file_path> at /var/www/html/vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php:96`.

So I had to modify `vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php` by adding `error_get_last()['message']` after `@createimagefromstring()` to finaly solve my problem (by adding the gd configuration line in Dockerfile, present in all findable tutorials / solved issues - shame on me).

Being a rookie in devops and specialy in Docker, Is there a method / Docker configuration to follow to had more details about LiipImagineBundle errors (an error collector/container - collecting php errors to a specific php log) or can I suggest a more verbose error reporting inside this driver handler ?

Thanks

**Comment by Raneomik** [comment]
FIY: If ever you wonder, the GD configuration line that solved my problem is 
`docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/`
 - not knowing what it exactly means (I guess it specifies an image tmp path to handle images by their type, gd not having this path by default ...?), I didn't accord a huge importance to it, but it seems very important. So if anyone could provide an explanation why it is so important, I'd be really glad for that

**Comment by dbu** [comment]
this sounds to me like imagine could be improved to try the error_get_last when this fails, to create a better exception. i don't think its the right place to put something for this into the bundle. (though somebody could add a command to check the setup and report if anything does not work well. but even that sounds like it would be better part of imagine itself, as its not symfony specific)

**Comment by mlocati** [comment]
Just a site note: I created a shell script to install PHP extensions easily.
You can find it at https://github.com/mlocati/docker-php-extension-installer
