### ISSUE TITLE
PHP 7 & LiipImagineBundle 2.1 / Parse error: syntax error, unexpected '?'

### ISSUE THREAD

**Issue by wonich** [liip/LiipImagineBundle#1168]
I need your help. We are not able to update to an highter PHP-Version then 7.0.

When we use the LiipImagineBundle to generate automaticaly thumbnails. we are getting the follow error message:

Parse error: syntax error, unexpected '?'

in vendor/liip/imagine-bundle/Binary/Locator/FileSystemLocator.php (line 61)
`protected function generateAbsolutePath(string $root, string $path): ?string`

does anyone has an idea to fix this?

**Comment by dbu** [comment]
what version of LiipImagineBundle are you using? the current version has the requirement ^7.1 for PHP. the nullable type syntax `?string` is only available since PHP 7.1 but not in 7.0.

(i hope you did not run composer with the ignore platform requirements option. if you did, then please don't and the problem should go away)

**Comment by wonich** [comment]
Hi dbu....

thx for your reply...
We are using 2.1 ... Is there. We have also try it with 2.0. the same... should we use an older version?

**Comment by dbu** [comment]
what php version are you using, and how do you call composer to install the dependencies?

**Comment by wonich** [comment]
PHP-Version: 7.0.33 -0+deb9u3
Before Composer-Call we remove the package with: composer remove liip/imagine-bundle
Composer-Call for Version 2.1: composer require liip/imagine-bundle
Composer-Call for Version 2.0: composer require liip/imagine-bundle:^2.0

**Comment by dbu** [comment]
when i look at https://packagist.org/packages/liip/imagine-bundle, the imagine-bundle 2.1 requires php 7.1, so i don't understand how these commands would end up installing that version of the bundle. are you sure you are not using `--ignore-platform-reqs` while doing the `require`? if you don't that looks like a composer bug, which would quite surprise me.

if you want to use a recent version of this bundle, use php 7.1 or newer. if you can't, use ^1.9 which does support php 5 and 7.0 (but is not maintained anymore, just as php 7.0 is not a current version of php anymore). i'd expect composer to install 1.9 with your commands run on a php 7.0 machine but you can force that by specifying the ^1.9 constraint.

**Comment by wonich** [comment]
Hey dbu...
Thank you for your answer. Yes we are sure we dont use this command :-) But it could be that there still exist the PHP Version 7.1 for CLI... that could become to this situation.
however... the reason why we dont update to PHP 7.1 is: we use debian... and on debian the php extension bcmath only exist for PHP 7.0 ...
we try it with your version-hint. thanks a lot.
