### ISSUE TITLE
Optimize a picture with liip imagine bundle

### ISSUE THREAD

**Issue by florent6001** [liip/LiipImagineBundle#1179]
Hi all,

I'm trying to optimize my website on google pagespeed. The image generated by liip is ~300kb and can have -180kb.

How can i optimize it ? It's possible to work with tinypng ? 
I saw optiPNG in your documentation : (https://symfony.com/doc/2.0/bundles/LiipImagineBundle/post-processors/png-opti.html)

But i'm on Windows pre-prod and Linux production,

In the documentation, we see how to configuration the bundle for work with optiPNG, but here : /your/custom/path/to/optipng what is the type of the executable please and how to work with it on both system ? Can i install optiPNG on my public folder ?

**Comment by franmomu** [comment]
Hi there, 

The `liip_imagine.optipng.binary` parameter defines where the Opti PNG executable is. So if you work with different environments, you can define this parameter in each environment differently.

For PNG there is also a [PNG Quant post processor](https://symfony.com/doc/2.0/bundles/LiipImagineBundle/post-processors/png-quant.html) and if you want to use another one, you can always create your own with a [custom post processor](https://symfony.com/doc/2.0/bundles/LiipImagineBundle/post-processors.html#custom-processors).
