### ISSUE TITLE
Version/milestones?

### ISSUE THREAD

**Issue by stephanvierkant** [liip/LiipImagineBundle#1186]
It's been a long time since the last stable release of this bundle. The milestones aren't up to date right now: https://github.com/liip/LiipImagineBundle/milestones.

Can someone tag a new version or update the milestones, so we can track when a new version will be released?

**Comment by garak** [comment]
I would also appreciate a new release, since Imagine has a lot of deprecations and I can't use its latest version (fixed in master, unreleased).

**Comment by dbu** [comment]
changelog looks quite unmaintained. if someone could look over https://github.com/liip/LiipImagineBundle/compare/2.1.0...master and do a PR to add things to the changelog as necessary, that would be a great help.

**Comment by dbu** [comment]
@michellesanver @franmomu wdyt, can we tag a release now, with symfony 4 no deprecations support?

**Comment by michellesanver** [comment]
I think it would make sense

**Comment by franmomu** [comment]
It looks good to me!

**Comment by michellesanver** [comment]
2.2.0 was released this morning! (YAY! FRIDAY RELEASE PARTY! :D) 

Thanks everyone for your contributions. Means a lot to this library. And let me know if anything went under or I missed anything. Just getting into this library as its new maintainer 👍
