### ISSUE TITLE
Changing default path %kernel.root_dir%  to aws bucket path

### ISSUE THREAD

**Issue by kstepanyan111** [liip/LiipImagineBundle#1189]
Unable to remove %kernel.root_dir% from dynamic filter .

### Preconditions

1. ` "liip/imagine-bundle": "^2.1",`
2. `"php": "^7.1.3",`
3. ` "symfony/framework-bundle": "4`
4. `"symfony/http-foundation": "4.2.*",`

Creating dynamic filter for watermarking images 
```
$runtimeConfig = [
    'thumbnail' => [
    'size' => [500, 500]
    ],
  'watermark' => [ 
       "image" => $this->aws->getPresignedUrl("photos/watermarks/mgName.png"),
        'size' => 0.5
           ]
      ];
```
Usage 
``` 
$cachePath =  $this->filterService->getUrlOfFilteredImageWithRuntimeFilters("$basePath/temp/$newFileName",'thumb_filter', $runtimeConfig );
```
Getting error 
```
File /var/www/photo-api/src/https://photo.s3.us-east-2.amazonaws.com/photos/watermarks/5d09d7f23fe10f0a2c25bc70/7975346b25e27b79e2c4a44c48d1asdw.png
```
System is prepending `%kernel.root_dir%` to amazon url . 
How I can use only bucket url and prevent system appending . 
Tried to set **web_root**  but did not help.

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
