### ISSUE TITLE
Resolve cache images in background not working

### ISSUE THREAD

**Issue by florianajir** [liip/LiipImagineBundle#1191]
The process explained on the [symfony doc](https://symfony.com/doc/2.0/bundles/LiipImagineBundle/resolve-cache-images-in-background.html) to resolve cache images in background is not working

### Preconditions

1. liip/imagine-bundle v2.1.0
2. enqueue/enqueue-bundle v0.9.12

### Steps to reproduce

1. Install both bundles mentioned above
2. Create a symfony command that try to resolve a file path with this line
`$this->producer->sendCommand(Commands::RESOLVE_CACHE, new ResolveCache($filename, 'my_filter'));`
3. You'll have an error because enqueue.producer does not exists in actual version of enqueue-bundle (there is no indication in the doc about which bundle version actually working) so I declared an alias in services.yaml `enqueue.producer: '@enqueue.client.default.producer'`

### Actual result
```
In GenericDriver.php line 91:

  [LogicException]
  There is no route for command "liip_imagine_resolve_cache".


Exception trace:
 () at /application/vendor/enqueue/enqueue/Client/Driver/GenericDriver.php:91
 Enqueue\Client\Driver\GenericDriver->sendToProcessor() at /application/vendor/enqueue/enqueue/Client/Producer.php:123
 Enqueue\Client\Producer->doSend() at /application/vendor/enqueue/enqueue/Client/Producer.php:85
 Enqueue\Client\Producer->sendCommand() at /application/vendor/enqueue/enqueue/Client/TraceableProducer.php:33
 Enqueue\Client\TraceableProducer->sendCommand() at /application/vendor/enqueue/enqueue/Symfony/Client/LazyProducer.php:30
 Enqueue\Symfony\Client\LazyProducer->sendCommand() at /application/src/Command/S3CacheGenerateCommand.php:62
```

**Comment by stvalett** [comment]
+1

**Comment by youssef-hiit** [comment]
Same Issue did you solve it ?
