### ISSUE TITLE
Images served over HTTP instead of HTTPS

### ISSUE THREAD

**Issue by DennisdeBest** [liip/LiipImagineBundle#1196]
I am running my symfony 4.3 app in a docker container with Traefik reverse proxy and all images using the liip imagine filter are served over http instead of https.

I haven't found a way to get this to work correctly, any help would be greatly appreciated.
### Preconditions

Syfmony 4.3 running inside a php-7.3:alpine container
Traefik 1.7 reverse proxy 

Traefik labels:
     - "traefik.enable=true"
     - "traefik.docker.network=web"
     - "traefik.frontend.rule=website.com"
     - "traefik.frontend.protocol=https"
     - "traefik.redirect.entryPoint=https"

Traefik.toml :

debug = true
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[web]
# Port for the status/dashboard page
address = ":8080"

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

    [entryPoints.https]
    address = ":443"

[api]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedByDefault = false

[acme]
email = "name@email.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
    [acme.httpChallenge]
    entryPoint = "http"

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

The image links should be served over https

### Actual result

Every image link uses a http

**Comment by DennisdeBest** [comment]
Turns out you need to configure the trusted proxies for this to work correctly. 
the awnser is at :
https://github.com/liip/LiipImagineBundle/issues/727
set
TRUSTED_PROXIES=127.0.0.1, 172.20.0.0/8
in .env.local fixes the issues for me (because traefik runas at 172.20.0.0 if tour reverse proxy uses a different IP you need to adjust these settings)

So sorry to have bothered you.

**Comment by Manasmd** [comment]
Thank you @DennisdeBest 
This is working great for me! I just have one question, the traefik's IP seems to be changing every time I docker-compose down; and up again. does it mean that we need to update the TRUSTED_PROXIES every time again and again?

**Comment by DennisdeBest** [comment]
@Manasmd 

If the base IP starts with 172 this will work ass the /8 subnet mask means the other parts of the IP can be anything.
