### ISSUE TITLE
Ease overriding of the Binary class

### ISSUE THREAD

**Issue by gnutix** [liip/LiipImagineBundle#1197]
For my current project, I'm using Flysystem and have a custom `PostProcessor` that needs the `$path` information in order to process the images (because we use a custom directory structure that contains information in the path, blablabla - you don't wanna know ;) ).

So, I need to have a custom `PathAwareBinary` class that knows about the `$path`. Exactly similiar to `FileBinary`, but I can't use it as-is because it has extra features in FilterManager (calling `open` instead of `load`, notably).

Anyway, to do that I've created a custom `Liip\ImagineBundle\Binary\Loader\LoaderInterface` instance (that extends `FlysystemLoader`) with the `find()` method as follows : 

```php
final class PathAwareFlysystemLoader extends FlysystemLoader
{
    public function find($path): BinaryInterface
    {
        $binary = parent::find($path);

        return new PathAwareBinary($path, $binary->getContent(), $binary->getMimeType(), $binary->getFormat());
    }
}
```

That works nicely and is clean enough for my taste.

However, the `FilterManager` class **recreates a new Binary object** in its private `exportConfiguredImageBinary()`, meaning I loose the path information that I need to have access to later in my custom PostProcessor.

The only way around that is currently to override much of the `FilterManager` and literally copy-paste all this code : 

```php
final class PathAwareFilterManager extends FilterManager
{
    public function applyFilters(BinaryInterface $binary, array $config): BinaryInterface
    {
        if ($binary instanceof FileBinaryInterface) {
            $image = $this->imagine->open($binary->getPath());
        } else {
            $image = $this->imagine->load($binary->getContent());
        }

        foreach ($this->sanitizeFilters($config['filters'] ?? []) as $name => $options) {
            $prior = $image;
            $image = $this->loaders[$name]->load($image, $options);

            if ($prior !== $image) {
                $this->destroyImage($prior);
            }
        }

        return $this->exportConfiguredImageBinary($binary, $image, $config);
    }

    /**
     * @param BinaryInterface|PathAwareBinary $binary
     */
    private function exportConfiguredImageBinary(BinaryInterface $binary, ImageInterface $image, array $config): BinaryInterface
    {
        $options = [
            'quality' => $config['quality'],
        ];

        if (isset($config['jpeg_quality'])) {
            $options['jpeg_quality'] = $config['jpeg_quality'];
        }
        if (isset($config['png_compression_level'])) {
            $options['png_compression_level'] = $config['png_compression_level'];
        }
        if (isset($config['png_compression_filter'])) {
            $options['png_compression_filter'] = $config['png_compression_filter'];
        }

        if ('gif' === $binary->getFormat() && $config['animated']) {
            $options['animated'] = $config['animated'];
        }

        $filteredFormat = $config['format'] ?? $binary->getFormat();
        $filteredString = $image->get($filteredFormat, $options);

        $this->destroyImage($image);

//       return new Binary(
         return new PathAwareBinary(
            $binary->getPath(),
            $filteredString,
            $filteredFormat === $binary->getFormat() ? $binary->getMimeType() : $this->mimeTypeGuesser->guess($filteredString),
            $filteredFormat
        );
    }

    private function sanitizeFilters(array $filters): array
    {
        $sanitized = array_filter($filters, function (string $name): bool {
            return isset($this->loaders[$name]);
        }, ARRAY_FILTER_USE_KEY);

        if (count($filters) !== count($sanitized)) {
            throw new \InvalidArgumentException(sprintf('Could not find filter(s): %s', implode(', ', array_map(function (string $name): string {
                return sprintf('"%s"', $name);
            }, array_diff(array_keys($filters), array_keys($sanitized))))));
        }

        return $sanitized;
    }

    private function destroyImage(ImageInterface $image): void
    {
        if (method_exists($image, '__destruct')) {
            $image->__destruct();
        }
    }
}
```

Only for this little change here : 

```diff
-       return new Binary(
+       return new PathAwareBinary(
+           $binary->getPath(),
```

That's not clean enough for my taste...

As the Binary class is only created in `LoaderInterface` instances (which are easy to override) and here, I guess the simplest "solution" would be **1)** to have a `protected` method `FilterManager::createBinary` and call it at the end of `exportConfiguredImageBinary`.

Another idea would be **2)** to provide the `$path` in all `BinaryInterface` classes by default. That would require to add the `$path` as an argument to the following methods of `FileManager`: `applyFilter()`, `apply()`, `applyFilters()`, `exportConfiguredImageBinary()`. Which wouldn't hurt IMHO, as this information is always available anyway and might be useful to some. The `FileBinaryInterface` would still be used to decide if `load` or `open` is called.

WDYT ?

**Comment by dbu** [comment]
2 seems problematic because there are several public methods in your list, so that would be quite some BC break. the factory method sounds a lot safer.

i wonder why the path is not always kept? and would it make sense to have exportConfiguredImageBinary directly do a PathAwareBinary? or would the different methods then be inconsistent? if that is the case, then it would be inconsistent to have a factory method only for one of the methods...
