### ISSUE TITLE
Symfony 4.3 support

### ISSUE THREAD

**Issue by proArtex** [liip/LiipImagineBundle#1200]
Is there any hope for sf 4.3 to have support? For now profiler is full of deprecation notices such as
* `User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.`
* `User Deprecated: The "Symfony\Component\HttpFoundation\File\MimeType\FileBinaryMimeTypeGuesser" class is deprecated since Symfony 4.3, use "Symfony\Component\Mime\FileBinaryMimeTypeGuesser" instead.`
* (/) `The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "liip_imagine" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.` => fixed in #1200

**Comment by dbu** [comment]
glad if you can do a pull request against 2.0 to fix these. for configuration, the pattern i have seen is https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/aa9daf9dea4eb5e26aba5550aec1da5c650b89ed/src/DependencyInjection/Configuration.php#L58-L63

for the others, you'd need to be careful to not break working with older supported symfony versions. sometimes you might need to compare the symfony kernel version to know which way to use, or for the mime type guesser check for existence of the new class.

**Comment by dbu** [comment]
turns out we will ditch the 2.0 branch (as master is the 2.x version) and things should be done against master again.

i realized there is #1185 starting on it, but not respecting BC for 3.4. if you want to pick that up and fix the things @franmomu noted, it would be great

**Comment by dbu** [comment]
fixed in #1213, #1217, #1218, #1212, #1176
