### ISSUE TITLE
Create thumb image without storing 

### ISSUE THREAD

**Issue by Arman-Hosseini** [liip/LiipImagineBundle#1204]
Hi guys.
How do I create an image without saving it?
I want to set the height of the image and get the rendered image without saving.

**Comment by michellesanver** [comment]
I don't think you can render an image without saving it. Do you know if you can do that @dbu?

**Comment by Arman-Hosseini** [comment]
Do you have my problem too? @michellesanver

**Comment by Arman-Hosseini** [comment]
I did this through documents and symfony services. @michellesanver

**Comment by dbu** [comment]
I am not aware of any option to do that currently. I am sure it would be somehow implementable, but would need someone who wants to contribute it (do you want to work on it @Arman-Hosseini?) and you would need to convince the maintainers that the use case is general enough to be needed. If its only about scaling for a preview/admin interface, this could be done in the browser with the image size attributes, or maybe with a nice javascript plugin to decide on what to crop and so on. If its a super specific different use case, it could also make sense that you write your own controller to interact with the LiipImagineBundle services or Imagine library itself.

**Comment by Arman-Hosseini** [comment]
Hi @dbu .
Excuse me I think I haven't spoken clearly about it.
I have some photos on my hosting that I want to resize and display without re-saving them.
I do not know if this library is capable of doing so and I have not fully read the documentation because it is urgent!
In general, this is what I need.

**Comment by dbu** [comment]
the purpose of this bundle is to provide scaled images on websites. as the output will be the same each time the same filter set is applied, it is more efficient to store the result of the filter set. when the image is updated on the server, the cache needs to be cleared.

> and I have not fully read the documentation because it is urgent!

look, this library is developped by people in their spare time and offered for free to use. we are happy if it is useful for you, but we don't do free consulting on top of that.

**Comment by Arman-Hosseini** [comment]
I meant when I asked this question I was in urgent need of it, but now I've solved it and thank you and this great community. @dbu

**Comment by dbu** [comment]
glad to hear!
