### ISSUE TITLE
Any plans to support latest Imagine v1.2.x or making a new release?

### ISSUE THREAD

**Issue by oleg-andreyev** [liip/LiipImagineBundle#1225]
Are there any plans to support latest Imagine v1.2.x?
Right now I see that master branch supports Imagine ^1.1, so 1.2 will be installed, but it was quite a while when new release was created.

https://github.com/liip/LiipImagineBundle/compare/2.1.0...master

**Comment by michellesanver** [comment]
Yes, will try our best to update it when we can! 👍
