### ISSUE TITLE
Could not find filter(s): "fixed"

### ISSUE THREAD

**Issue by jswypozyczone** [liip/LiipImagineBundle#1227]
### Preconditions
PHP 7.3, Symfony 4

### Steps to reproduce
https://symfony.com/doc/2.0/bundles/LiipImagineBundle/filters/sizing.html#fixed-size

### Expected result
Filter sets:
```
width: 100
height: 100
```
original image 50x50 after use this filter will be 100x100 and original image 300x300 will be also 100x100

### Actual result
Could not find filter(s): "fixed"

**Comment by michellesanver** [comment]
Thanks @jswypozyczone for the detailed issue! I am looking at it right now.

**Comment by jswypozyczone** [comment]
> Thanks @jswypozyczone for the detailed issue! I am looking at it right now.

did You found sth? :(

**Comment by michellesanver** [comment]
Nothing yet. I’ll look some more soon! 💚

**Comment by franmomu** [comment]
The "fixed" filter was lost in 2.x branch, but it is now (next release) available again: https://github.com/liip/LiipImagineBundle/issues/1181

**Comment by michellesanver** [comment]
Thanks @franmomu. I will close this issue and consider it "fixed" (pun intended) :)
