### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

### ISSUE THREAD

**Issue by JohJohan** [liip/LiipImagineBundle#1234]
There is a deprecation From Symfony 4.2

### Steps to reproduce
1. Install Symfony 4.2
2. Install Liip bundle and setup config
3. See deprication logs: `A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.`

### Expected result
1. We could easy fix this deprecation so we dont see this log.

### Actual result
1. No deprecation log

**Comment by franmomu** [comment]
Hi @JohJohan, thanks for reporting this, which version of LiipImagineBundle are you using?  I cannot see any call to `new TreeBuilder` without argument in 2.2.0 version.

**Comment by JohJohan** [comment]
Hi @franmomu you are right! Thanks for the fix next time i will update before posting issue 👍
