### ISSUE TITLE
[RFC] Add extra properties to Async\ResolveCache command to forward to results message (or message headers)

### ISSUE THREAD

**Issue by florianajir** [liip/LiipImagineBundle#1237]
**Is your feature request related to a problem? Please describe.**
When we use this command `$producer->sendCommand(Commands::RESOLVE_CACHE, new ResolveCache($filename, ['filter'], $force))` we can't pass extra informations (like the source of the file: eg database table) to be able to process the resolved results the way we want.

**Describe the solution you'd like**
This could be achieve by adding an extra parameter to `ResolveCache` constructor which will be forwarded to the `CacheResolved` response event.

If you agree I can do a PR.

Best regards

**Comment by florianajir** [comment]
The ResolveCache message should also have customizable headers (e.g. for deduplication purpose)

**Comment by dbu** [comment]
we will deprecate the enqueue support in favor of symfony messenger, which is added in #1360

can you propose your idea for extra message metadata there? or actually, as ResolveCache is not created by this bundle but in your code, you could also extend the class to add custom information.

i am however not sure how a database table information could be forwarded to the resolver, as getUrlOfFilteredImage only accepts $path and $filter. so i think the table would need to be part of $path.
