### ISSUE TITLE
How to resolve all related images for a given filter

### ISSUE THREAD

**Issue by ahmed-bhs** [liip/LiipImagineBundle#1268]
If we remove  image alias for a given filter using this command bin/console liip:imagine:cache:remove --filter=x is there a way to restore them ?

Any help would be appreciated,

**Comment by robfrawley** [comment]
Inversely to the cache removal command you mentioned in your question, `loop:imagine:cache:remove`, there is a cache resolution command that performs cache image generation actions: `loop:imagine:cache:resolve`.
