### ISSUE TITLE
Graceful fail on resolve error (S3 storage)

### ISSUE THREAD

**Issue by plamenh** [liip/LiipImagineBundle#1271]
**Is your feature request related to a problem? Please describe.**
I get a complete fail when my S3 file is not resolved (e.g. 503 error by S3)

**Describe the solution you'd like**
Graceful fail (e.g., resolve a placeholder image or don't resolve without bringing the whole app down)

**Describe alternatives you've considered**
Dumping S3 completely. Not a real alternative.

**Additional context**
`{% set imageUrl = photoUri | imagine_filter('infoImage2x') %}`

> An Error Occurred! Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Error executing "HeadObject" on "https://s3.xxx.com/infoImage2x/res/images/photos/trades/yyy.jpg"; AWS HTTP error: Server error: `HEAD https:///s3.xxx.com/infoImage2x/res/images/photos/trades/yyy.jpg` resulted in a `503 Service Unavailable` response (server): 503 Service Unavailable - ")." at /home/.../templates/zzz.html.twig line 41

**Comment by plamenh** [comment]
Any ideas? 503 errors crash whole pages with current behavior.

**Comment by plamenh** [comment]
Anyone? S3 type of storage is widely used and 503 slowdown errors are not a rare occurrence.

**Comment by notFloran** [comment]
To bypass that, I decorate the twig extension:

ImagineFilterExtension.php
```php
<?php

namespace App\Twig;

use Aws\S3\Exception\S3Exception;
use Liip\ImagineBundle\Templating\FilterExtension;

final class ImagineFilterExtension extends FilterExtension
{
    public function filter($path, $filter, array $config = [], $resolver = null)
    {
        try {
            return parent::filter($path, $filter, $config, $resolver);
        } catch (S3Exception $exception) {
            return '';
        }
    }
}
```

services.yaml:
```yaml
    App\Twig\ImagineFilterExtension:
        decorates: 'liip_imagine.templating.filter_extension'
```

**Comment by plamenh** [comment]
Thanks, @notFloran, will implement this.
