### ISSUE TITLE
Symfony 5.1 Class 'Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser' not found

### ISSUE THREAD

**Issue by thomas2411** [liip/LiipImagineBundle#1283]
Is there a plan to prepare bundle for Symfony 5.1 in the near future? When upgraded project I get:

`Class 'Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser' not found` while using /media/cache/resolve/ (thumbnail filter in this particular case)
Thank you,
Tom

**Comment by nidzho** [comment]
`composer require symfony/mime` fixed it for me

**Comment by thomas2411** [comment]
It did, thank you :)
