### ISSUE TITLE
Class 'Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser' not found

### ISSUE THREAD

**Issue by gyulaafodorr** [liip/LiipImagineBundle#1285]
With Symfony 5.1 LiipImagineBundle 2.3 I have this error:
Class 'Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser' not found

### Preconditions

1. Symfony 5.1 
2. LiipImagineBundle 2.3, GD

### Steps to reproduce

1. I see the missing files in here:
vendor/liip/imagine-bundle/Resources/config/imagine.xml
...
<service id="liip_imagine.mime_type_guesser" class="Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface">
            <factory class="Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser" method="getInstance" />
        </service>

        <service id="liip_imagine.extension_guesser" class="Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesserInterface">
            <factory class="Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser" method="getInstance" />
        </service>
...

Has anyone tried the bundle with Symfony 5?

**Comment by tbredillet** [comment]
Same issue with Symfony 4.4

**Comment by tbredillet** [comment]
`composer require symfony/mime`

Fixed it for me

**Comment by gyulaafodorr** [comment]
Yep, that fixed it for me as well, thanks very much @tbredillet
