### ISSUE TITLE
Add support for AsyncAws

### ISSUE THREAD

**Issue by Nyholm** [liip/LiipImagineBundle#1294]
**Is your feature request related to a problem? Please describe.**

Im running Sylius on AWS Lambda. There is a limit how large my application can be. I would really really like to remove the 20Mb large AWS SDK from my application. 

**Describe the solution you'd like**
I propose adding support for AsyncAws as addition to the official AWS SDK. 

**Describe alternatives you've considered**
I've considered using flysystem, But then I need to install the one-up bundle and flysystem. It works, but it is still a few abstractions away. 

**Additional context**
Im happy to provide a PR.

**Comment by dbu** [comment]
i am going through old issues in this repository. do you still want to contribute this? how much code is there to support AsyncAws? if it is significant, could this be a separate repository? if it is just one small adapter class, i am fine having it in this repository, if you still want to contribute it.

**Comment by Nyholm** [comment]
Thank you. 

The size of the implementation would be exactly as the official AWS SDK. 
One can use Async AWS by using Flysystem 1 and 2. 

I dont have time to contribute in the next few months. I also think I solved my problem by using Flysystem. 

Feel free to close this if you want to clean up old issues.

**Comment by dbu** [comment]
yeah going through flysystem sounds like the right way. thanks for the quick answer :+1:
