### ISSUE TITLE
JpegOptimPostProcessor quality

### ISSUE THREAD

**Issue by ant46** [liip/LiipImagineBundle#1310]
You cannot set the quality through the _liip_imagine.jpegoptim.max_ parameter
Instead, you have to specify via the option

### Steps to reproduce
Method **getProcessArguments()**

### Expected result
```php
if ($quality = $options['quality'] ?? $this->quality) {
    if (!in_array($quality, range(0, 100), true)) {
        throw new InvalidOptionException('the "quality" option must be an int between 0 and 100', $options);
    }

    $arguments[] = sprintf('--max=%d', $quality);
}
```

### Actual result
![изображение](https://user-images.githubusercontent.com/68695041/101455767-1eaac700-3944-11eb-986d-d758bce036fc.png)

**Comment by lsmith77** [comment]
fixed in https://github.com/liip/LiipImagineBundle/releases/tag/2.6.1
