### ISSUE TITLE
Bad image quality

### ISSUE THREAD

**Issue by AxelBriche** [liip/LiipImagineBundle#1312]
I use "quality : 100" with imagick and the image quality is realy bad :

![1](https://user-images.githubusercontent.com/1295251/101957350-90fbff80-3c01-11eb-9cd0-6d0eeb2fc188.jpg)
Source:

![here-are-all-the-ways-you-can-customize-your-character-in-cyberpunk-2077](https://user-images.githubusercontent.com/1295251/101957378-9a856780-3c01-11eb-9a8e-3d77a2ee7723.jpg)

**Comment by fbourigault** [comment]
Is it possible you show us your whole `liip_imagine` configuration?
