### ISSUE TITLE
[RFC] Switch to GitHub Actions

### ISSUE THREAD

**Issue by fbourigault** [liip/LiipImagineBundle#1318]
While working on fixing the build, I found differences between my computer and travis-ci.com.

After some research, I discovered that WebP tests are not run on travis-ci.com because GD isn't built with WebP support.

I quickly setup a GitHub action to reproduce the build failure: https://github.com/fbourigault/LiipImagineBundle/runs/1566977959?check_suite_focus=true

I learned through @lsmith77 on twitter that travis-ci.com is no longer friendly with open-source, so I guess switching to GitHub Actions for LiipImagineBundle could be a thing.

I volunteer to handle this task.

**Comment by dbu** [comment]
i agree with moving to github actions. thanks a lot for volunteering!
