### ISSUE TITLE
Webp - Your PHP version is compiled without WebP support.

### ISSUE THREAD

**Issue by maraism** [liip/LiipImagineBundle#1322]
Hi, 

I think there is an error in Liip\ImagineBundle\DependencyInjection\Configuration.php for webp.
We need to replace : 
`->ifTrue(function ($v) {
                                    return !$v || function_exists('imagewebp');
                                })`
by 

`->ifTrue(function ($v) {
                                    return $v && !function_exists('imagewebp');
                                })`

Thank's !

**Comment by lsmith77** [comment]
thank you for the PR.

I am holding off from merging as I first want to look into https://github.com/liip/LiipImagineBundle/issues/1319 .. maybe you also can have a look as it relates to the just released WebP support.

**Comment by peter-gribanov** [comment]
This code breaks logic and will result in fatal error.

```php
->ifTrue(function ($v) { return $v && !function_exists('imagewebp'); })
```

You enable WebP generation even though your PHP version does not support WebP generation.

**Comment by beardedev** [comment]
The solution offered by @maraism work great for older version of bundle (in my case 2.1) 👏
Consider upgrading to 2.10 ti fix this issue.
