### ISSUE TITLE
Release with PHP 8 support

### ISSUE THREAD

**Issue by pamil** [liip/LiipImagineBundle#1354]
Is there anything I could help with to push forward the release with PHP 8 support? It's already merged to the `2.x` branch, only missing a tag to be usable by other libraries.

**Comment by douglasjam** [comment]
Looking forward as well

**Comment by garak** [comment]
By the way, it looks like [milestones](https://github.com/liip/LiipImagineBundle/milestones) need to be re-organized

**Comment by lsmith77** [comment]
its coming https://twitter.com/lsmith/status/1359147344818819080?s=20

**Comment by lsmith77** [comment]
https://github.com/liip/LiipImagineBundle/releases/tag/2.5.0

**Comment by garak** [comment]
It looks like UPGRADE.md has been left behind

**Comment by lsmith77** [comment]
oopps .. yeah looks like this has been forgotten for the past 3 releases now :-/
