### ISSUE TITLE
Resample filter bug

### ISSUE THREAD

**Issue by bpradines** [liip/LiipImagineBundle#1358]
### Preconditions
Symfony 5.2 installed with Composer
liip/imagine-bundle v2.4.0 driver : gd
imagine/imagine v1.2.4

### Steps to reproduce
1. Create a 300 dpi jpeg image (.jpg)
2. If I don't use the resample filter, any filter saves the image in 96 dpi. So, create a custom filter set including the resample filter : 
`
my_result:
            quality: 100
            filters :
                crop:
                    
                    # set the size of the cropping area
                    size: [ 300, 600 ]

                    # set the starting coordinates of the crop
                    start: [ 040, 160 ]

                # use and setup the "resample" filter
                resample:

                    # set the unit to use for pixel density
                    unit: ppi

                    # set the horizontal pixel density
                    x: 300

                    # set the vertical pixel density
                    y: 300`
3. Apply the filter set to the jpeg image. Exceptions occure : 

### Expected result
1. The jpeg image should be saved with 300 dpi resolution.

### Actual result
two exceptions :
1. Exception in ResampleFilterLoader.php (LiipImagineBundle)
`
Liip\ImagineBundle\Exception\Imagine\Filter\ LoadFilterException
in D:\wamp64\www\aligne_images\vendor\liip\imagine-bundle\Imagine\Filter\Loader\ResampleFilterLoader.php (line 56) 
...
throw new LoadFilterException('Unable to save/open file in resample filter loader.', null, $exception);
...
`

2. Exception in Image.php (Imagine)
`
Imagine\Exception\ InvalidArgumentException

Saving image in "tmp" format is not supported, please use one of the following extensions: "bmp", "gif", "jpeg", "png", "wbmp", "webp", "xbm"
in D:\wamp64\www\aligne_images\vendor\imagine\imagine\src\Gd\Image.php (line 602)
`

![Exception 1](https://user-images.githubusercontent.com/79471095/108746570-cc3d7780-753c-11eb-9af6-28609d5bb600.jpg)
![Exception 2](https://user-images.githubusercontent.com/79471095/108746586-d19ac200-753c-11eb-8bc6-17076c22ac7b.jpg)

**Comment by bpradines** [comment]
I made a mistake.
The Exceptions were due to a bad expression in liip_imagine.yaml :

driver: "gd" instead of driver: gd

and the resampling doesn't work with gd - if I use :

driver: imagick

It works, even without resample : the 300 dpi resolution of my image is kept during filtering.
But I have to install Image Magick, and its PHP extension ...

**Comment by BurningDog** [comment]
I've found the same - resampling doesn't work with `gd` but does with `imagick`. This should be mentioned in the docs, but for some reason `resample` no longer shows up in the [General Filters documentation](https://symfony.com/bundles/LiipImagineBundle/current/filters/general.html)

**Comment by dbu** [comment]
after a bit of confusion, i realized why the resample doc disappeared: it has only been added to the 1.x branch and that branch has not been merged to 2.x afterwards anymore.

fixing that in https://github.com/liip/LiipImagineBundle/pull/1541

glad if you want to do a pull request (to the 2.x branch) to add a note about it.
