### ISSUE TITLE
Private property $webpGenerate in CacheManager

### ISSUE THREAD

**Issue by loicsapone** [liip/LiipImagineBundle#1366]
Hi :hand:,

First of all, thank you for this bundle and for your work!

I have a question concerning a recent PR: #1333 

In one of my projects, I need to override `CacheManager::getBrowserPath()` method.
But I can't access `$webpGenerate` property since it's private.

Is there a reason why this property is private while all the others are protected?
Do you think it would be a problem to make it protected?

Thanks for your time!

**Comment by peter-gribanov** [comment]
You can get the value of property `CacheManager::$webpGenerate` from parameter `%liip_imagine.webp.generate%`.
