### ISSUE TITLE
CacheResolver relies on to-be-retired doctrine/cache

### ISSUE THREAD

**Issue by mbabker** [liip/LiipImagineBundle#1368]
The `Liip\ImagineBundle\Imagine\Cache\Resolver\CacheResolver` class requires a `Doctrine\Common\Cache\Cache` implementation for its caching layer to work.  The `doctrine/cache` package is in the process of being sunsetted (see https://github.com/doctrine/cache/issues/354 for more details).

A new cache resolver supporting another caching implementation will soon be necessary to replace the Doctrine package.  Presumably, a `PsrCacheResolver` could be the replacement (to avoid a hard coupling to `symfony/cache`, which is a PSR-6 and PSR-16 provider).

**Comment by dbu** [comment]
see #1375
