### ISSUE TITLE
Unable to open image when PDF file

### ISSUE THREAD

**Issue by lulu59299** [liip/LiipImagineBundle#1369]
Hello,

I use Symfony 5, vich uplaoder and LiipImagine.
Only the jpg / png files get filtered. 
In the log file I get an "exception : object" for all the .pdf or .PDF files. The exception is "Unable to create image for path .... and filter.... ". The message is "Unable to open image .......".

The issue is really linked to PDF files, all other file types get filtered.

Has anyone encountered this before ?

**Comment by dbu** [comment]
are you sure that the image library you are using has support for handling pdf as images?

afaik LiipImagineBundle just tries to use the configured library to open the file and does not check what it is - we rely on the image library to tell if it works or not.
