### ISSUE TITLE
Webp bug

### ISSUE THREAD

**Issue by ehibes** [liip/LiipImagineBundle#1374]
### Preconditions

1. GD v 2.3
2. php 7.4

### Steps to reproduce

1. I configured liip for webp support adding next configuration :
```
liip_imagine:
    controller:
        redirect_response_code: 302
    default_filter_set_settings:
        format: webp
    webp:
        generate:    true
```

### Problem
1. In safari I should see an jpg image : the resolver redirect well to jpg format but even if the file extension is jpg, imaginebundle generate webp image. If I open the same URL (with jpg) in chrome, I see the image.

**Comment by rsereir** [comment]
Hello, i have the same issue.. when i add "/resolve" suffixe after "/cache/" the redirection to webp it's working, but when i use liip service to resolve url, i have jpg.. 

If someone have any idea..

**Comment by weyandch** [comment]
Got the same behaviour with IE11, the resolved images got the .jpg extension, but IE11 can't open 'em. 
I have created 2 filters, one which delivers webp, the other one regular jpg. When calling the webp-filter with IE11, it's getting the jpg-cloaked webp which can't be opened. 

`
liip_imagine:

    controller:
        redirect_response_code: 302
    webp:
        generate: true

    filter_sets:
        avatar_vp:
            format: webp
            post_processors:
                jpegoptim: { strip_all: true, max: 80, progressive: true }
            filters:
                resize: { size: [185, 185] }

        avatar:
            quality: 90
            filters:
                resize: { size: [185, 185] }
            post_processors:
                jpegoptim: { strip_all: true, max: 80, progressive: true }`

**Comment by xf-** [comment]
@weyandch IE11 has no webp support and is EOL by the vendor Microsoft.

**Comment by ehibes** [comment]
@xf- So the controller should return a jpg image. It returns a file with "jpg" extension, but it's a webp image. Here is the problem.

**Comment by peter-gribanov** [comment]
@ehibes the problem is that you specified in the settings that you want to **always** receive pictures **only** in WebP format. Reead the [docs](https://symfony.com/doc/2.x/bundles/LiipImagineBundle/configuration.html).

```yaml
liip_imagine:
    controller:
        redirect_response_code: 302
    default_filter_set_settings:
        format: webp # always use WebP format and never different formats
    webp:
        generate: true
```

I would recommend that you use the WebP format only in those browsers that support it.

```diff
liip_imagine:
    controller:
        redirect_response_code: 302
-    default_filter_set_settings:
-        format: webp
    webp:
        generate: true
```

Or ignore old browsers and always use images in WebP format.

```diff
liip_imagine:
    controller:
        redirect_response_code: 302
    default_filter_set_settings:
        format: webp
-    webp:
-        generate: true
```

Read [docs](https://symfony.com/doc/2.x/bundles/LiipImagineBundle/basic-usage.html#webp-image-format) for more details.

**Comment by weyandch** [comment]
@xf- sure its EOL, but still got 1.5% visitors with this version... 

@peter-gribanov  thanks for clearing things up, i did the same mistake and had the default_filter_sttings with format: webp enabled, didn't realize its killing the "fallback support for legacy browsers".
