### ISSUE TITLE
Drop support for unmaintained Symfony versions?

### ISSUE THREAD

**Issue by dmaicher** [liip/LiipImagineBundle#1378]
What is the plan for dropping support for Symfony 3.4, 4.3 and 5.0 + 5.1? Those are [EOL](https://symfony.com/releases)

Means we could get rid of some BC layers like

https://github.com/liip/LiipImagineBundle/blob/00f3ccfccb33834b44f82c17cca80bfd83882bb3/DependencyInjection/Configuration.php#L50
https://github.com/liip/LiipImagineBundle/blob/00f3ccfccb33834b44f82c17cca80bfd83882bb3/Imagine/Cache/CacheManager.php#L288
https://github.com/liip/LiipImagineBundle/blob/00f3ccfccb33834b44f82c17cca80bfd83882bb3/Events/CacheResolveEvent.php#L19

and probably some more.

Shall we do it? I can contribute on this

**Comment by Chris53897** [comment]
Meanwhile Symfony 5.2 has EOL.
Any news about this? I suggest to bump Php version to at least 7.2

**Comment by dbu** [comment]
i now picked up on the backlog of merge requests on this bundle...

my idea would be:

* step 1: merge as many of the things as possible, then tag a new minor version with the current set of supported symfony and php versions
* step 2: drop EOL symfony and PHP versions and cleanup legacy support thing we no longer need, then do another minor version

**Comment by dbu** [comment]
FTR: the place where we drop things is a new major version. allows to clean things much easier.
