### ISSUE TITLE
Permission issue when creating directories with flysystem V2

### ISSUE THREAD

**Issue by laferte-tech** [liip/LiipImagineBundle#1388]
Hello,
Upgrading to flysystem V2 using  oneup/flysystem-bundle i have permission issue with directories created by Liip Imagine (to store cached images).
The result is an access denied when trying to access the cached files (i can still access the raw files, not processed by liip i mean).

My setup:
Docker with local flysystem and using Symfony 5.3 and nginx.
The problem is the same either if i store the files in a named volume and either if i store them on my local computer (using bind mount).

In my docker-entrypoint for PHP container, i have this:

```
	setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX public/uploads
	setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX public/uploads

```
**The problem:**

![liip](https://user-images.githubusercontent.com/62180528/132494089-d907cd32-d5f5-4684-9a31-858afd592b6c.png)

Using: `"oneup/flysystem-bundle": "4.*",` (flysystem v2)
Liip create directories with insufficient permissions (second line)

Using `"oneup/flysystem-bundle": "3.*",` (flysystem v1)
Liip create directories with enough permissions (first line of the print screen above).

This is really weird. If i create the directory using flysystem v1 and then switch to v2, it's also working because the directory already exists.
So for me the problem seems to come when Liip create directories to store the cached images.

Anyone has any clue about this?

Thanks a lot

**Comment by laferte-tech** [comment]
ok, not related to Liip but with Flysystem directly (not even 1up)

**Comment by iacovlevdev** [comment]
Hi! how did you solve the problem?

**Comment by laferte-tech** [comment]
Hello,
i'm so sorry i don't remember well but i think i didn't solve it and i moved to AWS S3 instead.
I had trouble with Flysystem v2 and local filesystem and docker so it was easier for me to move to S3 to solve it.
Sorry i can't help more :/

**Comment by yevhenii-myronov** [comment]
This is due to the permissions configuration in the adapter

[https://github.com/1up-lab/OneupFlysystemBundle/blob/main/doc/adapter_local.md](https://github.com/1up-lab/OneupFlysystemBundle/blob/main/doc/adapter_local.md)
