### ISSUE TITLE
remove deprecated code and documentation

### ISSUE THREAD

**Issue by dbu** [liip/LiipImagineBundle#1406]
to prepare for version 3, remove all deprecated code and the documentation about it.

hint: search repository for "deprecated"

**Comment by mbabker** [comment]
Could you add a `3.x` branch so folks could start working on these types of issues?  I assume with the new issues and 3.0 milestone, you're ready to start working on the new major version.

**Comment by dbu** [comment]
i created the 3.x branch now.

**Comment by stephanvierkant** [comment]
And look for 'BC'. Two examples I've found:

https://github.com/liip/LiipImagineBundle/blob/89e7563103ba82c5495f728f041d7135ee4bb5ff/src/Imagine/Cache/Resolver/ProxyResolver.php#L67

https://github.com/liip/LiipImagineBundle/blob/89e7563103ba82c5495f728f041d7135ee4bb5ff/src/Imagine/Cache/CacheManager.php#L218

And this BC is still required, please add some more details when to remove it.

**Comment by tacman** [comment]
I attempted to remove these for version 3, and indeed many tests failed.

Not sure how to proceed.

**Comment by dbu** [comment]
the only one i still find is in ProxyResolver. i did a bit of digging to see where this comes from, and its this pull request: https://github.com/liip/LiipImagineBundle/pull/687

in this instance, i think the "old" use case of just having a list of domains to randomly pick seems valid to me. the more i look at #687 the more i think we should even drop this in version 3 and just have a list of domains that are randomly picked. the replace functionality was never documented, so i think almost everyone is using just the base functionality, if they even use the proxy resolver at all.
