### ISSUE TITLE
The resolve controller adds ".webp" string to the redirecting url

### ISSUE THREAD

**Issue by maxkain** [liip/LiipImagineBundle#1411]
Version 2.7.0

"/media/cache/resolve/some_filter/uploads/image/1/60cef7ee60cac165469253.jpg" query redirects to "/media/cache/some_filter/uploads/image/1/60cef7ee60cac165469253.jpg.webp" even if webp generate option is false. And there is 404 error.

Maybe is needed to change FilterService resolveFilterPathContainer function from this:
```php
  if ($webpSupported) {
      $path = $filterPathContainer->createWebp($this->webpOptions)->getTarget();
  }
```

to this:

```php
  if ($this->webpGenerate && $webpSupported) {
      $path = $filterPathContainer->createWebp($this->webpOptions)->getTarget();
  }
```

**Comment by dbu** [comment]
yes, sorry about that. i merged the fix this morning #1410, but did not release a new version just yet because there is something more broken with webp support that i also try to fix.
