### ISSUE TITLE
Replace guzzle with symfony http client in 3.0

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1451]
**Is your feature request related to a problem? Please describe.**

Not really.  There's a deprecation error: Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Describe the solution you'd like**

I've found the Symfony HttpClient to be as good as Guzzle, and has fewer issues when trying to upgrade to newer Symfony versions.

**Comment by dbu** [comment]
this being a symfony bundle, this makes sense to me, yes. in framework-independant libraries i advocate for PSR-18, but this is a bundle that needs symfony anyways, so we can just use the client they provide.

do you want to work on that?

**Comment by tacman** [comment]
Yes, I'll give it a shot.

**Comment by tacman** [comment]
So it looks we're only using Guzzle in the tests, and even then, it's just to have access to an ObjectMock of type Model (which extends Guzzle\Collection).

So we can drop Guzzle altogether, once we have a replacement for the Mock Object.  Alas, this is something I don't have much experience in (but need to learn anyway).  Can you point me to a replacement?

The code in question is in AwsS3ResolverTest.


```php
    /**
     * @return MockObject&Model
     */
    protected function getS3ResponseMock()
    {
        return $this->createObjectMock(Model::class);
    }
```

**Comment by dbu** [comment]
oh, so actually it is the Aws library that is hard-tied to guzzle. however, i had a look at the AwsS3Resolver and we never use the return value that we mock in these places. i think we can get rid of that model (i think #1455 would have created problems if it was actually used as intended) and of having a mock response. 

lets completely remove the `willReturn` section for the deleteObject and putObject calls in the AwsS3ResolverTest. as long as AWS does not do strict typing, that shoud be good enough for the test.

**Comment by tacman** [comment]
I think the problem was in an autocomplete -- that is, Model::class used the Guzzle Model, not our Model.  That's how version 2 works, I'm trying that fix now.
