### ISSUE TITLE
Image link return 404 when i apply filter.

### ISSUE THREAD

**Issue by SimonChabrier** [liip/LiipImagineBundle#1462]
The liip cache directory are not created on install in the public directory. 
I follow the instructions given in symfony doc.
Befor apply filter image is display.
And when I apply filter the image link is broken. 

### Preconditions

1.  Bundle is version": "2.7.6",
2. Symfony 5.4
3. php 7.4.3
4. Gd enable in Php

### Steps to reproduce

1.  I have a repository here with the code : 
2. https://github.com/SimonChabrier/ImageUploader
3. Just a simple basic code with a form tu upload image and a view for rendering.

### Expected result

1.  I just want to apply a filter like this 
2. `<img src="{{ vich_uploader_asset(card, 'CardPictureFile')|imagine_filter('my_thumb_filter') }}" alt="{{ card.CardTitle }}" />`

### Actual result

1. `The requested resource /media/cache/resolve/my_thumb_filter/assets/images/upload/300x300-620a8bda54310.jpg was not found on this server.`
2. `[Mon Feb 14 18:26:55 2022] 127.0.0.1:44226 [404]: GET /media/cache/resolve/my_thumb_filter/assets/images/upload/300x300-620a8bda54310.jpg - No such file or directory`

**Comment by SimonChabrier** [comment]
I just can resolve image using console command :

`bin/console liip:imagine:cache:resolve rmyelative/path/to/myimage.jpg `

use the command create the directory in the project but I can't do better at time. I try all the config I find in documentation I really don't uderstand. Thanks for some help.

**Comment by SimonChabrier** [comment]
I find a solution using the symfony server it's works fine on 127.0.0.1:8000 But I don't understand why this doesn't work on 0.0.0.0:8080

**Comment by Akamein** [comment]
Hello, i have the same problem here, 

when i use my liip_imagine filter :

my_filter_small:
            cache: ~
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true

It returns me a 404 error because of the path not generated...

<a > href="http://localhost:8000/media/cache/resolve/my_filter_small/uploads/randomarts/image-620bc5925aad1160605463.jpg" download=""> 
<img src="http://localhost:8000/media/cache/resolve/my_filter_small/uploads/randomarts/image-620bc5925aad1160605463.jpg" alt="">
</a>

I'm still searching

**Comment by massidi** [comment]
i have the same problem

**Comment by SimonChabrier** [comment]
"[http://localhost:8000/] does't work. Try to use symfony CLI (install it firts if you don't have  : https://symfony.com/download ) and run : `symfony server:start`
