### ISSUE TITLE
Could not find configuration for a filter with config from documentation on Symfony 6

### ISSUE THREAD

**Issue by akincer** [liip/LiipImagineBundle#1465]
After installing the bundle and using the documentation example to create a my_thumbnail filter this error is thrown:

`An exception has been thrown during the rendering of a template ("Could not find configuration for a filter: my_thumb").`

### Preconditions
1. Bundle Version 2.7.6
2. PHP 8.0
3. GD version 8.0.8-1ubuntu0.3
4. Symfony 6.0.2

### Steps to reproduce
1. Setup Symfony 6.0.2 project
2. Install LiipImagineBundle 2.7.6
3. Configure app/config/config.yaml as the documentation suggests
4. Attempt to use the filter in a twig template as the documentation suggests

### Expected result
1. The target image should show as a thumbnail on the rendered template

### Actual result
1. The above error message

**Comment by owebboy** [comment]
Put your liip_imagine configuration `config/services.yaml`
