### ISSUE TITLE
How to use/access the FilterService in a Symfony 5 controller

### ISSUE THREAD

**Issue by cbeyer** [liip/LiipImagineBundle#1470]
Hi, this was good working with Symfony 4.4 :
`$this->filterService->filter($path, $filter)`

($this->filterService is set in the constructor of the controller, from `Liip\ImagineBundle\Templating\Helper\FilterHelper`)

After upgrading to Symfony 5.3, I got this error :

> Attempted to load class "Helper" from namespace "Symfony\Component\Templating\Helper".
Did you forget a "use" statement for e.g. "Symfony\Component\Console\Helper\Helper" or "Knp\Menu\Twig\Helper"?

Origin : `liip/imagine-bundle/Templating/Helper/FilterHelper.php`

How to fix this ?

Thanks!

**Comment by dbu** [comment]
are you sure that the templating component is installed? the error indicates that the class Symfony\Component\Templating\Helper\Helper does not exist... you can try if executing `composer require symfony/templating` fixes the issue.

note that symfony is moving away from the templating abstraction, and the filter helper is deprecated in favor of using twig templates (if your use case is to render the filter url without doing a template, the new class to inject would be LazyFilterRuntime - that class has the same methods as the FilterHelper, but does not have any dependencies on the templating layer.

**Comment by cbeyer** [comment]
Yes of course templating bundle is installed !

I found this workaround 

Old code :
```php
use Liip\ImagineBundle\Templating\Helper\FilterHelper;
$filterHelper->filter($path, 'small')
```

New code :
```php
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
$cacheManager->getBrowserPath($path, 'small')
```

It seems it does the work ;)

**Comment by dbu** [comment]
that seems the right way, its also what we recommend to do in the README: https://github.com/liip/LiipImagineBundle#resolve-programmatically
