### ISSUE TITLE
Clarify/Document Flysystem Bundle Dependency (oneup,thephpleague)

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1477]
According to the documentation (https://symfony.com/bundles/LiipImagineBundle/current/data-loader/flysystem.html), there's a soft dependency on https://github.com/1up-lab/OneupFlysystemBundle.  

> This cache resolver has a soft dependency on [OneupFlysystemBundle](https://github.com/1up-lab/OneupFlysystemBundle), which can be installed by executing the following command in your project directory:
> 
>       composer require oneup/flysystem-bundle

Will this bundle also work with Flysystem's Bundle (https://github.com/thephpleague/flysystem-bundle?

**Describe the solution you'd like**

I _think_ that this bundle will work with either flysystem bundle, and was hoping to see an example, and if that's true, see this reflected in the documentation.

**Comment by dbu** [comment]
thanks for bringing this up. indeed it should work just fine with the league bundle - all we care about is having a flysystem instance as a symfony service, and either bundle provides that. you could even define the flysystem service without a bundle if you would prefer (though the bundles provide a much nicer way to do that).

**Comment by dbu** [comment]
i updated the documentation to explain this.

**Comment by tacman** [comment]
Thanks.  By any chance, is there a simple symfony demo that shows implements this?  

I've updated Ryan's All About Uploads to Symfony 6 (https://github.com/tacman/uploads-finish), but am still fighting with the configuration.  A simple "upload a photo, then show it cropped and get the url from a cache so it doesn't have to hit aws s3".

**Comment by dbu** [comment]
the documentation is here: https://symfony.com/bundles/LiipImagineBundle/current/cache-resolvers.html 

i am not aware of a current demo application with the imagine bundle, sorry.

**Comment by tacman** [comment]
Can you update this page to reflect how to configure the bundle without
oneup?

https://symfony.com/bundles/LiipImagineBundle/current/data-loader/flysystem.html

**Comment by dbu** [comment]
symfony.com only pulls the changes a couple of times a day. it updated meanwhile.
