### ISSUE TITLE
Filter don't work inside of functional tests.

### ISSUE THREAD

**Issue by MichaelBrauner** [liip/LiipImagineBundle#1482]
I wrote a [Bundle](https://github.com/Braunstetter/media-bundle). 
The UI is tested with [Panther](https://github.com/symfony/panther) but it doesn't really matter, because the problem exists also when I use the default symfony KernelBrowser.

In my [TestMethod](https://github.com/Braunstetter/media-bundle/blob/main/tests/tests/Functional/Ui/FormTest.php#L60) I took a [screenshot](https://github.com/Braunstetter/media-bundle/blob/main/tests/tests/Functional/Ui/screenshots/max_items_option_hides_add_button.png) with panther and the 2 existing images are not resolved.

Like I said, also when I don't use panther for that - the path is getting not resolved (path points to the controller route and no cache is created).

As soon as I visit the [test-app](https://github.com/Braunstetter/media-bundle/tree/main/tests/app) via a browser all works just fine - images are getting resolved and cache is getting created.
It is testable by going into the `tests/app/` of the cloned bundle and start a symfony webserver (`symfony serve -d`) than browsing to `127.0.0.1:8000/test-two-existing-images`. 

It's not that my functional tests are broken (I don't test the LiipImagineBundle - filter). 
But it would be nice to make this work, so that the images inside the screenshots are not broken anymore.  

### Steps to reproduce

1. Clone the [MediaBundle](https://github.com/Braunstetter/media-bundle/tree/main/tests/app) `git clone git@github.com:Braunstetter/media-bundle.git`
2. `cd media-bundle`
3. Run tests: 
`composer install`
`./vendor/phpunit/phpunit/phpunit --filter "/(Braunstetter\\MediaBundle\\Tests\\Functional\\Ui\\FormTest::test_max_items_option_hides_add_button)`

### Expected result

The [screenshot](https://github.com/Braunstetter/media-bundle/blob/main/tests/tests/Functional/Ui/screenshots/max_items_option_hides_add_button.png) should not be broken anymore.

### Actual result
The [screenshot](https://github.com/Braunstetter/media-bundle/blob/main/tests/tests/Functional/Ui/screenshots/max_items_option_hides_add_button.png) is broken.

**Comment by dbu** [comment]
hi, as it works in the browser, i suspect that there is a problem with the way the page is requested by panther. but i agree it would be nice if it would work - who knows if some other clients also do the same difference and run into problems. the first image request will always lead to a redirection, is maybe the problem that the testing client does not want to follow the redirection?

can you somehow find the response it gets instead of an image, to see if there is an error message? does the symfony application log contain any hints what happens? maybe the paths between where the files are created on the filesystem vs the web root are not set up correctly in the test env? (i think to exactly compare, you'd need to `symfony serve` with the test environment, i guess by default it takes dev)

**Comment by MichaelBrauner** [comment]
Thank you for your answer. 

> first image request will always lead to a redirection, is maybe the problem that the testing client does not want to follow the redirection?

Hm. The problem also occurs in normal symfony functional test (I see it because no image is added to the cache) and also it happens with the panther client. In panther redirects are [always followed](https://github.com/symfony/panther/blob/main/src/Client.php#L317). That can also be not the problem. 

> can you somehow find the response it gets instead of an image, to see if there is an error message? 

I don't know if this is possible. I did not find anything about it. I believe it's only possible to see the Response of the main request. But I can dig a little bit more into that.

The path's are exactly the same. Only browsing method and the domain differs. With `symfony serve -d` it's:

`https://127.0.0.1:8000/media/cache/resolve/form_preview/tests/images/ice-62ebba2017828.jpg`

And inside of the tests:

`http://localhost/media/cache/resolve/form_preview/tests/images/ice-62ebba2017828.jpg` 

Something weird is happening here.

**Comment by dbu** [comment]
can you try to make symfony serve run with the symfony `test` env? then maybe you can reprobude the problem?

do you see anything in the var/log/* that gives an indication of a problem?

**Comment by MichaelBrauner** [comment]
> can you try to make symfony serve run with the symfony test env? then maybe you can reprobude the problem?

It runs everytime in test environment. [Here](https://github.com/Braunstetter/media-bundle/blob/main/tests/app/src/MediaBundleKernel.php#L17) it is hardcoded inside the `MediaBundleKernel`.

And when I browse the test with `symfony serve` all works fine. I see the images and it works all perfect. 
The problem only occurs when the test clients hit the controller action. 

> do you see anything in the var/log/* that gives an indication of a problem?

`var/log` is completely empty.

**Comment by dbu** [comment]
weird. you could try to use step-by-step debugging or hack some more logging into the liip imagine code locally to see what is going on. i would still guess something is different in the server configuration between requests from the browser and the test client. 

i guess `Accept` or `Accept-Language` header should not be the cause? or that the test client does not support the image format that you are using?

**Comment by MichaelBrauner** [comment]
I've let that go for now. If someone has the same problem again, we can open it again.
