### ISSUE TITLE
Document which version of Flysystem to use

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1483]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the visibility constants, but I must have the wrong version installed.  Even just downloading the bundle has use statements that don't resolve.

**Describe the solution you'd like**

When I clone and install the bundle (2.x), these classes don't exist.

```
# Liip\ImagineBundle\Imagine\Cache\Resolver\FlysystemResolver
use League\Flysystem\AdapterInterface;
use League\Flysystem\FilesystemInterface;
```

The AdapterInterface constants are referenced here:

https://symfony.com/bundles/LiipImagineBundle/current/cache-resolver/flysystem.html

I'm guessing these constants moved with versions 2/3, but I'm struggling to just get a basic configuration working.

**Comment by dbu** [comment]
yeah the constants moved in version 2. as the doc says, you can also use the strings `public` or `private` instead of using constants. but the new place is the `Visibility` class. (the symfony website will take a while to update)
