### ISSUE TITLE
Deprecated $defaultName property in commands

### ISSUE THREAD

**Issue by garak** [liip/LiipImagineBundle#1488]
The `$defaultName` property in commands has been [deprecated](https://github.com/symfony/symfony/commit/ca3458c8781eafd9ff40bac50a254334e526dc10) in Symfony 6.1

Commands in Symfony 6 should use the `AsCommand` attribute instead.
A possible workaround to keep compatibility with older PHP versions is using the `getDefaultName` method instead.

**Comment by dbu** [comment]
yeah, i think to use the attribute we would have to drop php 7 support and also some of the older symfony versions. symfony 7 is still about 1 year in the future, we can either ignore it until we need to do something for symfony 7 support and then drop old versions, or go with the getDefaultName for now and then change again later. i would tend to ignore for now, its a deprecation but not creating any problems.

but if you want to do a pull request to change it, i can review and merge it.

**Comment by garak** [comment]
Sorry, I just realized that this was already fixed in #1472
I guess that at this point we only need a new release... I see that the last one was last May, maybe it could be a good time?

**Comment by dbu** [comment]
right, thanks for the reminder: https://github.com/liip/LiipImagineBundle/releases/tag/2.9.0
