### ISSUE TITLE
symfony 6 install???

### ISSUE THREAD

**Issue by CodingBDX** [liip/LiipImagineBundle#1498]
it's work on symfony 6 because i don't understand the installation??

composer require liip/imagine-bundle =>ok

app.kernel where???

and after symfony 5 okey...
 Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true]

that already inside my file
i put in my route.yaml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

ok and after
in my liip.yaml
i write
`filter_sets:
        article:
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
                watermark_image:
                # chemin vers le fichier
                    image: ../public/assets/img/watermark.png
                # Taille relative de l'image
                    size: 0.1
                # set the position of the watermark
                    position: bottomright
`

and the filter in my twig
{{ asset('uploads/images/posters/'~image.name)|imagine_filter('article') }}

but nothin to happen, please someone help me

**Comment by dbu** [comment]
symfony 6 uses config/bundles.php to load bundles, see https://symfony.com/doc/current/bundles.html

**Comment by CodingBDX** [comment]
Okey,so you sée m'y code,where it's thé problèm?

**Comment by dbu** [comment]
it is hard to read and understand what you wrote because of the formatting, but i don't see anything obviously wrong. so the bundle is loaded and you get an image path but the filter is not applied when you fetch the image? or do you get some sort of error?

**Comment by CodingBDX** [comment]
yes of course, nothing show but if i click on the link into my console

http://0.0.0.0:9900/media/cache/resolve/article/uploads/images/posters/54f8760ec1d98d2bb59a2a206bba6007.jpg

`Unable to create image for path "uploads/images/posters/54f8760ec1d98d2bb59a2a206bba6007.jpg" and filter "article". Message was "Unable to open image /var/www/html/heypapi/public/uploads/images/posters/54f8760ec1d98d2bb59a2a206bba6007.jpg"`

and i don't understand media/cache/resolve/article

because the correct path are
http://0.0.0.0:9900/uploads/images/posters/54f8760ec1d98d2bb59a2a206bba6007.jpg

**Comment by dbu** [comment]
the media/cache/resolve/article would be the route for the controller to trigger applying the filter that generates the image you want. but the error message says that it can't load the image from a path. you should debug why it can't open that image, if the root path is correct or if there are filesystem permission issues.

**Comment by CodingBDX** [comment]
okey i see, i don't install php-gd, it's work but on certain images...
it's work on 1920x865 167ko
but not on 1280x1280 330ko the image not in cache, and don't show...
[https://zupimages.net/up/23/04/b45g.png](url)

**Comment by dbu** [comment]
maybe your memory settings are too low?

another option to avoid having to set up image handling is using a service like [rokka.io](https://rokka.io/) where you can use an api and get a cdn with the images, and all image drivers installed and maintained as a service.

**Comment by CodingBDX** [comment]
i don't know, i see lot of peoples have same issue, i think my file liip.yaml are not correct there

`liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "uploads/images/posters"
`

all my images are in public/uploads/images/posters...it's good?? i use gd

**Comment by CodingBDX** [comment]
okey i find issu, it's gd...not work on jpg...i use now imagick that work perflectly!!

i have other problem, i would like use gallery on it...like flexbox or photoswiper

**Comment by dbu** [comment]
good, glad you solved it.

for gallery functions, you need to look into frontend tools. the imagine bundle is only about scaling single images and does not provide functionalities for managing the images.
