### ISSUE TITLE
WEBP converted picture  almost 3 times bigger than JPG on desktop view

### ISSUE THREAD

**Issue by ajaysSymfonyExpert** [liip/LiipImagineBundle#1501]
Hello there,  we are having an issue to maintain weight of WEBP converted picture.
Ex .  Original picture (6000x4000)  1.75 MB converted into jpg 1920x610 just 191KB.
BUT WEBP image created with 428kb (1920X610). its almost  thrice the size of JPG.
is there any way to decrease the size of converted WEBP format?
I tried to get help on this subject on [sylius channel](https://sylius-devs.slack.com/archives/C3EGDG9LY/p1675170461472629) as per suggestion changing quality  90 to 70 but still same result .
kindly guide me on this subject .
here is the my configuration:

`liip_imagine:
    webp:
        generate: true

              
    filter_sets:
       
        product_desktop_view:
            format: webp
            quality: 90
            filters:
                thumbnail:
                    size: [1920, 610]
                    mode: outbound   `

[7b7493ccdae9b8c6d3bea6949c4d.jpg.zip](https://github.com/liip/LiipImagineBundle/files/10579519/7b7493ccdae9b8c6d3bea6949c4d.jpg.zip)

**Comment by dbu** [comment]
this bundle is not doing any image conversions on its own. your best chance is to ask at the actual image library that you use (gd or imagick). 

i think with https://rokka.io/ we also have logic to check if webp actually is better than jpg and discard webp if it does not pan out. maybe @chregu has some input on that. (but this is only as inspiration for you to add on top of it, such logic would be out of scope for the liip imagine bundle)

**Comment by chregu** [comment]
WebP images should never be 3x bigger with equal quality settings. There's something seriously wrong somewhere. Maybe it tries to store them as "lossless"? Or something like that.

(at rokka, we actually don't check webp vs jpeg, because webp is never much bigger than jpeg. And in almost all cases smaller, so it's not worth the effort, we do that for avif vs webp, though)

**Comment by dbu** [comment]
@ajaysSymfonyExpert i close this issue as the problem seems to be with the image converter and not the symfony bundle. but feel free to comment if you found the issue, for future reference if others run into a similar problem.

**Comment by remikel** [comment]
@ajaysSymfonyExpert 
I had the same problem, the size was always bigger in webp than jpeg.
It appeared that the quality in the filter is not taken into account for the webp.
I don't know how to configure this for one filter but you can configure it globally like :
```
liip_imagine:
    driver: "gd"
    default_filter_set_settings:
        format: webp
    webp:
        generate:    true
        quality:     80
```
It will be the exact same size as jpeg for the same quality so I don't know if it worth it except avoiding google lighthouse saying "hey try webp it's better".
