### ISSUE TITLE
production public_html not work

### ISSUE THREAD

**Issue by CodingBDX** [liip/LiipImagineBundle#1505]
i have symfony 6 with docker;

that work fine in dev but when i try to deploy in other computer (raspberry), all works stripe service,tailwind,webpack,etc..

but liip image not work, i have install imagick on docker container inside raspberry but my images not appear...

the differents between my computer and server raspberry, it's the directory, in my computer it's public and on raspberry it's public_html..
that my config file
`# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    twig:
        mode: lazy
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "assets/uploads"`

and the error it's 404 not found, but the files existe, the url not  work
http://192.168.1.19/assets/uploads/profile/assets/uploads/f9ab2a5549d064c410266c3a7ce79ed4.png

**Comment by dbu** [comment]
the issue tracker is to report bugs of the LiipImagineBundle. if i understand correctly, you have a configuration problem with paths in your docker images and your deployment.

please ask for help in [symfony slack](https://symfony.com/slack) or [stackoverflow](https://symfony.com/blog/symfony-on-stackoverflow)
