### ISSUE TITLE
Deprecation in ImageType

### ISSUE THREAD

**Issue by garak** [liip/LiipImagineBundle#1517]
I know there's already an effort in progress to remove all deprecated code, but I see it targets the next major version (version 3).
The following problem can be addressed in version 2 without affecting BC, it's a simpler one:

>Method "Symfony\Component\Form\AbstractType::configureOptions()" might add "void" as a native return type declaration in the future. Do the same in child class "Liip\ImagineBundle\Form\Type\ImageType" now to avoid errors or add an explicit @return annotation to suppress this message.

Just add the needed return type to the class methods.

**Comment by dbu** [comment]
fixed in #1518

**Comment by cbeyer** [comment]
Is it possible to have a stable tag/release with this correction ? (I'm using tag 2.11)

**Comment by dbu** [comment]
oh indeed. created that now https://github.com/liip/LiipImagineBundle/releases/tag/2.12.0
