### ISSUE TITLE
JFIF files not converting

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1520]
### Preconditions

I have download some jpeg files that are compressed with JFIF.   Liip appears to not convert them on my production machine, but works okay locally.

Is there some specific library that needs to be install for jfif files?

I've tried with both 'gd' and 'vips', but I'm getting an error.

It's possible that the error is someone else, like permissions (I love docker, except when I hate it).   Flysystem is complaining that it can't get the mime type, and that could be for permissions (except that it appears to be there and readable) or that the library for getting the mime of a JFIF-compressed jpeg isn't loaded.

Any suggestions?

Thanks.

**Comment by dbu** [comment]
LiipImagineBundle only integrates the Imagine PHP library into symfony, and Imagine mostly leverages the imagick or gd libraries. i would bet that the gd library on your production machine is built differently and therefore does not support the compression. even more so if it works locally - that means it is not some missing flag that should be sent to gd but simply gd not supporting it.

i would look into how gd is installed.

**Comment by tacman** [comment]
Indeed, GD was installed, but without jpeg support.  Here's a quick way to see that;

```bash
php -r "echo sprintf(\"JPEG SUPPORT? %s\n\", gd_info()['JPEG Support'] ? 'yes': 'no')  ;"
```
