### ISSUE TITLE
Support for JsonManifestVersionStrategy

### ISSUE THREAD

**Issue by wouterSkepp** [liip/LiipImagineBundle#1524]
**Is your feature request related to a problem? Please describe.**
Our projects use the `Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy`, which get populated by our build system (Webpack Encore, in this instance). Each file gets its own versioning string. The bundle does support `StaticVersionStrategy` but, to my knowledge only handles a single versioning string for all assets. It does not support the use of wildcards either.

**Describe the solution you'd like**
Add support for `JsonManifestVersionStrategy`

**Comment by dbu** [comment]
thank you for the contribution: https://github.com/liip/LiipImagineBundle/releases/tag/2.13.0
