### ISSUE TITLE
Call to undefined method Symfony\Config\LiipImagine\ResolversConfig::webPath()

### ISSUE THREAD

**Issue by stephanvierkant** [liip/LiipImagineBundle#1533]
### Preconditions

1. Bundle version 2.12.0
2.  Symfony 6.3.5

### Steps to reproduce

1. Use PHP configuration:

```
return static function (LiipImagineConfig $config, ContainerConfigurator $containerConfigurator) : void {
    $config->twig()->mode('lazy');

    $config->resolvers('default')
        ->webPath()
        ->webRoot('%kernel.project_dir%/public')
        ->cachePrefix('media/cache')
    ;
    // ...
});
```
2. Run `bin/console cache:clear`

### Actual result

> Uncaught Error: Call to undefined method Symfony\Config\LiipImagine\ResolversConfig::webPath()

I'm not sure if this is an issue with this bundle or a Symfony bug so I'm wondering if more people have this issue. See https://github.com/symfony/symfony/issues/50713 for a similar issue.

**Comment by dbu** [comment]
did you ever find out what happens here? is it a symfony bug or something we should fix in the imagine bundle?

**Comment by stephanvierkant** [comment]
Still no idea, but it isn't related to this bundle. So this issue can be closed.
