### ISSUE TITLE
Attempted to load class "AmazonS3" from the global namespace

### ISSUE THREAD

**Issue by vasilvestre** [liip/LiipImagineBundle#1536]
### Preconditions

1. 2.11.*
2. PHP 8.1

### Steps to reproduce

1. Follow tutorial https://symfony.com/bundles/LiipImagineBundle/current/cache-resolver/aws_s3.html

### Expected result

1. I expect no error from a compiler pass.

### Actual result

1. [Screenshot, logs]
![image](https://github.com/liip/LiipImagineBundle/assets/17164385/41be87e8-171c-4575-a7b3-6e08e35e5598)

**Comment by dbu** [comment]
afaik this only happens if you configure aws, not by default. i agree that the error could be nicer - for example the configuration class or DI extension could check for the existence of the optional dependency.

do you want to do a pull request to improve this?

**Comment by vasilvestre** [comment]
I now have the project working, I can't remember the issue and my issue miss details. Feels free to reopen if anyone encounter the issue !
