### ISSUE TITLE
Redirect not working when resolving the first time

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1560]
This is odd -- when I run locally, everything works.  When I run on production, the /resolve link doesn't load the redirect, and I end up with this:

![image](https://github.com/liip/LiipImagineBundle/assets/619585/da53dd8c-4859-4806-b9be-73a615593a7d)

When I refresh, though, it loads the /cache link and works, so it is firing the image creation.

And because it works locally, it's hard to test.

https://dt-demo.survos.com/congress/api_grid

The repo is here: https://github.com/survos-sites/dt-demo, but I haven't updated the documentation on how to configure and load flysystem.  But it's an example of how to use the local filesystem for dev and s3 for production, and I hope others will find it valuable.

It's also an example of a more complicated setup, because the table display is actually javascript, not twig, so the resolving has to happen in a normalizer, using the cacheManager, since the stimulus controller that displays the data get the data from ApiPlatform, so the normalizer adds the correct image path at runtime.

```php
            foreach ($object['imageCodes'] as $idx => $imageData) {
                // if the thumbnail exists, return the cached link, otherwise return the resolve link.
                // use getBrowserPath, ->resolve will actually create the cached file.
                $thumbnailUrl = $this->cacheManager->getBrowserPath($imageData['code'], 'squared_thumbnail_tiny');
                $object['imageCodes'][$idx]['thumb'] = $thumbnailUrl;
            }
```

**Comment by dbu** [comment]
i think i have seen such issues in the past, but don't know what the solution is.

i hope when we simplify things for 3.x, we can find a way that works reliable and avoids obscure problems with the redirect.

the logic is that if the cached image is available, the link renders as the path to the cache file. if it is not available, the link renders to the controller that will render the image - but the controller then answers with a redirect to avoid the client going through the controller each time it needs the image, to avoid overhead.

**Comment by tacman** [comment]
It works reliably on local, in both dev and prod env.  And it fails reliably on production when I clear the cache and refresh the page.

Specifically, it returns a 404 instead of a 301, but it then must create the file anyway.

My guess is that it has to do with permissions, especially since my /media/cache is a link to persistent storage, as the production disk is readonly at that point.  But it doesn't explain why the cached file is written.

**Comment by tacman** [comment]
Not sure if this helps, but here's the issue in action.

go to https://dt-demo.survos.com/congress/Q101136890, click on the red refresh button, which removes the cached images and redirects back.  You can see the 404's as above.

I'm asking our devops person to tweak permissions to see if that helps.  I'll post here if we solve it.

**Comment by Sumyabazar1** [comment]
it was linked to nginx with web browser caching for images thats the reason why it worked on locally but not in production.
```sh
location ~*  \.(jpg|jpeg|png|gif|ico)$ {
    expires 3d;
    log_not_found off;
    add_header Pragma public;
    add_header Cache-Control "public";
    access_log off;
    try_files $uri $uri/ /index.php?$query_string;
}
```
[Duplicated_Issue](https://github.com/liip/LiipImagineBundle/issues/784)

**Comment by tacman** [comment]
On the plus side, it's working now, but after all that it turned out to be an nginx configuration issue.  it still doesn't "feel" right, in that it feels fragile.  But I'll close this and mentally star it, I'm almost positive it will come up again and I'll forget how we solved it.
