### ISSUE TITLE
Document integration with backblaze adapter

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1564]
This is probably outside of the scope of this bundle, but I'll ask anyway, in case someone has experience in it and it's easy to share.

[Backblaze](https://www.backblaze.com/) advertises itself as an s3-compatible service that costs 1/5 of what Amazon does.  So I'd love to see an example of configuring this with LIIP.

On the plus side, it's easy to set up a free 5G account, and it's MUCH easier to configure than S3.  

Maybe s3 is cheaper if it's configured correctly, but setting up permissions and storage types are pretty complicated, especially for a small project backblaze seems much easier to use.

Eventually, I have millions of images to upload, so better pricing seems worth investigating.

**Comment by dbu** [comment]
would one of the flysystem adpaters for backblaze work? there seem to be a couple: https://packagist.org/search/?query=flysystem%20backblaze (it if is fully compatible with S3 i don't know why the packages exist...)

for version 3, i want to push all the storage abstraction to flysystem to avoid having to maintain any of it in the LiipImagineBundle.
