### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by Nelsallg** [liip/LiipImagineBundle#1566]
Failed to execute git checkout 2e943e6be4309ec90fcff90227053898203c1c8e --
   && git reset --hard 2e943e6be4309ec90fcff90227053898203c1c8e --

  error: invalid path 'Tests/Functional/app/public/images/cat?question.jpeg' in symfony 7.0

**Comment by Nelsallg** [comment]
by downloading the zip file, the class exists but is not detected by symfony


Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#107
  #message: """
    Attempted to load class "LiipImagineBundle" from namespace "Liip\ImagineBundle".\n
    Did you forget a "use" statement for another namespace?

**Comment by dbu** [comment]
the files are here: https://github.com/liip/LiipImagineBundle/tree/2.x/Tests/Functional/app/public/images

are you trying to develop things on the bundle? if so, you probably need to work on a system with a filesystem that can handle the `?` in the path.

if you only want to use the bundle, make sure that you don't use the composer flag `--prefer-source` for installing this bundle. the .gitattributes file tells that the `/Tests/` folder is not needed when exporting, avoiding the problematic file (and saving you space on the server disks)

**Comment by Nelsallg** [comment]
I use a bundle, but in the config/bundles.php file of symfony, I imported
the class, the docstring is displayed correctly but the class is not
detected by symfony and there is this error which is displayed
   Use of unknown class: 'Liip\ImagineBundle\LiipImagineBundle'

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mer. 31 janv. 2024 à 10:40, David Buchmann ***@***.***> a
écrit :

**Comment by dbu** [comment]
the issue tracker is for bugs of the bundle, but this does not seem to be a bug of the library. please ask in a php forum or on stackoverflow to get help with using composer / symfony / php.
