### ISSUE TITLE
Bundle impossible to install or update

### ISSUE THREAD

**Issue by HeleneGreat** [liip/LiipImagineBundle#1572]
I had trouble updating the bundle on a big project I have, so I tried to install the bundle on an almost empty symfony project.
I use the "composer require liip/imagine-bundle" command from the documentation but was unable to install the bundle.

### Preconditions

PHP 8.2.12
Symfony 6.0.20

### Steps to reproduce

In terminal write "composer require liip/imagine-bundle"

### Actual result

In the terminal, this is what I got :
```
./composer.json has been updated
Running composer update liip/imagine-bundle
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking imagine/imagine (1.3.5)
  - Locking liip/imagine-bundle (2.12.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
    Failed to download imagine/imagine from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\xampp\php\php.ini
    Now trying to download from source
  - Syncing imagine/imagine (1.3.5) into cache
    Failed to download liip/imagine-bundle from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\xampp\php\php.ini
    Now trying to download from source
  - Syncing liip/imagine-bundle (2.12.2) into cache
  - Installing imagine/imagine (1.3.5): Cloning 7151d553ed from cache
  - Installing liip/imagine-bundle (2.12.2): Cloning 2ad259dd46 from cache
    Install of liip/imagine-bundle failed
    0 [--->------------------------]
In GitDownloader.php line 500:

  Failed to execute git checkout 2ad259dd46ce55f93c6e8d87908d2572bd94796e -- && git reset --hard 2ad259dd46ce55f93c6e8d87908d2572bd94796e --

  error: invalid path 'Tests/Functional/app/public/images/cat?question.jpeg'


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

**Comment by dbu** [comment]
> Failed to download imagine/imagine from dist: The zip extension and unzip/7z commands are both missing, skipping.

you seem to be running on a windows system that can not handle filenames with `?` in them. therefore the `git clone` checkout fails. and looking at your log, composer can not find zip, so it does not download the dist (which would not contain the tests, and thus also not the problematic file).

try installing/activating the `php-zip` extension or install 7 zip and make sure it can be found from the shell where you run composer.

**Comment by HeleneGreat** [comment]
Thanks a lot, I would have never thought searching into php.ini for that solution. This is one of the many thinks I still have to learn.
I hope I had posted this issue in the right place.

**Comment by dbu** [comment]
no worries, glad this solved the problem.

normally the git clone would work fine. it is a bit unfortunate that we have a file in the repository that causes problems on windows file systems. but it tests an important edge case because `?` is a very specific character in URLs...
