### ISSUE TITLE
exif data not persisted in image

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1573]
Original Image: https://foothills-forum.s3.us-east-2.amazonaws.com/tac-dog-portrait-65d74b3a1492e677788677.jpg

![image](https://github.com/liip/LiipImagineBundle/assets/619585/cc5fb4b2-8096-4ac6-84e8-1b2d904bd0cb)

Thumbnail Image: https://ff.survos.com/media/cache/squared_thumbnail_medium/tac-dog-portrait-65d74b3a1492e677788677.jpg
https://jimpl.com/results/XB4ACNY682LCi2svLECD2Ruh?target=exif

![image](https://github.com/liip/LiipImagineBundle/assets/619585/417ca5bf-9afd-421a-aa35-845af1655d5d)

Using Liip with the Flysystem S3 adapter, imagick driver.

**Comment by dbu** [comment]
the imagine bundle does not actively do anything with exif data. you will need to look into the imagine library or imagemagick to debug this.
