### ISSUE TITLE
Regex in redirect optimization doc matches more than expected

### ISSUE THREAD

**Issue by e-five256** [liip/LiipImagineBundle#1576]
### Preconditions

This is related to the avoid redirect documentation for at least both [2.x](https://github.com/liip/LiipImagineBundle/blob/2.x/Resources/doc/optimizations/avoid-redirects.rst) and [3.x](https://github.com/liip/LiipImagineBundle/blob/3.x/doc/optimizations/avoid-redirects.rst)

### Steps to reproduce

We used the provided web server configuration in nginx in this doc:

```
location ~* .(js|jpg|jpeg|gif|png|css|tgz|gz|rar|bz2|doc|pdf|ppt|tar|wav|bmp|rtf|swf|ico|flv|txt|woff|woff2|svg)$ {
```

And found that on URLs that ended in any of these things, for example `/FirefoxCSS`, `/ruleico`, the routes were not working. It turned out the `.` was being used as the regex match on any character, so `xCSS` and `eico` would match. I believe the goal is to match on the file type, so we changed it to `\.` to fix this issue

### Expected result

The regex to not match when the location is not a specific file / file type suffix

### Actual result

I can't quite remember the actual result, I believe it was a 404, or at the very least the pages did not work

Edit: Ah, sorry, it might not be completely correct to say that. The routes responded as webpages fine, but it broke activitypub for those routes (getting a bit specific in implementation details, but the same urls also need to respond to `"Accept: application/activity+json" ` requests and they were no longer doing so. I think either way the intent wasn't to match on non-full stop characters for that regex.

**Comment by dbu** [comment]
yep, i agree that the intention was to match on literal `.` and not match any character. if you have a specific prefix path to the image controller set up, you could also add that at the beginning of the matching (which would probably also be more performant, which matters given this is applied to every request). something like `location ~* ^/my-prefix/.*\.(js|...`

do you want to do a pull request (against the 2.x branch, we will then merge that into 3.x to keep them in sync)? ideally, you try the prefix and escaping the `.` in your system to make sure the doc is working as specified (i would assume in nginx we don't need to double-escape `\` but with these things its always best to actually try to be sure :-)

**Comment by dbu** [comment]
the `*` after `~` btw is to make the regex case sensitive. i think we still want that, we don't expect sudden uppercase file extensions.

**Comment by e-five256** [comment]
I am so confused as to why github opened a PR against my fork instead of the base, I thought it was a long-standing issue that forked repos always open PRs against the base one, in fact [reading about it right now](https://github.com/orgs/community/discussions/11729) people are still saying it is how things are... Well, anyways, unrelated, would just really want to know if they changed that since it's been a pain

Anyways, interesting you say it's case sensitive. I'm not a regex expert. All I can really say is this whole kerfuffle started from https://codeberg.org/Kbin/kbin-core/src/branch/develop/docs/admin_guide.md#kbin-server-block which describes the same location regex, and it causing a `/Firefox` community to work fine but a `/FirefoxCSS` community to not. Perhaps there was some rewrites or something going on to make the routes lowercase but, that was just what was observed. It took me a while to find that it had likely originally come from here and I wanted to make sure those findings were at least brought back

I've opened a PR for just the escape change

Edit: Oh and I can confirm adding the backslash instantly fixed the owner who was affected, and all the server admins in our group are running `location ~* \.(` now, just with tons more suffixes, haha, like `|avi|ogv|flv|wmv)$ {`, but don't see a need to bring all those over

**Comment by dbu** [comment]
the insensitive is because of nginx with the `~`, not really a regex thing (those usually would use `i` after the delimiter).

thanks for the fix PR, that will help already. it still would be an issue if somebody has `.jpg` or similar (with literal dot) as part of a path, but those are rather unlikely.

**Comment by e-five256** [comment]
Thanks!
