### ISSUE TITLE
cache busting

### ISSUE THREAD

**Issue by lsmith77** [liip/LiipImagineBundle#168]
figure out some solution to make it possible to add some cache busting capability, see #167 

i guess it should not be that hard to implement. imho the cleanest solution would be to simply append a top level directory (rather than adding something to the file name) with some hash. we would add some basic hash routing to all loaders and then the cache busting could be enabled on a per filter (plus maybe on a global level?). the generated route would be adjusted accordingly to have the relevant placeholder in the pattern.

**Comment by jowe1** [comment]
@haavg it works like you said although the documentation says:
<img src="{{ asset('/relative/path/to/image.jpg') | imagine_filter('my_thumb') }}" />
on
http://symfony.com/doc/master/bundles/LiipImagineBundle/basic-usage.html

Please fix the documentation or explain why that is ...?!

**Comment by fritzmg** [comment]
👍 for cache busting ability. I am in need for that as well currently and I have to resort to manually renaming the file.

**Comment by michellesanver** [comment]
@fritzmg @jowe1 @lsmith77 I assume this issue is still relevant? If so I'll at least look at the documentation and see what can be further done about the cache busting to open a more clear workable issue about that.

**Comment by dbu** [comment]
it seems this is not a huge concern to most people, as nobody implemented it. i will close it.

**Comment by dbu** [comment]
actually accidentally implemented it while working on symfony asset versioning integration #1397 :joy:
