### ISSUE TITLE
Tag Filter Sets

### ISSUE THREAD

**Issue by trsteel88** [liip/LiipImagineBundle#185]
I had a previous opened issue but it had a few things in it. It was a bit all over the place so I opened a more specific one.

Basically I want to tag filter sets (rather than just filters). Is this some functionality you would be interested in?

Basically, I want to be able to define a few filter sets within my application logic. Rather than having to define them in my config. This would also allow you to create filters using specific images from your entities etc too. Eg, a specific watermark allow from a Watermark Entity.

So you could define watermark_id_234 (or whatever naming convention you want). This would then resize the watermark to the correct size and overlay it on the original image.

**Comment by michellesanver** [comment]
@trsteel88 I am going through all issues to sort and prioritise. Is this a feature that you still want? Thanks a lot for your feature request to begin with! :)
