### ISSUE TITLE
Thumbnail resize - maintain aspect ratio

### ISSUE THREAD

**Issue by electricBonfire** [liip/LiipImagineBundle#190]
Is there a way to maintain the aspect ratio while doing a thumbnail resize?

I would like to pass a max-height / max-width. For example the image is 20 x 30 and I try to create a thumbnail max:15 x max:15. It would then resize to 10:15

**Comment by darkbluesun** [comment]
How does the RelativeResize filter allow this?
You could specify { heighten: 15, widen: 15 } - but an image that is 1000x30px (HxW) will come out at 500x15 because the widen is applied after the heighten!
