### ISSUE TITLE
improve error message

### ISSUE THREAD

**Issue by dbu** [liip/LiipImagineBundle#192]
when i manage to pass an empty path into the imagine_filter twig function (e.g. i have a phpcr `Image` document that is null). now instead of getting some message like "Invalid image source" i get "An exception has been thrown during the rendering of a template ("Parameter "path" for route "_imagine_home_slideshow" must match ".+" ("" given) to generate a corresponding URL.")"

the last step is in CacheManager::generateUrl - is it sane to assume there that if the path is empty we do have a problem? or are there use cases where path can legally be empty?

i am happy to do a PR for this, but wanted to ask first if it makes sense at all.

**Comment by michellesanver** [comment]
Does this still make sense for you @dbu ?

**Comment by dbu** [comment]
lets drop it :-)
