### ISSUE TITLE
Chaining Filters

### ISSUE THREAD

**Issue by trsteel88** [liip/LiipImagineBundle#205]
Should you be able to chain filters?

Here is an example:

``` html
<img src="{{ asset.path | imagine_filter('asset') | imagine_filter('asset_icon') }}" alt="" /> {{ asset.clientOriginalName }}

```

The reason I want this is so that asset adds an overlay, then I want to display a smaller version of it "asset_icon". The "asset" filter will then be used in multiple areas.

Not sure if it makes a difference, but currently "asset" is using AbstractDoctrineLoader

**Comment by juanolon** [comment]
@trsteel88 did you get this filter-chaining to work? like your last example - it would be really useful to reuse filters like you proposal :)
