### ISSUE TITLE
add a way to force early creation of the cache file

### ISSUE THREAD

**Issue by lsmith77** [liip/LiipImagineBundle#242]
I have to dig in an see if and how it would make sense exactly. But when reading from a remote data source it can make sense to generate the cache entry in the request that renders the image tag.

**Comment by kufi** [comment]
If anybody is still interested in this, the fix is actually quite easy to implement. The following code creates the image as soon as the filter is called.

        new \Twig_SimpleFilter('imagine_create', function ($path, $filter)
            {
                try
                {
                    if(!$this->cacheManager->isStored($path, $filter))
                    {
                        try
                        {
                            $binary = $this->dataManager->find($filter, $path);
                        }
                        catch(NotLoadableException $e)
                        {
                            if($defaultImageUrl = $this->dataManager->getDefaultImageUrl($filter))
                            {
                                return $defaultImageUrl;
                            }

                            throw new NotFoundHttpException('Source image could not be found', $e);
                        }

                        $this->cacheManager->store(
                            $this->filterManager->applyFilter($binary, $filter),
                            $path,
                            $filter
                        );
                    }

                    return new \Twig_Markup(
                        $this->cacheManager->resolve($path, $filter),
                        'utf8'
                    );
                }
                catch(RuntimeException $e)
                {
                    throw new \RuntimeException(sprintf('Unable to create image for path "%s" and filter "%s". Message was "%s"', $path, $filter, $e->getMessage()), 0, $e);
                }
            })

Use it like this:

        'path_to_image'|imagine_create('filter')

**Comment by lsmith77** [comment]
can you submit a PR for this?

**Comment by kufi** [comment]
I can, but I'm not sure if it should actually be a separate command when being in the bundle. Maybe a flag on the current imagine_filter would be better. Something like "forceEarlyCreation" or similar.

**Comment by makasim** [comment]
> Maybe a flag on the current imagine_filter would be better. Something like "forceEarlyCreation" or similar.

:+1:  on flag option.

**Comment by mikemix** [comment]
No flags, please. Just another filter, like `imagine_filter_create`

**Comment by michellesanver** [comment]
@pscheit Is this something you are looking at? Given the eyes emoji. If not, I'd like to label this one as a "good first issue" and write some clear instructions what needs to be done. Let me know :)

**Comment by pscheit** [comment]
I was referring to: "Wow, this is still open lol".,. ;)

I'm not using imagine anymore

**Comment by dbu** [comment]
there is enqueue now and #1360 adds symfony messenger.
