### ISSUE TITLE
imagine_filter returns correct path, but does not apply the filter

### ISSUE THREAD

**Issue by kvandenhaute** [liip/LiipImagineBundle#249]
Hi,

When I try to apply a filter on an image in the template, as long as the resized version does not exist it does not work. I first need to apply the filter in PHP (f.e. in my container) and then it works.

Example: {{ photo.getWebPath()|imagine_filter('300x') }}

This will return "/media/cache/300x/storage/1/9/o/9e1e7d7aba725db118a4e078517ac927e760e558.jpeg". But the file (and subfolders) were never generated.

Now when I do the following in my controller:

$this->container->get('liip_imagine.controller')->filterAction($this->getRequest(), $photo()->getWebPath(), '300x');

.. everyting works fine. So my problem is that the Twig extension only returns the correct path, but doesn't really apply a filter on the image.

I have web_profiler.intercept_redirects set to false in my config.

I'm a forgetting something?

**Comment by pixocode** [comment]
simply comment "access_log off;" :)
