### ISSUE TITLE
[1.1][filters] Split dynamic filter hash into several folder.

### ISSUE THREAD

**Issue by makasim** [liip/LiipImagineBundle#341]
extracted from https://github.com/liip/LiipImagineBundle/pull/313#issuecomment-37261509

I just wanted to raise 1 issue with this implementation. Currently, you are generating a hash to authenticate that the values are correct. I think this should be split into several "directories".

Eg, say the generated hash is "S8rrlhhQ" I think it should be split up so it becomes "S8r/rlh/hQ" (or something similar). Otherwise, if a website has 100,000 images it is going to create up to 100,000 folders inside 1 (or more) directories. Splitting it into several directories will scatter the structure a bit more. This will make it much easier to navigate through ftp or viewing the folder and doing "ls -la".

**Comment by dbu** [comment]
it seems this is not a huge concern to most people, as nobody implemented it. i will close it.

**Comment by dbu** [comment]
it seems this is not a huge concern to most people, as nobody implemented it. i will close it.
