### ISSUE TITLE
autorotate exif_read_data bug

### ISSUE THREAD

**Issue by JeffGreat** [liip/LiipImagineBundle#381]
autorotate filter is not working neither on my server debian php5 (exif extension installed) nor on a wamp windows install.
Actually there is no error msg, the picture keeps is simply upside down. If you want I can send you the test picture (shoot with an ipad).
Thx

**Comment by fritzmg** [comment]
What is the status on this? Is
```yml
driver: imagick
```
a requirement to be able to use the `auto_rotate` filter?

I am trying to figure out why the `auto_rotate` filter is working on one server and on another it does not have any effect.
