### ISSUE TITLE
PSD conversion to jpg 

### ISSUE THREAD

**Issue by wilson12** [liip/LiipImagineBundle#426]
Not sure if this is an issue or not should the conversion happen automatically or should i modify the code 
the bundle successfully does png to jpg,jpg to png
But for psd to jpg it seems to fail.

**Comment by michellesanver** [comment]
@ama3ing @wilson12 I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly. Thanks a lot! :)
