### ISSUE TITLE
Upscale improvements

### ISSUE THREAD

**Issue by smilesrg** [liip/LiipImagineBundle#428]
Is it possible to add parameters for upscale like max[x,y], exact[x, y] and crop? Because currently it is not possible to upscale rectangle image to square with cropping using upscale filter. To achieve this behaviour, I had to downgrade to v0.11.1 and use thumbnails filter with allow_upscale set to true.

**Comment by michellesanver** [comment]
I believe this is fixed already. 

https://github.com/liip/LiipImagineBundle/pull/1015

If this is still an issue for you, please open a new PR with more information :)
