### ISSUE TITLE
Applying filters to high resolution images does not work

### ISSUE THREAD

**Issue by Tibolte** [liip/LiipImagineBundle#431]
When I use images less than 1000X1000, it turns out ok, filters are applied. But when I go above this resolution (not exactly, but around 1100X1100, 1200X1200 and more for instance), images are not created. I can only see the small default image icon on my page.

What would be the reason?

**Comment by michellesanver** [comment]
I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly. Thanks a lot! :)
