### ISSUE TITLE
Apply Filter In Command

### ISSUE THREAD

**Issue by ndoulgeridis** [liip/LiipImagineBundle#438]
Hello,

How can i apply filter in command without creating a new image but just apply filter to an existing image? I need to it for just append watermark but I want to append watermakr in the original image without creating a new one.

**Comment by michellesanver** [comment]
@ndoulgeridis I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly. Thanks a lot! :)
