### ISSUE TITLE
couldn't get working watermark

### ISSUE THREAD

**Issue by rohitten** [liip/LiipImagineBundle#459]
@havvg 
I was trying watermark filter but it doesn't work for me, it doesn't create neither the folder inside media folder nor the image ,here is my configuration
my_image:
            filters:
                watermark:
                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
                    image: %kernel.root_dir%/Resources/data/watermark.png
                    # Size of the watermark relative to the origin images size
                    size: 0.5
                    # Position: One of topleft,top,topright,left,center,right,bottomleft,bottom,bottomright
                    position: center

can you please provide a example image path for reference

**Comment by michellesanver** [comment]
@rohitten I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly, and I or someone else would then look at the watermark filter. Thanks a lot! :)
