### ISSUE TITLE
S3 Cache Resolver performance

### ISSUE THREAD

**Issue by sgarner** [liip/LiipImagineBundle#463]
The `AwsS3Resolver` appears to issue an HTTP `HEAD` request to Amazon S3 for each image on a page every time the page is loaded, to determine if each filtered image has already been cached. This is clearly non-performant.

Before I spend time trying think up a solution to this, can anyone confirm this is the intended behaviour and I'm not just doing it wrong?

**Comment by makasim** [comment]
Somehow the cached images were removed from s3. The bundle does not do anything like that so it was done from the outside or by human.
