### ISSUE TITLE
Thumbnail without redirect. How?

### ISSUE THREAD

**Issue by Neokortex** [liip/LiipImagineBundle#465]
I use this bundle with runtime config 

``` html
{% set runtimeConfig = {"thumbnail": {"size": [50, 50] }} %}
<img src="{{ '/upload/images/48540.jpeg' | imagine_filter('my_thumb', runtimeConfig) }}" />
```

works fine, but generated image link 

```
http://mysite/app_dev.php/media/cache/my_thumb/rc/srQEyOTi/upload/images/48540.jpeg?filters%5Bthumbnail%5D%5Bsize%5D%5B0%5D=255&filters%5Bthumbnail%5D%5Bsize%5D%5B1%5D=170
```

this link redirect to 

```
http://mysite/media/cache/resolve/my_thumb/rc/srQEyOTi/upload/images/48540.jpeg
```

image loading not fast :(

how to avoid this redirect?

**Comment by michellesanver** [comment]
@Neokortex I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly and investigate this potential bug. Thanks a lot! :)
