### ISSUE TITLE
A recent pull request has broken paths to images

### ISSUE THREAD

**Issue by trsteel88** [liip/LiipImagineBundle#478]
I have quite a few images within content (through CKEditor). A recent pull has destroyed the paths to images.

Eg, the path to the images in the database are to "media/cache/image.jpg". A recent change was to change the routes so they read from "media/cache/resolve/image.jpg".

This update should have been classed as a BC break.

**Comment by richsage** [comment]
@makasim did you decide either way on a solution for this? I just encountered the same issue, would be interested to know a 'best practice' resolution.

**Comment by trsteel88** [comment]
@makasim, do you know of a way we can address this issue?

**Comment by makasim** [comment]
> This is also terrible if an external website links to an image and the cache is deleted.

This is always the case when you deal with remote cache storages such as Amazon S3. There is no way to implement it for them. so why should we provide a solution only for local cache resolver. Also I'd suggest not to store static files like images locally. There is not any issue for me.

> I have quite a few images within content (through CKEditor). A recent pull has destroyed the paths to images.

Here I'd suggest next. You create copy of original image, edit it in CKEditor and upload it. Change the related image from original one to new edited one. Than sometime later delete (when everyone switch to the new image) original image and its cache.

The @nathankot solution (route overwriting) could be used too if you dont care about Safari

**Comment by trsteel88** [comment]
It shouldn't be the case though. Especially if images are indexed by Google for Google Images. You don't want to delete that cached image or the reference would be lost forever. 

Does the safari issue even still exist? Surely it has been fixed and implementing a "fix" on their behalf shouldn't degrade the bundle performance.

**Comment by makasim** [comment]
if you delete an image on s3 and google index it you lose it too.

**Comment by trsteel88** [comment]
I'm not saying to delete the original. I am just saying if you deleted the cached image.

e.g cached image is /media/cache/image.jpg - if you delete this it will 404. However, the actual cache can be re-generated by going to media/cache/resolve/image.jpg. Except now external sources are ever going to trigger that action.

**Comment by makasim** [comment]
> I'm not saying to delete the original. I am just saying if you deleted the cached image.

Could you explain why do you want to delete it? What are the reasons to do so?

**Comment by trsteel88** [comment]
Sorry, I edited the comment with a reason so you may not have seen it.

> I say this because on a website you may want to clear the media/cache directory once a year to flush old images. I still want those cache paths to work if they are still used.

**Comment by makasim** [comment]
In that case you have to regenerate all that cache in console, or provide a route like @nathankot suggested.

**Comment by trsteel88** [comment]
Correct. I am suggesting that those routes should be part of the bundle (like they used to be). I don't think this bundle should be patching Safari's issues (only to cause other issues).

**Comment by makasim** [comment]
> Correct. I am suggesting that those routes should be part of the bundle (like they used to be). I don't think this bundle should be patching Safari's issues (only to cause other issues).

I dont think so, Safari is not an argument here. If we provide a route it will work only for default resolver configured with default values but what if you configure it differently.What if you change cache prefix it would not work... so I believe it has to be impl in app code, it is not hard to do...

**Comment by trsteel88** [comment]
> default values but what if you configure it differently

Well no, we could load a route based on the prefix config.

> What if you change cache prefix it would not work

If you specifically change it, it should definitely be up to the user to 301 those old requests.

I think this is a serious issue. If a cached path is stored anywhere as a static link (e.g with a WYSIWYG) this is vulnerable to problems.

**Comment by trsteel88** [comment]
* Didn't mean to close that.

**Comment by makasim** [comment]
Two solutions:

* use cli command to regenerate cache if you remove it.
* add custom route 

End of story.
