### ISSUE TITLE
Allow setting the output image resolution

### ISSUE THREAD

**Issue by CodeMonkey90** [liip/LiipImagineBundle#482]
Currently, both the Imagick and the Gmagick backend of Imagine support setting the image resolution, but there is no corresponding configuration option in LiipImagineBundle, which makes implementing something similar to Imagine\Filter\Basic\WebOptimization impossible. Possible solutions:
- Add a configuration option allowing to specify the desired image resolution in ppi (preferred)
- Add a configuration option which allows us to pass additional options to $image->get() in FilterManager::apply()

**Comment by michellesanver** [comment]
I think this is a good idea to still do if relevant, need to investigate.
