### ISSUE TITLE
[DX] Use dynamic Twig filters instead of hardcoded imagine_filter()

### ISSUE THREAD

**Issue by javiereguiluz** [liip/LiipImagineBundle#483]
As you know, Twig supports [dynamic filters](http://twig.sensiolabs.org/doc/advanced.html#dynamic-filters) which allow to create filters with undefined parts in their names. My question is: could we use this feature to allow the use of dynamic filters instead of `imagine_filter`?

``` jinja
{# current filters with no parameters #}
<img src="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb') }}

{# proposal #}
<img src="{{ '/relative/path/to/image.jpg' | imagine_my_thumb }}

{# current filters with parameters #}
<img src="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb',  { thumbnail: { size: [50, 50] }}) }}

{# proposal #}
<img src="{{ '/relative/path/to/image.jpg' | imagine_my_thumb({ thumbnail: { size: [50, 50] }}) }}
```

The idea would be to define [in the Twig extension](https://github.com/liip/LiipImagineBundle/blob/master/Templating/ImagineExtension.php#L30) a dynamic filter called `imagine_*`  A question for the heavy users of this bundle: do you think that this change would be a good idea? Or it's better to continue using the current `imagine_filter`?

**Comment by carakas** [comment]
We are using this bundle in our cms and the use case we see is allowing people in the backend to set a width and height for an image.
