### ISSUE TITLE
Opposite of inset?

### ISSUE THREAD

**Issue by appeltaert** [liip/LiipImagineBundle#484]
To take the docs as an example:

Inset maintains aspect and keeps the dimensions within boundaries, but what if i want the opposite? I want one side to be exceeding, without cropping(so no outbound). So 50x30 > min: 40x40 = something like 60x40.

Way to do this right now with some chain combination? Did some digging into the code but it doesnt seem possible?

Probably doing something wrong, pretty common technique for example background fillers. 

Upscale (even with the over-complex description "expanded to the requested size by interpolation of its content.") doesn't seem to do it looking at the code. There still is a widthxheight condition check returning false if one side is exceeding.

**Comment by michellesanver** [comment]
@appeltaert I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly and look into the opposite of inset, closing this for now. Thanks a lot! :)
