### ISSUE TITLE
hotlink cache image from outside

### ISSUE THREAD

**Issue by poznet** [liip/LiipImagineBundle#494]
Hello  
this  could be a stupid  question, but  i can't work it  out 

I got some resized images  ( standard Liip configuration ) ,everything  works  fine , but  how do "hotlink" image  from another domain ? 

On another domain if i give  html   img src="http://domainwithsymfonyandliip.com/media/cache/fotos/foto/679/13.jpg"   i get 404 

i understand that is a routing  thing - is there any simple method to access this cached image  "from the outside" ?

**Comment by CedCannes** [comment]
@poznet Until now I used AvalancheImagineBundle and access to images from the outside thumb worked well. If the thumb file not exists the request go in avalanche controller and the thumb is generated.

Unfortunally I found this message on AvalancheImagineBundle github : " Deprecated
This project is no longer actively maintained, please find one of the populate forks. Thanks!"

so I looked for an alternative and found LIIP, i replace easily AvalancheImagineBundle with LiipImagineBundle but "hotlink"  image from another domain doesn't work with it.

according to the @makasim message, it looks like I'll have to find another new alternative :)

**Comment by trsteel88** [comment]
I would suggest this also related to #478 - previously if you had linked to the cached url it would have been automatically created.

**Comment by mitrae** [comment]
very sad. we used 0.21.2 and was very happy because of "lazy" cache. now it seems we have to look for alternatives, because now varnish caches page with "resolve" in path.

**Comment by michellesanver** [comment]
It doesn't seem like this is something we will work on. If this is still an issue for you and you believe it is something this bundle should support please open a new issue.
