### ISSUE TITLE
Exception: PHP exif extension is required to use the ExifMetadataReader

### ISSUE THREAD

**Issue by JasonHanley** [liip/LiipImagineBundle#501]
When upgrading to the lastest dev-master, I receive the following when simply trying to read an image:

Uncaught PHP Exception Imagine\Exception\NotSupportedException: "PHP exif extension is required to use the ExifMetadataReader" at /home/rumie/test-content/vendor/imagine/imagine/lib/Imagine/Image/Metadata/ExifMetadataReader.php line 25 {"exception":"[object] (Imagine\Exception\NotSupportedException: PHP exif extension is required to use the ExifMetadataReader

Probably better to simply not read the exif data rather than blowing up.

I suspect this used to either be optional or go through a different path.

**Comment by lukaszrak** [comment]
Still not fixed.

**Comment by x3r0z** [comment]
I fixed that problem change the value of the parameter liip_imagine.meta_data.reader.class in imagine.xml by default the value is Imagine\Image\Metadata\ExifMetadataReader and I change to Imagine\Image\Metadata\DefaultMetadataReader, if that parameter can change in the bundle config to that way not modified the bundle.

**Comment by stefann-sasori** [comment]
@x3r0z editing imagine.xml solved the problem for me thank you.
If it can help, the absolute path of this file is : 
vendor\liip\imagine-bundle\Liip\ImagineBundle\Resources\config\imagine.xml

**Comment by Miliooo** [comment]
I added this to my parameters: (config.yml)
liip_imagine.meta_data.reader.class: "Imagine\Image\Metadata\DefaultMetadataReader"

**Comment by WebDevCodr** [comment]
@Miliooo Thanks for your solution, works great!

**Comment by MAXakaWIZARD** [comment]
@lsmith77 this is not an issue with imagine lib, the bundle configures it with `ExifMetadataReader` which requires `ext-exif`. I think we need to change it to `DefaultMetadataReader` or configure it dynamically depending on `ext-exif` availability.

**Comment by stickyhands** [comment]
@Miliooo @WebDevCodr I have an unrecognized option error here with that fix

**Comment by cedricziel** [comment]
@stickyhands I just opened #841 which should fix the issue with a compiler pass, so you don't have to fiddle around with parameters here.

btw: @Miliooo surely meant setting it through a parameter and not directly in config.yml.
