### ISSUE TITLE
Cleanup of ImagineController::filterAction() -- Remove Request param and extract functionality

### ISSUE THREAD

**Issue by ReservedDeveloper** [liip/LiipImagineBundle#506]
Researching how to use the ImagineController, I ran across #485. Once I took a look at this method, I realized a few things.

  1. The Request object isn't being used
  2. This makes things a little cumbersome for any commands that might be utilizing this service.
  3. Any callers that don't need to output the image are at a loss.

I think the ideal would be if we could extract the file creation/URL generation functionality into a separate service method, and then allow the ImagineController to utilize that service and generate a redirect based on the response from the service method. This same service could be utilized by #379, thus cutting down on some redundancy currently present in the system.

**Comment by makasim** [comment]
see https://github.com/liip/LiipImagineBundle/issues/686
