### ISSUE TITLE
Bug at cache lookup

### ISSUE THREAD

**Issue by ghostika** [liip/LiipImagineBundle#516]
I came across with an interesting bug with the cache lookup.
My setup:
storage on S3
cache is Redis

The main problem is the first `/` character. 

In my example, I have a file with this path:
`/userImage/234/13123jfk24.jpg`

Using the twig filter, the CacheManager will look in the Redis cache with this path, and it will be a miss, so it's generate a resolving url. After this, the resolving url will be called, and this is where the problem comes from. In the ImagineController:filterAction the cachemanager is looking for the path, but at this time, the path will be this: `userImage/234/13123jfk24.jpg` without the first `/` because that is the route parameter delimiter and after resolve, the entry will be stored under the cachekey for the path without `/`. With the FileSystemLoader, it's not a problem, cause it takes care of this, and append a `/`.
Part of my workflow is that if a user creates a new cut of an avatar, I remove the stored one from S3, at the same time deleting the Redis entry( actually this one is not happening cause it's not finding the key ) and then a new image should be generated.
 At this point I made a shortcut, at the remove process I ltrim() the path with the `/` so it will delete the right key from redis but this one doesn't solve the problem of the double lookup.

**Comment by digitalkaoz** [comment]
could you create a PR for that?

**Comment by ghostika** [comment]
Done
