### ISSUE TITLE
Cache manager remove function does not remove files generated by dynamic filters configurations 

### ISSUE THREAD

**Issue by mahmouds** [liip/LiipImagineBundle#525]
The cache manager has a function to get a different path for the image based on the run time configurations passed to the filter https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/CacheManager.php#L148

The web path resolver is stored check is done only for the static configuration defined for the filter https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/Resolver/WebPathResolver.php#L64
This means that any image generated by a run time configuration is not cleared from the cache manager

**Comment by trsteel88** [comment]
@makasim, to resolve this we would need to include a wildcard in the filesystem delete so it removes all 

/media/cache/[filter]/rc/*/[path]

This means we don't need to work out the hash for every single image.

**Comment by makasim** [comment]
> to resolve this we would need to include a wildcard in the filesystem delete so it removes all

have you tried? I believe it must work out of the box for local storage. Just pass the path with a wildcard

**Comment by trsteel88** [comment]
Not at this stage. I'm am not to familiar with any resolver other than the WebPath resolver. I could give that one a go if anyone else is able to do the others?

**Comment by makasim** [comment]
I dont think the feature is supported, at least out of the box and for all resolvers. I plan to impr support of this feature in 2.0 https://github.com/liip/LiipImagineBundle/issues/686
