### ISSUE TITLE
Issue with path on Windows?

### ISSUE THREAD

**Issue by yellow1912** [liip/LiipImagineBundle#527]
In Liip\ImagineBundle\Binary\Loader\FileSystemLoader

we have:
$absolutePath = $this->rootPath.'/'.ltrim($path, '/');

On Windows, we will get something like:
/D:/absolute/path

Is this intentional or should it be something like: 
$absolutePath = ltrim($path, '/');

**Comment by michellesanver** [comment]
@yellow1912 Did vinhtrinh's solve your issue? If not, please open a new issue if this is still an issue for you. Thanks! :)
