### ISSUE TITLE
S3 GET Parameters not stripped

### ISSUE THREAD

**Issue by rdohms** [liip/LiipImagineBundle#529]
We use S3 to store our images and use a temporary url to read them, this url obviously has a few extra parameters in it.

`0ed3ab5ec2bd1fbaa44c4dbc4766205a.jpg?AWSAccessKeyId=<key>&Expires=1408614399&Signature=<signature>`

This is fine when it goes into the cache manager for loading, but the cached file simply dumps that full url, into the filename, schema and get parameters included.

What's the best way around this? I would guess a transformation on the check of caching and the write of caching would be enough is this doable from outside the plugin?

**Comment by makasim** [comment]
This is the url of cached image, is it? And do you want to strip those query parameters off? If so you can create a listener on POST_RESOLVE and do with the url whatever you need.

**Comment by svassaux** [comment]
@rdohms @makasim same issue with the new asset component of symfony, see https://github.com/liip/LiipImagineBundle/issues/647
This would be nice to have s simple parameter option to remove get parameters. Meanwhile, creating a listener should do it, I'll give it a try

**Comment by svassaux** [comment]
I've tried with a listener which strips get parameters ath the post_resolve event but there are cases when this post_resolve event is not called.

the following does not go through the resolve function, how can I handle that ?
img class="img-circle" src="{{ asset('images/user.png') | imagine_filter('mini')  }}"

**Comment by makasim** [comment]
If the cache already exist, you are redirected to the cached image, by passing the filter action, indeed the post resolve event is not triggered. 

We may need a new listener which triggers before we resolved the cached image url

**Comment by michellesanver** [comment]
@rdohms @makasim Unclear if this is still an issue. Since this is so old, could you do me a favour and open a new issue if that is the case? Then we can prioritise and possibly implement a new feature accordingly. Thanks! :)
