### ISSUE TITLE
how to apply grayscale filter on an image?

### ISSUE THREAD

**Issue by mappedinn** [liip/LiipImagineBundle#540]
Hi,

Could you please tell how to apply a grayscale filter on an image?

Thank,

**Comment by snjegov** [comment]
I'm also looking for this feature - is it possible to achieve this? Any hints?

**Comment by igormukhingmailcom** [comment]
@snjegov Hi

You can use Here function that you may use: https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Filter/Advanced/Grayscale.php

Or you can write own fast wrapper by yourself.
Here is my example with custom trim filter & wrapper: https://github.com/liip/LiipImagineBundle/issues/586

**Comment by snjegov** [comment]
great, I'll give it a try :)

**Comment by garak** [comment]
This is my working solution: http://stackoverflow.com/a/30026664/369194

**Comment by michellesanver** [comment]
@mappedinn I am going through all issues to sort and prioritise. Is this still an issue for you? Did garak's solution solve it? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly. Thanks a lot! :)
