### ISSUE TITLE
GridFSLoader - how to add image extension to cached images?

### ISSUE THREAD

**Issue by veego** [liip/LiipImagineBundle#552]
Is this possible to add `.jpg` or `.png` to images filename based on `mimeType` entry in mongodb? For now my webserver don't sent 'Content-Type' headers for images, because files looks like: `/cache/my_thumb/54b79df80a676a5511b4c6b5`.

**Comment by michellesanver** [comment]
@veego Is this still a question that you have? If so I'll look at it, thanks! :)

**Comment by veego** [comment]
I think so, I not try to solve that, but it might be helpfull to properly load images on website.

**Comment by dbu** [comment]
gridfs has been removed from this bundle in 2.0, in favor of the flysystem gridfs adapter.
