### ISSUE TITLE
Thumbnails aren't generate on prod environment

### ISSUE THREAD

**Issue by caramba1337** [liip/LiipImagineBundle#553]
Hi Guys,

I am on "dev-master". After i updated through composer to the latest version, i got issues with the thumbnail generation on prod. I got an dev and prod environment on the same server. Tried to delete the cache by hand and checked the permissions ( which are correct by the way ).

i've attached my config

https://gist.github.com/caramba1337/e335685397f8151f9c4e

**Comment by caramba1337** [comment]
It doesn't generate the /media/... folder structure at all. I have the same file permissions for dev and prod.

**Comment by veego** [comment]
What's the log say:)
`tail app/logs/prod.log`

**Comment by caramba1337** [comment]
Well there are no issues in the prod logs. I these lines in the nginx error log

Like i said before. It isn't generating any cache folder structure at all.

2015/01/16 15:41:51 [error] 18420#0: *21119 stat() "/var/www/vhosts/heiratslocation.de/htdocs/web/media/cache/resolve/location_gallery_thumb_medium/images/locations/6b4ihqqbt2o8cgkg0w4/54b8fb9f12af9.jpg" failed (2: No such file or directory), client: 31.18.82.26, server: heiratslocation.de, request: "GET /media/cache/resolve/location_gallery_thumb_medium/images/locations/6b4ihqqbt2o8cgkg0w4/54b8fb9f12af9.jpg HTTP/1.1", host: "heiratslocation.de", referrer: "http://heiratslocation.de/s?anchorventures_searchbundle_locationsearch_form%5Bquery%5D=hamburg&anchorventures_searchbundle_locationsearch_form%5Bprice%5D=&anchorventures_searchbundle_locationsearch_form%5BguestQuantity%5D=&anchorventures_searchbundle_locationsearch_form%5BroomQuantity%5D="
2015/01/16 15:42:05 [error] 18420#0: *21119 open() "/var/www/vhosts/heiratslocation.de/htdocs/web/media/cache/resolve/location_gallery_thumb_medium/images/locations/iq8b963ypugc8gccc8w/54b9232b54ac2.jpg" failed (2: No such file or directory), client: 31.18.82.26, server: heiratslocation.de, request: "GET /media/cache/resolve/location_gallery_thumb_medium/images/locations/iq8b963ypugc8gccc8w/54b9232b54ac2.jpg HTTP/1.1", host: "heiratslocation.de", referrer: "http://heiratslocation.de/s?anchorventures_searchbundle_locationsearch_form%5Bquery%5D=hamburg&anchorventures_searchbundle_locationsearch_form%5Bprice%5D=&anchorventures_searchbundle_locationsearch_form%5BguestQuantity%5D=&anchorventures_searchbundle_locationsearch_form%5BroomQuantity%5D="

**Comment by veego** [comment]
Try to manually create `web/media` directory, and set 777 permissions, or change owner to the webserver user (usually `www-data`).

**Comment by caramba1337** [comment]
i already tried. Like i wrote above. Its the same server i am running the dev and prod environment on. So i tried to manually create the directory but it isn't generating thumbnails at all.

**Comment by caramba1337** [comment]
i only got the problem since i updated to current master. I updated it in november the last time.

**Comment by caramba1337** [comment]
Meanwhile i found out that if you cache images through nginx, it seems like they won't be regenerated by the bundle. Maybe i had old path in the cache. Is there a better way to do caching or should i turn it off?

    location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
        access_log off;
        expires 365d;
    }

**Comment by caramba1337** [comment]
Seems like nginx is caching the path BEFORE the redirect. Which means the bundle won't recognize the call of the given image ( cause the redirect won't work at all ). So is there a better caching strategy for images in combination with the redirect problem?

**Comment by diegocastro** [comment]
Have you found a solution? I'm having the same problem

**Comment by makasim** [comment]
It most likely an issue in server configuration or permissions.  Everything works fine in the sandbox: https://github.com/makasim/LiipImagineBundleSandbox
