### ISSUE TITLE
Error doc Filters PostProcessor

### ISSUE THREAD

**Issue by Spawnrad** [liip/LiipImagineBundle#555]
Hi,

I found an error in the documentation Filters : 
https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/filters.rst

it's not **loader=** => it's **post_processor=**
```
<service id="liip_imagine.filter.post_processor.my_custom_post_processor" class="Acme\ImagineBundle\Imagine\Filter\PostProcessor\MyCustomPostProcessor">
    <tag name="liip_imagine.filter.post_processor" post_processor="my_custom_post_processor" />
</service>
```

**Comment by lsmith77** [comment]
can you submit a PR?

**Comment by Spawnrad** [comment]
https://github.com/liip/LiipImagineBundle/pull/556
