### ISSUE TITLE
Varnish and cookies

### ISSUE THREAD

**Issue by peternijssen** [liip/LiipImagineBundle#557]
I am not exactly sure if it's due to this bundle, but I think so.

Currently I am running a website with lots of images, which are resized by this bundle. Varnish is in front of this website and I am stripping all cookies away from the request and response headers to make sure static files are cached.

What I noticed however is that I am logged out on a regular basis in our system. It seems like I am getting a new session appointed or the old one is invalid.

This doesn't occur when all images have been created in the cache directory, but only when the images are created for the first time. I suspect it has something to do with the fact the image is resized on the fly and you basically "enter" Symfony instead of returning a static file from the cache.

Is this a known problem? Or am I searching in the wrong corner?

**Comment by makasim** [comment]
> Is this a known problem? Or am I searching in the wrong corner?

it could be the case indeed. If the cache is empty then the symfony filter action is hit and if symfony configured to auto start session than the session is started. If you dont really needed this you can generate cache images in background. It could cli script which prepares all cache variants.

**Comment by peternijssen** [comment]
Yeah I was thinking the same, but that would generate too much images due to the amount of filters. I am more looking in a practical solution within the code. Any clues?

**Comment by makasim** [comment]
> Any clues? 

you have to disable session auto start for this particular filter action in symfony. A listener may help here.

Do you really need it? What is the problem with getting a new session?

**Comment by peternijssen** [comment]
I am stripping away the session cookie from the request and response by Varnish, so it caches the files and makes sure I got cache hits. That's why I am not "receiving" a new session cookie on the moment I am "generating" images.

**Comment by trsteel88** [comment]
Make sure your firewall is ignoring your image paths as well if you have a firewall that would activate on /media/cache requests.

eg:

```yaml
security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|media/cache)/
            security: false
```

**Comment by trsteel88** [comment]
@peternijssen also, make sure that you don't have any other libraries that are trying to start the session.

e.g, if you are using the older Facebook library, it starts a session with session_start(). If this is the case, it will break your session so you need to start the session through Symfony's session class first. See https://github.com/symfony/symfony/issues/11612#issuecomment-55190436

**Comment by peternijssen** [comment]
Thanks all for your responses. I already tried @trsteel88 his solution, only with "media" as path, but both "media" and "media/cache" don't make a difference. In both cases, I am losing my session again.

Regarding the session_start(), I search through the entire codebase (including vendor) but the only place I find it, is in Symfony itself.

**Comment by peternijssen** [comment]
Alright. I think I kinda solved the issue. A listener was kicked off which was using the session to get some data. That started a session and thus created this problem. I now added a if ($this->session->isStarted()) around it + I implemented this session listener; http://www.mattfitz.info/notes/466

Not sure yet if it's completely fixed, but it already seems to go better.
