### ISSUE TITLE
AwsS3 v3 support

### ISSUE THREAD

**Issue by yellow1912** [liip/LiipImagineBundle#558]
Now that V3 is out, many bundles are starting to support it. The problem is that we cannot include both v2 and v3 which will result in a conflict with composer. Can we either: update to v3 or remove the requirement for v3 from require-dev?

**Comment by magedan** [comment]
Just curious, is there any chance to use concurrent requests to AWS S3 to generate cache thumbnails in LiipImagineBundle?

**Comment by makasim** [comment]
@magedan what do you mean by saying "concurrent".

**Comment by magedan** [comment]
aws-sdk-php v3 documentation says:
>Is built on Guzzle v5, and utilizes many of its features, including persistent connections, concurrent requests, events and plugins, etc.

I guess "concurrent requests" actually means "asynchronous requests" using promises: http://docs.guzzlephp.org/en/latest/clients.html#asynchronous-requests

This feature may potentially reduce the thumbnails generation time (if there are several thumbnails to generate). For example, my current application has to generate 3 thumbnails on S3 server during one API request, each thumbnail takes about ~0.3s to generate. What I'll be glad to achieve is to parallelize thumbnail generation using promises.

**Comment by makasim** [comment]
Not sure, One http request to filter action generates one thumbnail and you have to wait for the response from aws to get the image url.

**Comment by magedan** [comment]
Ok, thanks!
