### ISSUE TITLE
Resolver for redis (SncRedisBundle)

### ISSUE THREAD

**Issue by ahurt2000** [liip/LiipImagineBundle#562]
Any suggestions for using redis as cache images?
  using SncRedisBundle

**Comment by makasim** [comment]
I would not suggest to store images to redis, could you please explain why do really want to store them there?

**Comment by ahurt2000** [comment]
The cache in web path seem not a good option in our project.
Instead of memcache, web_path or s3 intend to use redis for cache images, because we use it for other purposes.
Why not redis?
Any suggestions? 
No one tried to make a CacheResolver for redis ??  (SncRedis)

**Comment by makasim** [comment]
> The cache in web path seem not a good option in our project.

Why not, Do you face any limitations of filesystem or s3?

**Comment by ahurt2000** [comment]
We have several nodes in production for frontend and backend but we have a shared file system. (Sysadmins argue that we should we use Redis)  (access to s3, or others is restricted)

**Comment by makasim** [comment]
well, nobody implemented it, feel free to do so and send a PR.
