### ISSUE TITLE
"Resolve" issue with symfony cmf bundle and doctrine phpcr 

### ISSUE THREAD

**Issue by xingshi** [liip/LiipImagineBundle#564]
Hi Everyone 

I have an issue of resolving an image when set up with cmf bundle and phpcr, basically an imagine block is created and the image is uploaded and stored into database using doctrine phpcr, then I want to load this image in front end, is this possible now, I have seen the change doc that says 

Changelog
=========

* **2013-09-17**: [PHPCR loader] DoctrinePHPCRLoader is now deprecated, as the
  CmfMediaBundle provides a more reliable loader that is already provided as a
  service. See http://symfony.com/doc/master/cmf/bundles/media.html#liipimagine

Does this means the image saved with phpcr wouldn't work with liip imagine? I am recently working on a Sylius project and it loads the image stored by phpcr, but the url rendered is something like `http://sylius:8888/app_dev.php/media/cache/resolve/{filter_name}/cms/blocks/{block_name}/image`
it can not be resolved. Can this be fixed?

Many thanks

**Comment by lsmith77** [comment]
yes .. see https://github.com/liip/LiipImagineBundle/commit/8a58d95a355f8d1c2c4e45f34976c32b46f0d282

@sylius should use https://github.com/symfony-cmf/MediaBundle/blob/master/Adapter/LiipImagine/CmfMediaDoctrineLoader.php instead

/cc @pjedrzejewski @dbu

**Comment by dbu** [comment]
so should we close the issue here and open one on sylius?

**Comment by lsmith77** [comment]
I think so yes .. but I haven't checked the Sylius code base for details
