### ISSUE TITLE
Cache invalidation when using "runtime config" example

### ISSUE THREAD

**Issue by joshribakoff** [liip/LiipImagineBundle#571]
In your readme, you show how to set the runtime config... I'd like to use 1 filter called "my_thumb", and then just code the widths & heights into each Twig call. The reason being is that I think the designer who edits the Twig files should be the one who sets the widths & heights. The overhead of setting up a named filter each time is undesirable to me.

Here's your example:
```
{% set runtimeConfig = {"thumbnail": {"size": [50, 50] }} %}
<img src="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb', runtimeConfig) }}" />
```

I am then doing this when I wish to invalidate the cache:
```
$cm = $this->getContainer()->get('liip_imagine.cache.manager');
$cm->remove('/relative/path/to/image.jpg');
```

Normally the files are cached to "cache/my_thumb". However, when passing the runtime config they are not cached there - they are instead cache into a folder "rc" with subfolders that appear to be some sort of hash.

When I ask the cache manager to invalidate caches for my source file, it only clears "cache/my_thumb" & it is not clearing any cache files that were created with a custom "runtime config" & cached to the "rc" folder.

Wouldn't it be simpler if you just looked at the modification time/hash of my original image, and invalidate it for me? I don't even desire to do explicit cache invalidation. Your docs for the cache invalidation are unclear to me. You do not show examples, and it leave users confused as to what they should pass for the value of the `$path` parameter. As it stands I have no idea how to clear the cache for any files with a "runtime configuration" & I am not finding any help via the documentation.

Furthermore, it should be easier for me to purge my own cache files outside of this library. Due to your choice to store the folder name as a hash, I'm unclear how to do that. I'd suggest the folder to be named "rc/50x50" rather than "rc/{some_random_hash}" - that would improve the library by allowing it to "get out of the way" when needed, if that makes sense.

**Comment by makasim** [comment]
The hash is required, because runtime config may container different options, and the bundle does not control them, you as a developer control them. So the bundle not able to generate fine path because it does not know what inside the config path. We just do a hash from the serialized config. 

The runtime cache invalidation is planned for 2.0 see https://github.com/liip/LiipImagineBundle/issues/686

Feel free to reopen if you still have any question
