### ISSUE TITLE
Get filesystem path from cache manager

### ISSUE THREAD

**Issue by kiler129** [liip/LiipImagineBundle#572]
Is it possible to get absolute filesystem path from cache manager?
Reading documentation and code I've found that it's only possible to get browser path:

``` php
$this->get('liip_imagine.cache.manager')->getBrowserPath('/relative/path/to/image.jpg', 'my_thumb', true),
```

However creating external outputs like PDFs I wish to use image with liip filters without executing unnecessary HTTP requests. Is it possible, or method like "getFilesystemPath()" need to be added to support such thing?

**Comment by richsage** [comment]
This would be great if possible - we have the same use case regarding PDFs.

**Comment by makasim** [comment]
> "getFilesystemPath()" need to be added to support such thing?

We can add such method to FilesystemResolver. The problem is if you use this method you are not able to change the resolver to another one as you tie to this implementation of resolver

**Comment by kiler129** [comment]
@makasim: I know, it's little drawback but sadly I don't see any other options. I currently use http request but it's rather bad method in terms of performance & good practices.

**Comment by richsage** [comment]
It almost makes sense for that method to *only* be available on FilesystemResolver really - given that it's a local path that is required.

**Comment by broadcasttechie** [comment]
Sorry if I'm missing something here, but is this function available? I can't see any reference to it in the docs...

**Comment by makasim** [comment]
No it is not, as far as I remember  nobody sends a pull request with the feature.

**Comment by webbk05** [comment]
Ok - I'll give it a go. (any hints appreciated!)

**Comment by broadcasttechie** [comment]
Ok, I'll give it a go... (any hints appreciated!)

**Comment by salemgolemugoo** [comment]
Is there some way to remove cached images from cache  manager?

**Comment by makasim** [comment]
Have you tried this method https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/CacheManager.php#L252

or simialr cli command

**Comment by salemgolemugoo** [comment]
@makasim Thx man! That was I looking for.

**Comment by Koc** [comment]
Have same requirements. `getFilesystemPath` would be useful.

**Comment by makasim** [comment]
@Koc We can add it to a local resolver only (the resolver specific method which is not covered by the interface.)

**Comment by kiler129** [comment]
@makasim: Is there any documentation note about it? if yes I think we can close this issue with a link to it ;)

**Comment by makasim** [comment]
This is a feature that has to be implemented

**Comment by kiler129** [comment]
@makasim: Ough, I misread your comment actually because it was middle of the night in my TZ - apologies.
Maybe I'll find some time to implement it.

**Comment by wuethrich44** [comment]
I have the same problem with a pdf generator. So I can spend some time to implement this feature.

@makasim Do you have a hint where I could start? As far as I see implementing another resolver couldn't fix this problem.

**Comment by makasim** [comment]
I would say we can add a method to  filesystem resolver like getAbsolutePath then you can use it in a template

**Comment by wuethrich44** [comment]
I found a possibility to access the absolute file path but it is not very elegant. As the thumbnail generation is coupled to the controller there is no elegant way to create a thumbnail programmatically. But as far as I know this issue will get adressed in a upcoming release.

To get the absolute path I create a custom resolver which override the `resolve` method:
```php
class AbsolutePathResolver extends WebPathResolver
{

    public function __construct(Filesystem $fileSystem, $webRootDir, $cachePrefix = 'media/cache')
    {
        parent::__construct($fileSystem, new RequestContext(), $webRootDir, $cachePrefix);
    }

    public function resolve($path, $filter)
    {
        return $this->getFilePath($path, $filter);
    }

}
```
With the resolver above we only get the absolute path when a thumbnail is already generated. Thumbnail creation can only be triggered through a controller action. In order to achieve that I created a custom Twig extension which first call the controller action and then returned the absolute path.
```php
class AbsolutePathExtension extends Twig_Extension
{
    private $imagineController;

    private $cacheManager;

    public function __construct(ImagineController $imagineController, CacheManager $cacheManager)
    {
        $this->imagineController = $imagineController;
        $this->cacheManager = $cacheManager;
    }

    public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter('imagine_absolute_path_filter', array($this, 'filter')),
        );
    }

    public function filter($path, $filter, array $runtimeConfig = array(), $resolver = null)
    {
        $this->imagineController->filterAction(new Request(), $path, $filter);

        return $this->cacheManager->getBrowserPath($path, $filter, $runtimeConfig, $resolver);
    }

    public function getName()
    {
        return 'app_extension';
    }
}
```
The request is not important in this case and could be omitted. I know it is really hacky but I don't find another workaround. If anybody come up with a nicer solution let me know ✌️

**Comment by scottgutman** [comment]
This is what I did to create a thumbnail and return the full filename with path:

```
	public function makeThumbNail( $fileName ) {
		$filenameParts = pathinfo( $fileName );
		$filter        = 'thumbnails';

		$dataManager   = $this->container->get( 'liip_imagine.data.manager' );
		$filterManager = $this->container->get( 'liip_imagine.filter.manager' );

		$image = $dataManager->find( $filter, $filenameParts['basename'] );
		$image = $filterManager->applyFilter( $image, $filter );

		/** @var CacheManager */
		$imagineCacheManager = $this->container->get( 'liip_imagine.cache.manager' );
		$imagineCacheManager->store( $image, $filenameParts['basename'], $filter, 'local_storage' );

		$url = $imagineCacheManager->resolve( $filenameParts['basename'], $filter );

		return $filenameParts['dirname'] . parse_url($url, PHP_URL_PATH);
	}
```

**Comment by michellesanver** [comment]
Not very elegant but it seems like this is somewhat solved, if you want to work on or really need/want that feature, please open a new issue as I am cleaning out old issues to have a clear workable issue tracker! Thanks a lot :)
