### ISSUE TITLE
How i can get result image size

### ISSUE THREAD

**Issue by Neokortex** [liip/LiipImagineBundle#575]
path to resized image:
```php
$resolve = $cacheManager->resolve($imagePath, $filter);
```
How i can get result image size (width and height)? it can?
example:
```php
$imageSize = $cacheManager->getSize($imagePath, $filter);
```

**Comment by makasim** [comment]
No you cannot do it with cache manager, but you can try to use imagine library directly (there is a service imagine with its instance). From that service you can create an Image instance.

**Comment by Neokortex** [comment]
Thanks, but this information will not be cached. Therefore it is necessary to solve this problem, yes?
