### ISSUE TITLE
Wrong generated URL for images

### ISSUE THREAD

**Issue by yuriricci** [liip/LiipImagineBundle#576]
I'm moving from localhost to a remote server in which, to be more clear, the hostname part - localhost - has been replaced by -ip-address-/~siteid/ since I didn't transfer the domain yet on a shared hosting setting. The remaining details are the same in both environments. Locally the generated path is ok, while remotely the  /~siteid/ URL piece is inserted after the media/cache (and it should not be there) leading to erroneous URL ..media/cache/~siteid/...   I don't know how to adjust such a thing..

**Comment by makasim** [comment]
It is not the bundle issue, there is a rewrite rule for apache or a listener that modifies urls or something like that. try to debug your app.
