### ISSUE TITLE
AppKernel.php error

### ISSUE THREAD

**Issue by MiguelAdige** [liip/LiipImagineBundle#578]
Hello, excuse my broken English.
I tried to install "LiipImagineBundle" but I get this error without being able to solve:

ClassNotFoundException in AppKernel.php line 26:
Attempted to load class "LiipImagineBundle" from namespace "Liip\ImagineBundle".
Did you forget a "use" statement for another namespace?

here is my AppKernel.php file

```
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = array(
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new ULV4\UserBundle\UserBundle(),
            new ULV4\PostBundle\PostBundle(),
            new ULV4\SiteBundle\SiteBundle(),
            new ULV4\CommentBundle\CommentBundle(),
            new ULV4\AdminBundle\AdminBundle(),
            new ULV4\SlugBundle\SlugBundle(),
            new ULV4\VideoStreamBundle\VideoStreamBundle(),
            new Liip\ImagineBundle\LiipImagineBundle(),
        );

        if (in_array($this->getEnvironment(), array('dev', 'test'))) {
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
        }

        return $bundles;
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load(__DIR__.'/config/config_'.$this->getEnvironment().'.yml');
    }
}

**Comment by makasim** [comment]
how did you install this, did you use a composer?

**Comment by cheikh321** [comment]
Attempted to load class "LiipImagineBundle" from namespace "Liip\ImagineBundle". Did you forget a "use" statement for another namespace?

**Comment by cheikh321** [comment]
Hello i have the same problem when i install liip imagine bundle: Attempted to load class "LiipImagineBundle" from namespace "Liip\ImagineBundle". Did you forget a "use" statement for another namespace?

**Comment by fabirus** [comment]
Hello i have the same problem when i install liip imagine bundle: Attempted to load class "LiipImagineBundle" from namespace "Liip\ImagineBundle". Did you forget a "use" statement for another namespace?

**Comment by khadimniass** [comment]
Hello teams i've this error: ''Attempted to load class "LiipImagineBundle" from namespace "Liip\ImagineBundle".
Did you forget a "use" statement for another namespace?''
 Do you have a solution for me ?
