### ISSUE TITLE
JpegOptimPostProcessor options

### ISSUE THREAD

**Issue by HitoTech** [liip/LiipImagineBundle#589]
When I use the JpegOptimPostProcessor in my project, it work just fine.

But when I'm trying to give a "max" option to the post-processor, it never takes it.

```
post_processors:
      jpegoptim: { max: 90 }
```

I see that the FilterManager call the process function of the post-processor, but the `$postProcessorOptions` never seems to be used.

Am I doing it the wrong way or should the FilterManager give option to the post-processor ?

**Comment by franmomu** [comment]
Same here, based on JpegOptimPostProcessor code, something like this could be done:

```php
public function applyPostProcessors(BinaryInterface $binary, $config)
{
    $config += array('post_processors' => array());
    
    foreach ($config['post_processors'] as $postProcessorName => $postProcessorOptions) {
        if (!isset($this->postProcessors[$postProcessorName])) {
            throw new \InvalidArgumentException(sprintf(
                'Could not find post processor "%s"', $postProcessorName
            ));
        }

        $postProcessor = $this->postProcessors[$postProcessorName];

        $this->updatePostProcessorOptions($postProcessor, $postProcessorOptions);

        $binary = $postProcessor->process($binary);
    }

    return $binary;
}

private function updatePostProcessorOptions($postProcessor, $options)
{
    foreach ($options as $name => $value) {
        if (method_exists($postProcessor, $setter = 'set'.ucfirst($name))) {
            return $postProcessor->$setter($value);
        }
    }
}
```

**Comment by franmomu** [comment]
This can be closed as it's already possible: https://symfony.com/doc/current/bundles/LiipImagineBundle/post-processors/jpeg-optim.html

**Comment by michellesanver** [comment]
Closing this based on @franmomu's comment above :) Thanks a lot!
