### ISSUE TITLE
picture in cache without filter

### ISSUE THREAD

**Issue by strauss69400** [liip/LiipImagineBundle#593]
i would like to know if it is possible to put a picture in cache(folder media) but without apply a filter, in keeping the original picture?

thanks

**Comment by makasim** [comment]
Have you tried do not configure filters at all, leave them empty. In this case it should apply nothing and you get same picture as origin in cache.

The other way: To manually call data loader and cache resolver methods, avoiding filter manager ones.

**Comment by strauss69400** [comment]
ok thank you very much.but if in this case, it is useful to put the pictures in cache?

**Comment by makasim** [comment]
I dont see much sense in it, but it is possible to do.
