### ISSUE TITLE
Use the bundle in CSS?

### ISSUE THREAD

**Issue by lukey78** [liip/LiipImagineBundle#597]
Hi there,

I wonder if there's a way to use the bundle's dynamically cached image url generation in stylesheets (for background-image).

Any hints on how this could be accomplished?

Thanks,
Jens

**Comment by lsmith77** [comment]
using this Bundle basically means 2 things:
1) generating URLs pointing to the cache
2) generating thumbnails if they have not yet been cached

for 1) you will need to use PHP or Twig to generate your CSS files. but you can of course also handcode the necessary urls.

for 2) this should work just fine regardless of where the files are referenced (HTML, CSS etc).

**Comment by lukey78** [comment]
Understood. Thx!
