### ISSUE TITLE
symfony 2.7 wrong path

### ISSUE THREAD

**Issue by joe936** [liip/LiipImagineBundle#606]
Hello,

I have been using this bundle successfully for around 3 years now, never had a problem. But when I upgrade my projects to symfony 2.7 (from symfony 2.6 or symfony 2.5) none of the images appear anymore, and the path in twig resolves to a wrong path. Not sure if it is a bug or something I missed, please help. I need to move to symfony 2.7 since it is LTS.

**Comment by lsmith77** [comment]
can you give a bit more context about your code, config and result?

@stof do you maybe have a hint here?

**Comment by stof** [comment]
Well, not without more information about what happens

**Comment by joe936** [comment]
It's very straightforward and simple twig usage 
       <img src="{{ asset(employee.path ~ employee.photo)|imagine_filter('people')}}"/>

where employee.path equals to '/uploads/employee/"' and employee.photo is a jpg file name

It works in all symfony <2.7, with symfony 2.7 the path repeats itself, instead of getting 

http://localhost:2223/site/web/app_dev.php/media/cache/resolve/people/uploads/employee/986850employee2.jpeg
I get 
http://localhost:2223/site/web/app_dev.php/media/cache/resolve/people/site/web/uploads/employee/986850employee2.jpeg

And all I changed was the symfony version from 2.6 to 2.7 in composer.I am using liip dev-master

Thank you.

**Comment by stof** [comment]
@lsmith77 please edit the comment to fix the markup

**Comment by dextervip** [comment]
I have got the same issue. I have upgraded to symfony 2.7 and all images disappears. The source image path can't be found anymore.

**Comment by joe936** [comment]
Any updates?

**Comment by jcurlier** [comment]
same here...

**Comment by lsmith77** [comment]
i anyone able to build a failing test case for this? would help to try and find a fix ..

**Comment by makasim** [comment]
You could do it here https://github.com/makasim/LiipImagineBundleSandbox. Though you have to upgrade the sandbox first.

**Comment by pjam** [comment]
Anyone has a clue on this? I don't know about pre sf2.7 because I just installed liip, but I'm having this problem.

It seems that symfony doesn't like images outside bundles, like in web/test_images. When the page loads, the image is there but with css to hide and not display it. With images living in bundles there's no problem.

Anyone can explain that?

**Comment by joe936** [comment]
Okay, sorry I took this long. Here is a scenario where it does not work on symfony 2.7

https://github.com/joe936/test

if you switch symfony to 2.6 in composer and run composer update again, it will work. Without changing any of the code. I will work on putting it online somewhere.

**Comment by makasim** [comment]
One of my college is working on symfony2.7 project + this bundle 1.0.6 version. He tells it works fine. 

Could you check the problem gone if you downgrade the bundle to that version?

**Comment by trsteel88** [comment]
I'm using 2.7 without issue.

**Comment by trsteel88** [comment]
Also, some of your other dependencies are different to the 2.7 standard. You should try updating the other dependencies to match first. 

https://github.com/symfony/symfony-standard/blob/v2.7.3/composer.json

**Comment by Dannebicque** [comment]
Hi,

For me, that does not work with Symfony 2.7. I have the same issue. I have the dependencies like trsteel88 expected sensio/distribution-bundle, i have an older version.

**Comment by Dannebicque** [comment]
I obtain this path for my picture: /uploads/img/dossier/http://127.0.0.1:8081/projet/web/app_dev.php/media/cache/resolve/avatar/image.jpg

In first the path in web, and then the url ...

**Comment by joe936** [comment]
I updated the dependencies, still it does not work
