### ISSUE TITLE
Upgrading symfony to 2.7 displays warning 

### ISSUE THREAD

**Issue by vishalmelmatti** [liip/LiipImagineBundle#607]
PHP Deprecated:  Symfony\Component\DependencyInjection\Definition::setFactoryClass(Aws\S3\S3Client) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. in /var/www/st/symfony-website/Symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Definition.php on line 101

**Comment by makasim** [comment]
there is a PR for that: https://github.com/liip/LiipImagineBundle/pull/566
