### ISSUE TITLE
[configuration] "route" key present in documentation but not in Configuration?

### ISSUE THREAD

**Issue by inmarelibero** [liip/LiipImagineBundle#609]
I found the key `route` here: [http://symfony.com/doc/master/bundles/LiipImagineBundle/configuration.html](http://symfony.com/doc/master/bundles/LiipImagineBundle/configuration.html) and here [https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/configuration.rst](https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/configuration.rst)

with the description:

```
route - optional list of route requirements, defaults and options using in the route loader. Add array with keys
```

but I if try to set that option, it gives `Unrecognized option "route" under "[...]"` because, looking at [Configuration.php](https://github.com/liip/LiipImagineBundle/blob/6fd9dd18c22a6de68c979d54baee62e537af44db/DependencyInjection/Configuration.php), this config is not present.

```
[...]
->arrayNode('filter_sets')
                    ->useAttributeAsKey('name')
                    ->prototype('array')
                        ->fixXmlConfig('filter', 'filters')
                        ->children()
                            ->scalarNode('quality')->defaultValue(100)->end()
                            ->scalarNode('jpeg_quality')->defaultNull()->end()
                            ->scalarNode('png_compression_level')->defaultNull()->end()
                            ->scalarNode('png_compression_filter')->defaultNull()->end()
                            ->scalarNode('format')->defaultNull()->end()
                            ->booleanNode('animated')->defaultFalse()->end()
                            ->scalarNode('cache')->defaultNull()->end()
                            ->scalarNode('data_loader')->defaultNull()->end()
                            ->scalarNode('default_image')->defaultNull()->end()
                            ->arrayNode('filters')
                                ->useAttributeAsKey('name')
                                ->prototype('array')
                                    ->useAttributeAsKey('name')
                                    ->prototype('variable')->end()
                                ->end()
                            ->end()
                            ->arrayNode('post_processors')
                                ->defaultValue(array())
                                ->useAttributeAsKey('name')
                                ->prototype('array')
                                    ->useAttributeAsKey('name')
                                    ->prototype('variable')->end()
                                ->end()
                        ->end()
                    ->end()
                ->end()
[...]
```

am I missing something or the doc diverges from the code?

**Comment by inmarelibero** [comment]
just to contextualize: my problem is that I'd like to generate `relative`, instead of absolute, urls for the thumbnails

**Comment by inmarelibero** [comment]
`route`parameter was removed here:

https://github.com/liip/LiipImagineBundle/commit/e69d87deab9a99e24d241b40cffbd9984dd7c20d
https://github.com/liip/LiipImagineBundle/commit/e3a28ed6c6624b1d4164cbc14cbf4883acabcd8b

**Comment by inmarelibero** [comment]
I report here a tweet by @makasim: 

```
Nope it is not possible to just configure, by design.
But you can do it with event listener which replace domain part
```

@makasim isn't choosing absolute/relative url not so requested by users? creating a listener just for this is not very handy, and this maybe this is a common situation.

the problem I have now is:
```
Mixed Content: The page at [...] was loaded over HTTPS,
but requested an insecure image
'[...]/media_cache/9999999999x160_outbound/uploads/event/55705d75425f0.jpg'.
This content should also be served over HTTPS.
```

and if I could do something like
```
// second parameter "false" means the url is not absolute
{[ vich_uploader_asset(event, 'imageMediumFile') | imagine_filter('160x160_outbound', false) }}
```

would be great. what do you think?

**Comment by makasim** [comment]
The main idea that you have to be able to get image by the url returned by ANY resolver. In case of relative url you cannot do it and has to first add the domain port and so on.

**Comment by makasim** [comment]
All other resolvers (remove ones like aws s3) always return absolute url so I'd consider filesystem resolver as a special case which just has to follow main rule.

**Comment by makasim** [comment]
The route is there because you can still able to change look of the absolute url.

**Comment by makasim** [comment]
> @makasim isn't choosing absolute/relative url not so requested by users? creating a listener just for this is not very handy, and this maybe this is a common situation.

I must admit it was requested several times, and as a solution the bundle can provide such listener and an option on the filesystem resolver factory. By default it is disabled and only when a developer knows who he does he can enable it. But the resolver in this case not consistent with others

**Comment by inmarelibero** [comment]
ok, I (almost) got the argumentation of the resolver.

what about enabling this choice only in the twig extension?
I quite agree with all your argumentations, and we could think about adding this feature at least only in [filter()](https://github.com/liip/LiipImagineBundle/blob/master/Templating/ImagineExtension.php#L43) twig function maybe

**Comment by makasim** [comment]
twig function could be used with other resolvers like aws s3 and what this addition would mean in that case?

**Comment by inmarelibero** [comment]
mm in this case I have to study better what you call `resolvers`..

I would say that the choice may be left to the developer: if I try to print a relative url from aws s3 it will print nothing, the error is mine in that case
