### ISSUE TITLE
Apply a filter depending on image size

### ISSUE THREAD

**Issue by picks44** [liip/LiipImagineBundle#617]
Is it possible to apply a custom filter depending on the original image size ? 

Like applying the "background filter" for images smaller than the requested size or the "crop filter" for images bigger than the requested size.

**Comment by makasim** [comment]
Yes it is possible, but you have to write your own filter with such logic, the filter delegates the job to other standard filters depending on what you need.

**Comment by trsteel88** [comment]
@picks44 relevant documentation is here: http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html#load-your-custom-filters

The ImageInterface inside the [load](https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/Loader/LoaderInterface.php#L17) method will allow you to check the size.

**Comment by picks44** [comment]
Yes thank you, I was looking into it. How to I "hook" to a standard filter within my custom filter ?

**Comment by picks44** [comment]
@trsteel88 @makasim Any help here ?
How can I call the Tumbnail filter within my custom filter (and pass it the image + options) ?
Thanks.

**Comment by trsteel88** [comment]
You don't need to call it. Configure a filter set in your config.yml. First
call thumbnail, then call your custom filter. You can call as many as you
want. Each loaded will be given the ImageInterface with the current state
of the image.
>
>
