### ISSUE TITLE
Old Router ->generate() syntax

### ISSUE THREAD

**Issue by cadavre** [liip/LiipImagineBundle#624]
Imagine is not updated to current Router `->generate()` method:
https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/CacheManager.php#L167
Third argument is not boolean anymore.
It's since 2.2 (three years ago):
https://github.com/symfony/symfony/blob/2.2/src/Symfony/Component/Routing/Router.php#L205

**Comment by makasim** [comment]
The [docblock](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Routing/Generator/UrlGeneratorInterface.php#L76) says that a bool valid case.
