### ISSUE TITLE
imagine_filter() twig function output an absolute URL

### ISSUE THREAD

**Issue by bbeaulant** [liip/LiipImagineBundle#625]
Hi,

Previously, my project uses [Avalanche123/AvalancheImagineBundle](https://github.com/avalanche123/AvalancheImagineBundle) where the *imagine_filter()* was *apply_filter()*. 
The old *apply_filter()* function outputs by default a relative path of the cached image. That was a good option for me because I used this bundle in CLI too. And **absolute URL** generated from CLI starts with http://localhost. That's not what I want.

Then my question is : Is there a way to outputs a relative path with *imagine_filter()* function from a twig template ?

**Comment by makasim** [comment]
> Then my question is : Is there a way to outputs a relative path with imagine_filter() function from a twig template ?

The absolute is returned on purpose to keep resolvers consistent.  Relative url is an edge case. 

There is not easy way to enable relative urls. You can try to add a post resolve listener which convert absolute url to relative.

> And absolute URL generated from CLI starts with http://localhost. That's not what I want.

You can configure router context parameters host,port etc to get correct absolute url.

**Comment by bbeaulant** [comment]
Thanks for the quick answer @makasim !

You're right I can solve my problem by configuring the router context in my app parameters.

```yaml
parameters:
    router.request_context.host: mywebsite.com
```

**Comment by mitrae** [comment]
@makasim because `imagine_filter` returns absolute url it is not possible to wrap result into `asset`
so `framework.assets.base_urls: ['http://cdn.example.com', 'http://cdn2.example.com']` is ignored

**Comment by makasim** [comment]
@mitrae you can do achieve it while configuring the resolver

**Comment by johnecon** [comment]
As @makasim suggested, 

> You can try to add a post resolve listener which convert absolute url to relative.

 The code below, might turn useful to someone using a simpler cdn like keycdn:

My _EventListener/CacheResolveListener_:
```php
<?php
namespace AppBundle\EventListener;

use Liip\ImagineBundle\Events\CacheResolveEvent;

class CacheResolveListener
{
    function onLiipimaginePostresolve(CacheResolveEvent $e)
    {
        $e->setUrl(parse_url($e->getUrl())['path']);
    }
}
```

My _config/services.yml_:
```yml
...
  app.event_listener.post_cache_resolver:
      class: AppBundle\EventListener\CacheResolveListener
      tags:
          - { name: kernel.event_listener, event: liip_imagine.post_resolve }
...
```
Then in twig I use it as:
```twig
{% set assetPackage = 'keycdn' %}
{{ asset('assets/media/logo.png' | imagine_filter('thumb'), assetPackage) }}
```
