### ISSUE TITLE
Memory leak inside the FilterManager

### ISSUE THREAD

**Issue by cmodijk** [liip/LiipImagineBundle#633]
I'm currently debugging a memory leak we have inside of our application. We have a long running php script which generates video's from a serie of images and we are using the LiipImageBundle to convert al the images to the correct sizes before we start generating the video using ffmpeg. We use Imagick to covert the images. After looking into this problem I found a [bug report](https://bugs.php.net/bug.php?id=59878) at PHP and I upgraded to the latest version's of Imagick (3.3.0RC2) and ImageMagick (ImageMagick 6.9.2-0) but the problem still remains. 

After a debugging session this evening i found that the https://github.com/avalanche123/Imagine/ library has implemented a [```__destruct```](https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Imagick/Image.php#L82-L88) method but this method is only getting called after the script ended. But in our long running situation this never happens. 

I tried adding a ```unset($image)``` inside the [apply](https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/FilterManager.php#L92) method but that does not help destructing the object and destructing imagick to free the memory used. I just added a call to ```$image->__destruct();``` and that does the trick to free memory. 

I'm not sure if this is something to be implemented inside this bundle or if we should implement it ourself with a custom FilterManager.

**Comment by lsmith77** [comment]
related to this see http://paul-m-jones.com/archives/262

**Comment by cmodijk** [comment]
@lsmith77 Tnx great artikel! We currently are not using LiipImagineBundle any more and implement our own filters using https://github.com/avalanche123/Imagine with the custom `__destruct` methods. I'm closing this because it's not an issue for us anymore.
