### ISSUE TITLE
Access Bundle Functions from Controller

### ISSUE THREAD

**Issue by Critical-Impact** [liip/LiipImagineBundle#64]
Hi I was wondering if it was possible to access the functions of this bundle from other parts of the application instead of just twig templates?
I don't know if it's already possible or not, but if it is could someone write up a quick tutorial?

I have actually been able to create my own service that brings in the cachemanager and uses the same filter function as the twig helper but for some reason it never actually saves the image I input into the cache. I can see it returns a file path and it works normally in a twig template but it doesn't work inside the controller.

Main reason I need this is that I'm uploading files using SWF and I need to generate a file path and also a thumbnail path so I figured I'd hit two birds with one stone and use the same generation profile for returning the thumbnail url via JSON and also on the template.

Any thoughts?

**Comment by ragsnas** [comment]
@ed-lea : The new Request didn't work for me. It seems it is missing parameters.

I can't use the current Request thou since i am trying to integrate this into a listener that only has access to a AJAX Request wich doesn't work either.
