### ISSUE TITLE
bundle doesn't save cached images on shared hosting

### ISSUE THREAD

**Issue by NadjibBELLOUNDJA** [liip/LiipImagineBundle#642]
Hi everybody. I have installed Liip Imagine Bundle on my local server and it works fine. My images are saved in the web/images/ repository and below there is my app/config/config.yml

liip_imagine:
    filter_sets:
        my_thumb_profile_big:
            quality: 75
            filters:
                thumbnail: { size: [155, 155], mode: inset}
        my_thumb_profile_small:
            quality: 75
            filters:
                thumbnail: { size: [27, 27], mode: inset}

and my app/config/routing.yml

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

The bundle works fine in my local host and generates cached images in the folder web/media/cache/my_thumb_profile_big

But when I uploaded all my files on my shared hosting server, the generation of cached images doesn't work anymore. And the src of all my images is no longer "http://localhost/media/cache/my_thumb_profile_big/images/name.png" but 
"http://subdomain.domain.com/Application/web/app_dev.php/media/cache/**resolve**/my_thumb_profile_big/Application/web/images/unkown-155x155.png" instead.
I use a subdomain for my website.

What is the issuer? Why is the bundle not able to resolve anymore? If I run the command on my terminal wirh the command php-cli app/console liip:imagine:cache:resolve path/to/image, the cached image is generated. But I keep getting the wrong path on my browser.

Thanks for your help.

**Comment by makasim** [comment]
Why do you think the path is wrong? It is expected to have `resolve` in the url for the first time.

**Comment by trsteel88** [comment]
Also, make sure you aren't using the asset filter when printing the image path. This has caused issues in the past for other people. 

What does your twig/html look like?

**Comment by NadjibBELLOUNDJA** [comment]
Hi @trsteel88

It worked man, thanks a lot. I was using the asset filter. I removed it and then it worked perfectly.

Do you know what is the reason of this? How come using the asset filter causes issues?

**Comment by trsteel88** [comment]
No worries. The asset filter will rewrite the path to a relative path which this bundle can't handle unfortunately.

**Comment by lsmith77** [comment]
closing this issue .. please reopen if I misunderstood ..
