### ISSUE TITLE
Stand alone feature

### ISSUE THREAD

**Issue by INHack20** [liip/LiipImagineBundle#643]
This library is very good, I want to use in a project that is developed in yii2 in the future could consider eliminating dependencies framework and can be used on a stand alone such as:
https://github.com/KnpLabs/KnpMenu (php independent use.)
KnpLabs / KnpMenuBundle (Bridge Liberia with Symfony2)

Esta librería es muy buena, quisiera utilizarla en un proyecto que esta desarrollado en yii2, en un futuro podrian considerar eliminar dependencias del framework y pueda ser usada de forma stand alone como por ejemplo:
https://github.com/KnpLabs/KnpMenu (php uso independiente.)
KnpLabs/KnpMenuBundle (Puente de liberia con symfony2)

Thanks.
Gracias.

**Comment by makasim** [comment]
The bundle is coupled to symfony's container and request\response. How do you think this could be decoupled?

**Comment by INHack20** [comment]
You're right, I'm reviewing and components as the "Router", "Container", "Request", "EventDispatcher" Symfony2 used ...
With your permission I will reuse the logic of various class to facilitate my work.
Thank you.

Tiene razón, estoy revisando y se usan componentes como el "Router","Container","Request","EventDispatcher" de symfony2...
Con su permiso voy a reutilizar la logica de varias class para facilitar mi trabajo. 
Gracias.

**Comment by makasim** [comment]
> With your permission I will reuse the logic of various class to facilitate my work.
yes, go ahead

@lsmith77  the bundle miss LICENSE file. What it should be?

**Comment by INHack20** [comment]
Hello please check the link, have separate logic and remain functional, single component requires "symfony / http-foundation" and can be used independently in applications with php, is minimal settings, please check and the future could make refactoring of LiipImagineBundle and create LiipImagineLibrary or LiipImagineService as basis for LiipImagineBundle library.

It's working in my application and manages the cache and filters perfectly, I think if they could separate the base component, I created some Interfaces and minimal changes in the code.

Thank you.


https://github.com/Tecnocreaciones/ImagineService
"require": {
	"php": ">=5.3.3",
        "imagine/imagine": "~0.5,<0.7",
        "symfony/http-foundation": "~2.3 || ~3.0"
    },


In spanish:
Hola por favor revisa el link, he separado la lógica y quedo funcional, solo requiere del componente de "symfony/http-foundation" y se puede usar de forma independiente en las aplicaciones con php, la configuración es mínima, por favor revisa y en un futuro podrían hacer un refactor de LiipImagineBundle y crear LiipImagineLibrary or LiipImagineService como librería base para LiipImagineBundle.

Esta funcionando en mi aplicacion y maneja la cache y filtros perfectamente, creo que si podrían separar la base del componente, he creado algunas interfazes y cambios mínimos en el código.

Gracias.

**Comment by makasim** [comment]
Crazy idea is to make a library coupled to psr7 interfaces + own interfaces for event dispatcher, router etc, and the bridge implementations for symfony.

**Comment by lsmith77** [comment]
BTW its MIT see https://github.com/liip/LiipImagineBundle/blob/master/Resources/meta/LICENSE

**Comment by lsmith77** [comment]
pulling code out of a framework specific repo into a generic repo is always welcome .. so generally I am very open to this!
