### ISSUE TITLE
imagine_filter not working with asset versioning strategy

### ISSUE THREAD

**Issue by svassaux** [liip/LiipImagineBundle#647]
When implementing the new feature of the asset component in symfony, ie versioning the assets, it ouputs a version number which then is not handled properly by the imagine_filter.

Please see the full details there : http://stackoverflow.com/questions/33200339/symfony-2-7-asset-component-not-working-with-imagine-filter

The following does not work when I activate asset versioning
img src="{{ asset('images/user.png') | imagine_filter('default') }}" alt="Image de profil" class="img-circle whitebg"

Is there something to correct or I am doing something wrong ?

**Comment by makasim** [comment]
You should first apply imagine_filter filter and than call asset function, https://github.com/symfony/symfony/issues/12474#issuecomment-64130839
