### ISSUE TITLE
protocol relative function for Liip\ImagineBundle\Imagine\Cache\Resolver\ProxyResolver::rewriteUrl

### ISSUE THREAD

**Issue by kcassam** [liip/LiipImagineBundle#661]
A better [rewriteUrl](https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/Resolver/ProxyResolver.php#L73)   that returns a proxy url with same scheme (http/https) as input url.

```
// A better rewriteUrl that returns a proxy url with same scheme (http/https) as input url
protected function rewriteUrl($url)
{

    if (empty($this->hosts)) {
        return $url;
    }

    // What is the scheme of the URL
    $scheme = parse_url($url, PHP_URL_SCHEME);

    // We make a hosts array of all proxies with same scheme as the input url
    $hosts = array();
    foreach ($this->hosts as $host) {
        if ($scheme == parse_url($host, PHP_URL_SCHEME)) {
            $hosts[] = $host;
        }
    }

    // If no proxy with same scheme as the input url, we simply return the input url
    if (empty($hosts)) {
        return $url;
    }

    // If at least one proxy with same scheme as the input url, we randomly choose a proxy
    $host = parse_url($url, PHP_URL_SCHEME).'://'.parse_url($url, PHP_URL_HOST);
    $proxyHost = $hosts[rand(0, count($hosts) - 1)];
    return str_replace($host, $proxyHost, $url);
}
```

With this code : 
- if url scheme is https, we should only use https proxy
- if url scheme is http, we should only use http proxy

The question I ask myself is that maybe if url scheme is http, we should accept http or https proxy ?

**Comment by caramba1337** [comment]
+1

**Comment by makasim** [comment]
You can just set `//foo.host` as proxy host and a browser will use same scheme as the site has

**Comment by kcassam** [comment]
the https proxy is not always the same as the http proxy

**Comment by michellesanver** [comment]
@kcassam I am going through all issues to sort and prioritise. Since this is so old, before we investigate further: Is this still an issue for you? Thanks a lot! :)

**Comment by dbu** [comment]
if symfony is set up correctly to trust the reverse proxy, hostname and https vs http are set correctly https://symfony.com/doc/current/deployment/proxies.html
