### ISSUE TITLE
unset filter at runtime 

### ISSUE THREAD

**Issue by kcassam** [liip/LiipImagineBundle#662]
I have a filter configured as follow : 

        photo_mail:
            data_loader:    stream.shooting
            quality:        100
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

I would like to be able to unset the thumbnail filter at runtime, but it seems I can't.

The code would be as follow : 

    {% set runtimeConfig = {"thumbnail": {}} %}
    <img src="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb', runtimeConfig) }}" />

**Comment by makasim** [comment]
No you cannot do it.
