### ISSUE TITLE
"Source not found" error does not say which path is causing it

### ISSUE THREAD

**Issue by sirgallifrey** [liip/LiipImagineBundle#663]
"Source not found" error does not say which path is causing it, which makes it very difficult to debug the error.

On ImagineController.php line 91 we got: 
```php
throw new NotFoundHttpException('Source image could not be found', $e);
```
i have changed it to: 
```php
throw new NotFoundHttpException($e->getMessage(), $e); 
```
And it solves my problem

**Comment by makasim** [comment]
symfony prints the message of previous exception, and if you use something like sentry it shows it too.

What is your usecase?
