### ISSUE TITLE
1.3.1 Could not find filter loader for "downscale" filter type

### ISSUE THREAD

**Issue by iBasit** [liip/LiipImagineBundle#665]
I have installed latest version and using downscale filter gives me following messages

"Could not find filter loader for "downscale" filter type"

**Comment by RicardoSantosDiaz** [comment]
Any solution to this?

**Comment by RicardoSantosDiaz** [comment]
Changing to dev-master solved the issue

**Comment by javiereguiluz** [comment]
Same here:

![liipimaginebundle_error](https://cloud.githubusercontent.com/assets/73419/11776477/c183ebbc-a247-11e5-89da-d589584c11cd.png)

Any plans to release a new version soon or should we add some warnings in the documentation? Thanks.

**Comment by makasim** [comment]
[1.3.2](https://github.com/liip/LiipImagineBundle/tree/1.3.2) was released 4 four days ago. Most likely it contains the fix. Could you please check ?

**Comment by javiereguiluz** [comment]
@makasim 1.3.2 version fixed the problem for me. Thanks!
