### ISSUE TITLE
Problems with new symgony 2.8 autoloader and Appkernel.php

### ISSUE THREAD

**Issue by micronax** [liip/LiipImagineBundle#670]
When using the new symfony 2.8 autoloading feature symfony introduced by the SesionDistributionBundle v5 throws the following error:

`Fatal error: Cannot redeclare class AppKernel in /vagrant/vendor/liip/imagine-bundle/Liip/ImagineBundle/Tests/Functional/app/AppKernel.php on line 45`

I think this is caused by a missing namespace in the AppKernel.php included in this bundle.

**Comment by lsmith77** [comment]
can you try to create a PR for this?

**Comment by makasim** [comment]
fix is in master
