### ISSUE TITLE
Generate thumb only by calling the url

### ISSUE THREAD

**Issue by hotgeart** [liip/LiipImagineBundle#671]
Hi,

I'm making an app mobile for my symfony app. But i'm stuck, when an user request a photo that has not already a generated thumb.

There's a solution for that ? Like a "magic" controller to do something like that:

> img src="domain.com/route/?img=path/img.jpg&filter=thumb"

Thank you

**Comment by makasim** [comment]
There is a controller which generates cached images on the fly. Once it does the it it redirects you to cached image directly. Next time you have to use this redirection url.
