### ISSUE TITLE
Get rid of /resolve/ part - is it possible?

### ISSUE THREAD

**Issue by kiler129** [liip/LiipImagineBundle#675]
In default configuration Liip generates two kind of URLs:
  * https://domain.tldl/media/cache/resolve/image.jpg
  * https://domain.tld/media/cache/avatar.jpg

First one is generated when filtered image does not exists, second one when image exists on e.g. local harddrive.
Is it possible to configure Liip to always generate second type URL? Use case for that is simple - some pages gets cached as static HTMLs. If some (or all) images has not been processed yet HTML is populated with `/resolve/` urls which later causes massive amount of HTTP requests (while all of them are just HTTP/301 to second URL).

**Comment by makasim** [comment]
It is possible (by overwriting the filter route) but you will face issues in Safari. Safari does not understand 301 redirect to the same url

**Comment by kiler129** [comment]
Details about the issue: https://github.com/liip/LiipImagineBundle/issues/478
Possible solution for local files: .htaccess entry ;)
