### ISSUE TITLE
Filename "mačací obrázok.jpeg" causes installation fails on Windows platform

### ISSUE THREAD

**Issue by tamcy** [liip/LiipImagineBundle#678]
Hi,

Windows still sucks at dealing with non ASCII filenames in command line. Composer fails to install the latest package on my system because of the file `LiipImagineBundle/Tests/Functional/app/web/images/mačací obrázok.jpeg` added 
since rev 4598c42. 

```
ZipArchive::extractTo([project_dir]/vendor/composer/d515cd58/liip-LiipImagineBundle-c2dfddf\Tests\Functional\app\web\images/ma?ac穩 obr獺zok.jpeg): failed to open stream: Invalid argument
```

How about changing it to plain alphabet? Thanks :)

**Comment by makasim** [comment]
Yes, sounds legit. Could you work on a patch?

**Comment by tamcy** [comment]
Sorry that I didn't go through the commit when i reported this issue. It turns out that the commit is about handling filenames with special characters, and the offending file is used as a test case. So removing those characters basically spoils its use, which is a problem.

**Comment by makasim** [comment]
I think we have to drop the test, or rewrite it. It is more important to make the bundle work on windows.

**Comment by makasim** [comment]
fix is in master
