### ISSUE TITLE
[RFC] PHP5.5 and Symfony 2.8 as lower supported versions

### ISSUE THREAD

**Issue by makasim** [liip/LiipImagineBundle#679]

**Comment by graundas** [comment]
I would agree with a drop of PHP 5.3 support, because It is quite old version of PHP. For example, Flysystem (https://github.com/thephpleague/flysystem), which support I have added to LiipImagine bundle, does not support PHP 5.3 anymore.

**Comment by lsmith77** [comment]
I am fine with dropping 5.3.

As for dropping Symfony 2.3 .. maybe we should do this in a new major version and use this opportunity to clean up some aspects of the Bundle.

**Comment by makasim** [comment]
close in favor https://github.com/liip/LiipImagineBundle/issues/686
