### ISSUE TITLE
chmod 600?

### ISSUE THREAD

**Issue by fmronan** [liip/LiipImagineBundle#702]
Hello
I have a problem when i generate my pictures, chmod is 600, is it possible to change that somewhere?

**Comment by makasim** [comment]
Why do you think it has to be changed. 600 means owner can read and write

**Comment by fmronan** [comment]
heuu no impossible to read with 600
![forbidden](https://cloud.githubusercontent.com/assets/1835167/12592352/592ce3a6-c46c-11e5-9dd9-8f24c51e4582.png)
![img600](https://cloud.githubusercontent.com/assets/1835167/12592379/7323d40e-c46c-11e5-8a91-f5b7b338f1fe.png)

**Comment by fmronan** [comment]
With one site I have 666 for my picture with symfony 2.7 but with symfony 3.0 600 so I don't understand, How can I change that, please?

**Comment by makasim** [comment]
I think there was a change in filysystem symfony's component.

**Comment by fmronan** [comment]
Yep ,hope you can make something for that?
thanks for your reply and sorry for my english

**Comment by fmronan** [comment]
I have made a test with symfony2.7 and symfony3 in the same web hosting, Work with 2.7 not 3, so the problem is symfony3 with your bundle
Sorry for my english

**Comment by bgatellier** [comment]
Hi,

This bug has been fixed in Sf 3.0.2, see https://github.com/symfony/symfony/pull/17063

**Comment by fmronan** [comment]
Ok, thank you.
Close
