### ISSUE TITLE
Background filter uses unexistent Color class

### ISSUE THREAD

**Issue by mangelsnc** [liip/LiipImagineBundle#703]
A few years ago, this bug was reported: https://github.com/liip/LiipImagineBundle/issues/449 and it was fixed in this commit: https://github.com/liip/LiipImagineBundle/commit/2e11afe4d114d434539a890944553e75611ea315

But five days ago I see that this bug seems to be reintroduced by this commit: https://github.com/liip/LiipImagineBundle/commit/e07cc0d0d60c921454b67ef77644d78a348c147e

This causes failing in some Imagine Library version, such as 0.6.

Is this correct?

**Comment by makasim** [comment]
No it is not, and the PR merged few days ago has to be reverted.

**Comment by makasim** [comment]
Or we have to stricter the version of imagine we rely on and use the recommended there way of manipulating with background.

**Comment by perk11** [comment]
Also affected by this.

**Comment by Gudabu** [comment]
Also here...

**Comment by makasim** [comment]
It is as simple as doing a git revert command on this commit https://github.com/liip/LiipImagineBundle/commit/417a2d594ea05f0cf963dfee94331a49a2c4e14e

**Comment by florianajir** [comment]
+1

**Comment by mangelsnc** [comment]
It's necessary to create a new PR fixing this?

I think @makasim is right, someone with permissions could revert the commit.

**Comment by makasim** [comment]
Everybody can do it.
