### ISSUE TITLE
JpegOptimPostProcessor problem with jpegoptim on linux OS

### ISSUE THREAD

**Issue by cyrilepinat** [liip/LiipImagineBundle#708]
Since  v1.5.0 of LiipImagineBundle, I get the following error for JPEG images : 
`Warning: file_get_contents(/tmp/imagine_jpegoptim2yUyal): failed to open stream: No such file or directory`

I'm facing the errors on LINUX OS, but not on MAC OS
No error occurs on LiipImagineBundle v1.4.*

Any thought about that ?

Thanks in advance

**Comment by makasim** [comment]
Do you have a problem on v1.5? Could this be related to https://github.com/liip/LiipImagineBundle/pull/707/files

**Comment by makasim** [comment]
Try 1.5.1 (I've just released it) and let me know if it works or not.

**Comment by cyrilepinat** [comment]
Yes it works perfectly with 1.5.1, thank you! :)
Have a great day!
