### ISSUE TITLE
Can't resize if the desired size is < to thumbnail size

### ISSUE THREAD

**Issue by marvin-SL** [liip/LiipImagineBundle#710]
Hello, 

I tried to resize an image with dynamic filter and it didn't work until i change my thumbnail size.
in my imagine.yml, if my thumbnail size is  `thumbnail: { size: [200, 200], mode: inset }`  and i try to do in my php
`...
    array(
        'filters' => array(
                'background' => array(
                    'size' => array(120,87)
                )
            ))
    ...
`

It doesn't work, and no error message is fired. 

It's quite weird that it works for some desired sizes under the thumbnail 's size, and doesnt work for some other sizes :
in imagine.yml `thumbnail: { size: [200, 200], mode: inset }` 

in php

```
...
array(
        'filters' => array(
                'background' => array(
                    'size' => array(160,80)   <-------- work
                )
            ))
...
```

---

```
...
array(
        'filters' => array(
                'background' => array(
                    'size' => array(150,80)   <-------- doesn't work
                )
            ))
...
```

version 1.5.2
symfony 2.7.5

**Comment by marvin-SL** [comment]
nobody ?

**Comment by abhinavkumar940** [comment]
https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/filters.rst#the-thumbnail-filter

Use the option `allow_upscale`

**Comment by marvin-SL** [comment]
Thanks but it doens't fix the issue.
I tried `thumbnail: { size: [200, 200],  allow_upscale : true }`

**Comment by JulienItard** [comment]
see @560

**Comment by JulienItard** [comment]
see #560

**Comment by michellesanver** [comment]
Closed; See https://github.com/liip/LiipImagineBundle/pull/1015
