### ISSUE TITLE
Errors handling large image files (lacking documentation)

### ISSUE THREAD

**Issue by camburns** [liip/LiipImagineBundle#711]
I've spent several hours today dealing with an error that's generated when processing large image files (> 4MB) within LiipImagineBundle. Unfortunately the runtime error produces no error or indication or where the error lies, however I discovered the issue had previously been discussed in this github issue (on the avalanche123/imagine repository):

https://github.com/avalanche123/Imagine/issues/206

However there is no suggestion on how to deal with the issue nor is there any documentation from LiipImagineBundle on how to process large image files. I've come to the conclusion that I should increase the PHP memory limit (and execution time of the controller) to allow processing of larger image files.

However, as the rendering of the derivative image only occurs via an asset URL route (i.e. a generate route such as: "http://localhost:8000/media/cache/resolve/my_thumb2/1.jpg") I cannot simply add:
ini_set('memory_limit', '1024M') to my application's controller as image rendering occurs via the asset URL route (mentioned above).

I've tried overriding the ImagineController:filterAction to include the memory increase line in the overridden LiipImagineBundle, however I don't know enough about overriding controllers and am stumped on this issue:

Catchable Fatal Error: Argument 1 passed to visageFour\Bundle\LiipImagineOverrideBundle\Controller\ImagineController::__construct() must be an instance of Liip\ImagineBundle\Imagine\Data\DataManager, none given, called in /Library/WebServer/Documents/anchorcards_app/app/cache/dev/classes.php on line 2214 and defined

So I'm taking an alternate route of forking the LiipImagine repo, adding the memory increase line and referencing this via composer (allowing me to effectively override the vendor library).

Issue:
- No out of the box solution for processing large images via LiipImagineBundle
- No clear documentation on how to increase memory when render large images

I suspect there will be others out there in a similar position so if you're able to advise on how we can improve documentation / solve the issue, that would be of great help. Hope this feedback is useful in some manner.

**Comment by makasim** [comment]
@Seldaek was able to process large files, (with some changes to the code) see https://github.com/liip/LiipImagineBundle/pull/705

I dont think the bundle should manage or increase memory limit, it must be set in your php.ini file. or you can increase it in the listener.

**Comment by MAXakaWIZARD** [comment]
@Seldaek Last stable release of https://github.com/avalanche123/Imagine was on 19 Sep 2015. As I got it, we need new stable release of imagine to be tagged or install it as `dev-master`.
