### ISSUE TITLE
Managing multiple loaders and Multiple Gaufrette Adapters

### ISSUE THREAD

**Issue by deviprsd** [liip/LiipImagineBundle#718]
As suggested by this comment, https://github.com/KnpLabs/Gaufrette/issues/332#issuecomment-199167214, how am I suppose to handle this? Have multiple filters all of them doing the same work but with each with a different data_loader? I plan to use local adapter.

**Comment by michellesanver** [comment]
Not sure if this is still an issue for you, but this sounds like something we could and probably should investigate and document.
