### ISSUE TITLE
Problem on php7 server

### ISSUE THREAD

**Issue by WarGot-by** [liip/LiipImagineBundle#719]
Good day. I need help -)
First of all, ignored the my config
```

 liip_imagine:
     resolvers:
         default:
             web_path:
                 web_root: %kernel.root_dir%/../web
                 cache_prefix: cache
     loaders:
         default:
             filesystem:
                 data_root: %kernel.root_dir%/../web/
     driver:               gd
     cache:                default
     data_loader:          default
     default_image:        null
     controller:
         filter_action:         liip_imagine.controller:filterAction
         filter_runtime_action: liip_imagine.controller:filterRuntimeAction
     filter_sets:
         shop_300:
             filters:
                 thumbnail:
                     size:               [300, 300]
                     mode:               inset
         shop_600:
             filters:
                 thumbnail:
                     size:               [600, 600]
                     mode:               inset
         shop_180:
             filters:
                 thumbnail:
                     size:               [180, 180]
                     mode:               inset`
```
 
`
In twig template I write

`<img src="{{ vich_uploader_asset(item, 'logoFile')|imagine_filter('shop_300') }}" class="img-rounded" alt="" /`
At frontend for image created link to
http://site.com/media/cache/resolve/shop_300/storage/shop/56f233f46d365.png
not http://site.com/cache/resolve/shop_300/storage/shop/56f233f46d365.png

media/cache and cache directory is empty

It may be lacking some extensions for php ?
```

extension=php_fileinfo.dll
extension=php_gd2.dll
extension=php_intl.dll
```

Cache directory in web/ it is symlink. Chown root:root, chmod 777

**Comment by WarGot-by** [comment]
On dev server with php 5.6 all works

**Comment by makasim** [comment]
what if you open this link `http://site.com/media/cache/resolve/shop_300/storage/shop/56f233f46d365.png`. what will be?

**Comment by WarGot-by** [comment]
> what if you open this link http://site.com/media/cache/resolve/shop_300/storage/shop/56f233f46d365.png. what will be?

404 not found. In routing.yml file I include liip image routing.xml at the beginning

**Comment by WarGot-by** [comment]
Console resolve command create thumbs correctly
php app/console liip:imagine:cache:resolve storage/shop/56f233f46d365.png
