### ISSUE TITLE
Resize and crop with cropping options

### ISSUE THREAD

**Issue by pulse00** [liip/LiipImagineBundle#72]
I've the following requirement in our app for image resizing and cropping:
1. If an image exceeeds a given dimension, resize it's smallest side to this dimension
2. Crop the resulting image, but with the option to specify the side on the image where to crop

So for example, when the maximum dimension is a rectangle with 250x250 (height/width) and the input image is
300x600, resize it to 250x498, and make it optional where to crop the resized image:
1. crop the left side
2. crop in the "middle" 
3. crop on the right

Is this possible with the current available filters?

If not, i'd be happy to send you a PR with this feature.

**Comment by michellesanver** [comment]
This is an issue from 2012, I thus assume it is no longer relevant. If it is, please open a new issue with details and we will look into that. Thanks a lot :)
