### ISSUE TITLE
Path Problems when imagename from variable

### ISSUE THREAD

**Issue by hegelx** [liip/LiipImagineBundle#724]
Hello,

I have some problems with paths and the liip imagine bundle. I' m using Symfony 2.8.4 and PHP 7.0.4.
I'm working with the vich/uploader Bundle. When I have this in my twig-File:

`<img src="{{ 'images/members/profile/570648e1ee813_olivier-messiaen.jpg'| imagine_filter('my_thumb')  }}" />`

ll works fine. The thumb is generated and the path is like this:

`http://example.com/web/media/cache/my_thumb/images/members/profile/570648e1ee813_olivier-messiaen.jpg`

But when I put the imagename in a variable, it doesn't work:

```
{% set foo = '570648e1ee813_olivier-messiaen.jpg' %}
<img src="{{ foo|imagine_filter('my_thumb')  }}
```

or

`<img src="{{ asset(foo)|imagine_filter('my_thumb') }}`

it doesn't work, no generating from the thumb and the path is always

`http://example.com/web/app_dev.php/media/cache/resolve/my_thumb/web/570648e1ee813_olivier-messiaen.jpg"`

My config.yml:

```
...
vich_uploader:
    db_driver: orm 

    mappings:
        member_image:
            uri_prefix:         /images/members/profile
            upload_destination: %kernel.root_dir%/../web/images/members/profile
            namer:              vich_uploader.namer_origname
        background_image:
            uri_prefix:         /images/members/backgrounds
            upload_destination: %kernel.root_dir%/../web/images/members/backgrounds
            namer:              vich_uploader.namer_origname

liip_imagine:
    resolvers:
       default:
          web_path: ~



    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
```

Any suggestions?

**Comment by danielforer** [comment]
Hi, Did you resolve this issue? If so, how? I am having the same problem. Thanks

**Comment by hegelx** [comment]
Hi Daniel,
I resolve the issue with the following steps:

First I wrote in the config/parameters.yml the following line with the path for the images:

```
parameters:
    image_member_profile: images/members/profile/
```
In the Controller I wrote the following lines:
```
public function indexAction(Request $request) {
	...
	$memberProfile = empty($user->getMemberImageName()) ? NULL : $this->container->getParameter('image_member_profile') . $user->getMemberImageName();
	return $this->render('member/index.html.twig', array(
                    'base_dir' => realpath($this->container->getParameter('kernel.root_dir') . '/..'),
                    'memberProfile' => $memberProfile,   
        ));
	}
```

And in the twig file I wrote:

`<img src="{{ memberProfile|imagine_filter('profile70') }}" alt="{{ app.user.firstName }} {{ app.user.lastName }}" />`

Hope this helps, Uwe

**Comment by michellesanver** [comment]
Seems like this issue is solved, thanks Uwe! :)
