### ISSUE TITLE
Downscale and Upscale are the same

### ISSUE THREAD

**Issue by trsteel88** [liip/LiipImagineBundle#728]
Has anyone noticed that DownscaleFilter and UpscaleFilter are exactly the same (with the exception of the rounding)?

https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/Loader/DownscaleFilterLoader.php
https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/Loader/UpscaleFilterLoader.php

I think something has gone wrong here. Also, if you use DownscaleFilter and set something large (e.g 1200x1200) and the original images if 400x400, it actually increases the size to 1200x1200. Shouldn't it stay at 400x400 because it's a Download (not an upscale)?

**Comment by michellesanver** [comment]
Looks weird, is this still an issue? Need to investigate :)

**Comment by franmomu** [comment]
I made an example in https://github.com/franmomu/liip-imagine-bundle-examples and it looks like it works. With an image of 400x400 if the downscale filter is set to 1200x1200 it does nothing and also if the upscale filter is set to 300x300 it does nothing. I guess the `isImageProcessable` method is the one who determines if should scale or not.
