### ISSUE TITLE
I just need Image Manipulation

### ISSUE THREAD

**Issue by JHGitty** [liip/LiipImagineBundle#730]
For my application I want to create thumbnail files and save them in my own storage system. I just like to create a thumbnail (resize, watermark) of my pictures.

- I don't need the twig features of LiipImagineBundle.
- I don't need the thumbnail storage features of LiipImagineBundle.
- I don't need the cache features because my thumbnails are persistent and will be automatically created again if the main file has been changed.

I also provide creation of thumbnails for videos and other things like manual upload of own thumbnail files. That because I don't want to integrate the default LiipImagineBundle thumbnail features.

**How can I just use image manipulation with LiipImagineBundle?**
**How can I disable all the features I don't need to increase performance?**

**Comment by makasim** [comment]
Use the Imagine library without the bundle

**Comment by JHGitty** [comment]
If somebody else is looking for an alternative: http://image.intervention.io/
