### ISSUE TITLE
LiipImagineBundle not found after composer update

### ISSUE THREAD

**Issue by DavidGarciaCat** [liip/LiipImagineBundle#734]
Hello,

I started to work in a Symfony project some months ago that is using this bundle (an old `dev-master` version) and after upload the `composer.json` file (to set the `^1.5` version) I am getting this error:

```
Fatal error: Class 'Liip\ImagineBundle\LiipImagineBundle' not found in app/AppKernel.php on line 27
```

Of course:
- My `composer.lock` file is up to date
- I have run the `composer dump-autoload` command to be sure the autoload file is up to date
- I have added the bundle into the AppKernel (that is the cause I am getting this error)
- I have added the routing configuration
- I have verified the `vendor/liip/imagine-bundle` folder exists (and has content)

I have noted the `Liip\\ImagineBundle\\` reference is just inside the `vendor/composer/autoload_psr4.php` file, but I am not sure if this bundle should be inside any other file and it is not there.

Do you know what can be causing this error? I would like to use this stable version instead of a non-updated `dev-master` if possible.

Thanks for your help,

**Comment by antoligy** [comment]
Hey, Sorry about the long TTL on this!

Is this still an issue?

**Comment by DavidGarciaCat** [comment]
hey @antoligy 

I have just checked this process again, but this time setting the `^1.6` version on my `composer.json` file. After run the `composer update liip/imagine-bundle --with-dependencies` command looks like all is loaded properly and the cached images generated by the bundle are working. I have double checked this process using a new image, and all is OK.

I presume the new 1.6 version is adding something that is fixing the error I had.

Thanks for your answer!

**Comment by antoligy** [comment]
No worries, glad you sorted it in the end! 😄
