### ISSUE TITLE
Can't clear cache for previously existing thumbs ?

### ISSUE THREAD

**Issue by jorismulliez** [liip/LiipImagineBundle#739]
Hi all,

I'm trying to use this bundle. It work fine for display.
But I can't figure how to clear specific Image cache correctly (without clear full cache).

I want to create a service like this one : stackoverflow.com/questions/27524336/update-and-remove-cached-image-using-liipimaginebundle#answer-28023595
But nothing work...

How can I remove the cache from the image I just replaced ?

Lets say I have some images entries : 
- image 1, with file 1.png, thumb/120x120/1.png, thumb/180x180/1.png
- image 2, with file 2.png, thumb/120x120/2.png, thumb/180x180/2.png

If I update image 1, I want thumb/120x120/1.png and thumb/180x180/1.png to be removed but not thumb/120x120/2.png and thumb/180x180/2.png

Is it clear ? (sorry for my poor english :/ )

Thanks in advance for your help...

**Comment by BartVB** [comment]
This is rather hard to answer, a lot depends on your configuration and the method you use to update images.

Did you manage to solve this problem in the meantime?

**Comment by michellesanver** [comment]
I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly. Thanks a lot! :)
