### ISSUE TITLE
image not appear (Source image could not be found)

### ISSUE THREAD

**Issue by essaghir-m** [liip/LiipImagineBundle#740]
hey this is my probleme
Source image not found in "C:\wamp\www\symfony3\app/../web/symfony3/web/images/uploads/5745ce2e628a9.png" 

and this my config.yml

`liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }`

**Comment by BartVB** [comment]
Did you manage to fix this in the meantime?
The above is a bit thin on details. 

How did you call Imagine? Does the stated file exist? And if it does exist, where is it?

**Comment by michellesanver** [comment]
@essaghir-m I am going through all issues to sort and prioritise. Is this still an issue for you? Since this is so old, please open a new issue if that is the case with answers to the questions from BartVB, and we will prioritise accordingly. Thanks a lot! :)
