### ISSUE TITLE
OptiPng postprocessor is slow

### ISSUE THREAD

**Issue by mitrae** [liip/LiipImagineBundle#744]
https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/PostProcessor/OptiPngPostProcessor.php#L47

Optimization level (7) is too high, IMO should be 2 or 3.

**Comment by makasim** [comment]
It has to be configurable

**Comment by makasim** [comment]
It has to be a configurable post processor. ConfigurablePostProcessorInterface

**Comment by BartVB** [comment]
There is a pull requests to make postprocessors configurable: https://github.com/liip/LiipImagineBundle/pull/720

**Comment by antoligy** [comment]
It may be worth taking a look at pngquant which is a bit quicker, albeit does lossy (unnoticable) compression.  https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/filters.rst#post-processors

**Comment by antoligy** [comment]
@makasim - This? https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/PostProcessor/ConfigurablePostProcessorInterface.php

**Comment by lsmith77** [comment]
please use the new config option available in 1.6.0
