### ISSUE TITLE
maintainer

### ISSUE THREAD

**Issue by lsmith77** [liip/LiipImagineBundle#746]
how are things looking in terms of maintenance? I am obviously not doing much at all aside from merging or responding the occasional PR/issue. but I feel generally we are reacting too slow to PRs/issues and development of a new major version seems stalled.

what do you think @makasim ..
any suggestions on how to proceed?

**Comment by makasim** [comment]
The bundle pretty much covers my needs and I do not plan to work on a major release any soon. 
That's not a problem to help people or review PRs from time to time for me.

**Comment by lsmith77** [comment]
Its similar to me .. I am not using the Bundle in any project actively since a while :-/

I guess I will post this issue on twitter to get some feedback from the community.

**Comment by javiereguiluz** [comment]
If I may, I have two quick questions:

* @makasim do you plan to stop working on this because you consider the bundle finished or do you want to deprecate it (like NelmioApiDocBundle) ?
* @lsmith77 I don't know if you can share the reason publicly but, what's the reason why you stopped using this bundle? Better alternatives? You no longer use Symfony?

Thanks!

**Comment by makasim** [comment]
> @makasim do you plan to stop working on this because you consider the bundle finished or do you want to deprecate it (like NelmioApiDocBundle) ?

@javiereguiluz I still using it, It is very helpful and powerful and I am certainly do not want to deprecate it. 
Some part of the bundle could be improved and I described them in roadmap 2.0 but I do not have time to work on them and there is not a project which would require something from that list.

**Comment by lsmith77** [comment]
@javiereguiluz we are a web agency, use depends on the projects we have. usually after a project we hand over maintenance to the client. so nothing wrong with the Bundle from our POV. that being said one some larger projects we started using rokka.io which does image resizing as a service. it uses imagine under the hood but is more specialized so we are not using the Bundle there.

**Comment by javiereguiluz** [comment]
Thanks for the info guys ... and good luck finding a maintainer!

**Comment by antoligy** [comment]
Following on from @lsmith77's comment on #715, might it be worth offering up slots to maintainers?

For one, I'm very interested in volunteering to help maintain and enhance this bundle, and have tonnes of ideas concerning responsive images and better ways of using this with the new-ish Picture element.

**Comment by lsmith77** [comment]
@antoligy awesome! I saw you have contributed some code already. so I would say if you can help me keep an eye on open tickets/PRs for a bit so that I and @makasim get to know a bit better, I am totally open to given you push rights.

**Comment by antoligy** [comment]
Sure thing, sounds like a plan! :smile: - Would be interesting to see if there are others who are also interested?

**Comment by lsmith77** [comment]
the more the merrier .. lots of tickets open :-/

**Comment by lsmith77** [comment]
@BartVB noticed you answered several tickets .. maybe you are also interested?

**Comment by cedricziel** [comment]
I would be interested too, since we rely more and more on the bundle. I didn't contribute much apart from the flysystem resolver, but I'd be interested.

**Comment by lsmith77** [comment]
things are really looking good now with so much activity!

thx @cedricziel, @robfrawley and @antoligy for stepping up!
