### ISSUE TITLE
applyMask() not working

### ISSUE THREAD

**Issue by retosteffen** [liip/LiipImagineBundle#750]
I tried to create a new Filter that transforms square thumbnails into round thumbnails with a mask on a PNG file.
(If I'm correct transforming jpg into png files isn't yet implemented in this bundle.)
But the applyMask() doesn't work, it just gives me back the same file.
Is this not yet part of the bundle or am I doing something wrong?

**Comment by antoligy** [comment]
Hey, thanks for reporting this, sorry about the delay - Is this still an issue?

If so, would you be able to contribute a failing test case?

**Comment by retosteffen** [comment]
Hi,
Sorry was travelling but will check it this is still an issue (it was a month ago) and provide a test case this week.

**Comment by retosteffen** [comment]
@antoligy 
Here is the script that doesn't work for me. It's supposed to make a PNG image square and then mask it with a circle so that the outer part of the circle is transparent.
If I export the mask as the image it gives the "right" result, i.e. a black circle with a transparent background.


```
use Imagine\Filter\Basic\Thumbnail;
use Imagine\Image\Box;
use Imagine\Image\BoxInterface;
use Imagine\Image\ImageInterface;
use Imagine\Image\Palette\Color;
use Imagine\Image\Palette\RGB;
use Imagine\Filter\FilterInterface;
use Imagine\Image\Point\Center;
use Imagine\Filter\Basic\ApplyMask;

class CircleThumbnailFilter implements FilterInterface
{
    private $imagine;



    public function __construct($imagine, BoxInterface $size)
    {
        $this->imagine = $imagine;
        $this->size = $size;
    }

    public function apply(ImageInterface $image)
    {
        // create a square thumbnail
        $thumbnail = $image->thumbnail(
            $this->size,
            ImageInterface::THUMBNAIL_OUTBOUND
        );

        // create a new image to hold our mask
        // make the background white
        $palette = new RGB();
        $white=$palette->color('#FFFFFF',0);
        $black=$palette->color('#000000',100);
        $mask = $this->imagine->create($this->size, $white);

        // draw a black circle at the center of our new image
        // use $this->size to make it full width and height
        $mask->draw()
            ->ellipse(
                new Center($this->size),
                $this->size,
                $black,
                true
            );

        // apply the mask to the thumbnail and return it
        return $thumbnail->applyMask($mask);
 
        
  
    }
}
```


Let me know if you need anything else.
Thanks!

**Comment by antoligy** [comment]
Thanks for this, I'll take a look most likely this evening! 😄

**Comment by rvanlaak** [comment]
ping @antoligy  ;)

**Comment by michellesanver** [comment]
@retosteffen It seems that this issue got forgotten. Easily happens! Since it's so old and not mentioned much anymore, I have decided to close it. If it's still an issue for you, or anyone, please open a new issue so that we know it's a current problem to debug. 

And thanks @antoligy for the intention to fix this, if you have any more context to this issue and would like to contribute a new issue (Even if not working on a PR), I'd be super grateful. Thanks! :)
