### ISSUE TITLE
Crop image into circle

### ISSUE THREAD

**Issue by kekcius** [liip/LiipImagineBundle#752]
Hi guys!
I need to crop the image into circle. 
Something like this: http://stackoverflow.com/a/999563
Did not find any appopriate filter to apply the mask. Is it possible?

**Comment by BartVB** [comment]
Sure, but you'll have to roll your own filter:
http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html

The watermark filter is probably a fairly usable template for this. What you're doing isn't cropping but drawing a circle and making everything outside this circle transparent. Reducing the size of the image can be done with one of the provided filters.

**Comment by kekcius** [comment]
Sorry, but I cannot find out how to do this "drawing a circle and making everything outside this circle transparent". Could you please explain?

**Comment by rvanlaak** [comment]
@kekcius same here, the following snippet should work but it doesnt:

```php

    public function load(ImageInterface $image, array $options = array())
    {
        $size = $image->getSize();
        $palette = new RGB();

        // Create a new image to hold our mask, make the background white
        $mask = $this->imagine->create($size, $palette->color('fff'));

        // Draw a black circle at the center of our new image,
        // use $this->size to make it full width and height
        $mask->draw()->ellipse(
            new Center($size),
            $size,
            $palette->color('000'),
            true
        );

        // Apply the mask to the thumbnail and return it
        return $image->applyMask($mask);
    }
```

**Comment by rvanlaak** [comment]
I've did dive into this, and it seems that because of a bug the masks don't work. PR has been merged January 6th. See:

* http://stackoverflow.com/a/31753084/1794894
* https://github.com/avalanche123/Imagine/pull/449

**Comment by michellesanver** [comment]
@kekcius Closing because of https://github.com/avalanche123/Imagine/pull/449, therefore not sure if this is still an issue for you in this bundle. If it's still an issue please open a new issue and we will prioritise and handle it accordingly. Thanks! :)
