### ISSUE TITLE
Request: Webp image conversion support

### ISSUE THREAD

**Issue by alexborton** [liip/LiipImagineBundle#755]
It would be really great to allow webp file conversion through filter_sets to allow progressive enhancement of images throughout builds.

ImageMagick offers support for the conversion and hopefully this can be utilised. 

Is this already possible with post processing? Does anyone have an example of this?

**Comment by lsmith77** [comment]
the main question is if the imagine lib supports it.

**Comment by antoligy** [comment]
Apparently not yet! https://github.com/avalanche123/Imagine/issues/271

http://php.net/manual/en/function.imagewebp.php

**Comment by Romaiin52** [comment]
Hi, thanks for your work ! Is there anything new about webP support ?

**Comment by nakashu** [comment]
FYI: the release is in with WebP support in imagine lib.
https://github.com/avalanche123/Imagine/releases

**Comment by antoligy** [comment]
Sweet! Hopefully someone can get on adding support soon.

**Comment by FabianSchmick** [comment]
Since the pull request from @franmomu was merged a while ago, I would like to know how to use the `WebP` feature with `LiipImagineBundle`, because it is not documented anywhere?

**Comment by bogdandovgopol** [comment]
So is WebP supported now?

**Comment by lsmith77** [comment]
I would assume that if you have a WebP source image, the imagine library can now resize etc.
Would be great if someone could test this and either update the docs (if needed) or submit an issue ticket if something isn't working.

If you are looking to be able to convert to WebP, then this isn't yet supported https://github.com/liip/LiipImagineBundle/issues/686

**Comment by franmomu** [comment]
Exactly, I applied locally some filters to a WebP image and it worked fine, there is no extra configuration, it's just that Imagine is able to handle the WebP format.

**Comment by FabianSchmick** [comment]
Alright, I was looking for support to convert an image to WebP. But as @lsmith77 commented there is no support yet, so I will keep waiting. Thanks clarifying things

**Comment by Gemorroj** [comment]
i have the error:
```
Uncaught PHP Exception Imagine\Exception\InvalidArgumentException: "Saving image in "webp" format is not supported, please use one of the following extensions: "gif", "jpeg", "png", "wbmp", "xbm"" at /var/www/wapinet/vendor/imagine/imagine/lib/Imagine/Gd/Image.php line 536 {"exception":"[object] (Imagine\\Exception\\InvalidArgumentException(code: 0): Saving image in \"webp\" format is not supported, please use one of the following extensions: \"gif\", \"jpeg\", \"png\", \"wbmp\", \"xbm\" at /var/www/wapinet/vendor/imagine/imagine/lib/Imagine/Gd/Image.php:536)"} []
```

**Comment by gnutix** [comment]
Apparently, the latest release of imagine added complete support for WebP : https://github.com/avalanche123/Imagine/releases/tag/1.2.2

However, LiipImagineBundle restricts the version of Imagine to ~0.7... Which is like 2 years old!

**Comment by dbu** [comment]
as 0.7 is a pre-release, the upgrade to 1.2 could be rather involved. as long as there are no difficult requirements on the underlying binaries (imagemagick / gd) i guess a pull request to update imagine would be welcome.

**Comment by martinbroos** [comment]
Any update on this? The 1.2.2 version of Imagine does get installed but not sure if the bundle already has the options to use webp.

**Comment by bogdandovgopol** [comment]
Any news?

**Comment by Soonz** [comment]
It would be a great update, I need that too.

**Comment by michellesanver** [comment]
I'm not sure if anyone is working on this. A pull request would be very welcome. It seems like we have some motivated people? :)

**Comment by floor12** [comment]
Is anybody work on it?
I cannot understand,  how is possible to make modern websites without webp support for content graphic in 2020 )

**Comment by franmomu** [comment]
> Is anybody work on it?
> I cannot understand, how is possible to make modern websites without webp support for content graphic in 2020 )

I guess not, what is not supported is image conversion, if you need it, feel free to start.

**Comment by floor12** [comment]
> I guess not, what is not supported is image conversion, if you need it, feel free to start.
I just came from Yii2 world and now m trying to find some bundles for my first projects on symfony. But its possible that i will implement it later, when i will be ready to such a deep dive. First, im trying to find something ready to use...
This lib looks very nice.

**Comment by Soonz** [comment]
I don't really feel the need to use this format but as Google seems to like it according to PageSpeed Insights I believe it can improve the SEO, that's the only reason I'm looking for it.

**Comment by floor12** [comment]
For me the reason is not only the PageSpeed rank, but the final page size can be half-small with webp and rendered much faster on middle-budget smartphones with unstable 3g connection. Especially with <picture> tag with different thumbnails for different screen sizes and resolutions. Usually I can use up to 8 different thumbnails for one picture in one place on the page: 1x - 2x size for retina o non-retina, webp and jpeg, mobile and desktop image size. I like this way )

**Comment by dbu** [comment]
this is an open source bundle, meaning that it will need somebody who wants to work on it to make this happen. we would be happy to have webp support in LiipImagineBundle but so far, nobody invested the time for implementing it.

the other option would be: if you have a very small project or some budget for it, liip offers https://rokka.io which is a hosted solution for image scaling and delivery with cdn. it supports both webp and specialized jpg algorithms for optimal images. the entry level (traffic and storage) is free and from there, prices are transparent.

**Comment by chregu** [comment]
My main question: What is the goal of webp support? If you want to deliver webp for browsers supporting it, but not for others (like safari), not sure LiipImagineBundle could do that, or it would need quite some technical changes (but I may be wrong). There's usually much more behind such stuff than it looks like on the first look.

Supporting webp to be used in a <picture> tag like described eg. here https://medium.com/front-end-weekly/html-picture-tag-in-practice-png-and-webp-formats-5a3fc51b5998
that's certainly technically more possible than automatic detection, but how many people would benefit from that?

And btw, webp usually brings about saving of  10% to 20% compared to same quality jpg. More is usually only under very ideal circumstances. For more we have to wait for next generation image compression like avif (or heif, but that's not gonna be supported by many or any browsers in the future)

So back to the inital question: What's the main goal of webp support? Where and how do you want to use that?

**Comment by floor12** [comment]
Usually, webp takes a half size of jpeg image. in my opinion, this is especially important on retina screens, where we transmit 2x size images. And it supports transparency, which is very helpful with really big png images (i can save up to 80% in this cases) . On a normal page, using webp helps save up to 40% of the page size, increase the rendering speed and lighthouse scores. 

Besides,  chrome and firefox support webp. The only safari does not support it...

I like to use it. 
In Yii2 framework i build a module that supports requesting image thumbnails with width and webp get params, it creates the thumbnail "on the fly" and store it in the cache... To prevent DDOS attacks by requesting a lot of images with different widths its possible to preconfigure possible thumbnail sizes for each file attribute in model...

I wandering find or create something with similar functionality for symfony. To prevent DDOS attacts with requsting

**Comment by cbastienbaron** [comment]
any news on this ? :)

**Comment by lsmith77** [comment]
Since the current version of the Bundle supports Imagine 1.2.2+, I would think it should just work like with any other format. So I would suggest please try it out and report back.

**Comment by peter-gribanov** [comment]
I am create PR #1307 that can solve this issue.
