### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by antonioperic** [liip/LiipImagineBundle#760]
Hi,
i am using imaginebundle with PHP7, and this is filter example

        47x47:
            quality: 75
            filters:
                thumbnail: { size: [47, 47], mode: outbound }
            post_processors:
                jpegoptim: {}

    driver: imagick

If picture doesn't exist it tries to resolve it but 404 is result if i try it to make from consoe i got
http://localhost/media/cache/sylius_small/98/83/9263f4779ab27fc3b71f0fcd18cc.jpeg
Segmentation fault

on second try it will generate image.

**Comment by lsmith77** [comment]
hmm normally no PHP code should cause a segmentation fault. so I fear the issue is more inside imagick or the PHP extension than this Bundle.

**Comment by makasim** [comment]
you can try to debug a place where it happens by storing the execution trace. 

```
php -d xdebug.auto_trace=ON -d xdebug.trace_output_dir=/tmp app/console xxx 
```
