### ISSUE TITLE
Finding if path is outside the root path check is wrong

### ISSUE THREAD

**Issue by BojidarStanchev** [liip/LiipImagineBundle#763]
LiipImagineBundle/Binary/Loader/FileSystemLoader.php lines 48-49 are just wrong.
First of all if I have ../ anywhere in the path this will throw an exception (how i actually discovered the problem) so if I have root/dir1/dir2/../dir2_1/A ... you get the point. 
Furthermore if somebody writes the path with the other slash '\' it will not pass the check even if it really goes outside of the defined root. As you can see checking if a path is a outside or a root folder is not a problem that can be solved with 1 line of code obviously.

**Comment by antoligy** [comment]
Hey,

I'm not able to replicate being able to escape this check using a backslash (it just escapes the next character for me in a variety of shells) - Could you provide some more information on this?

The use case is to prevent obvious security breaches however I agree that this isn't as elegant or necessary as effective as it could be, and for example this current rule is non-configurable which is not ideal for situations like yours.  Do you have any suggestions for a better way of approaching this?

**Comment by BojidarStanchev** [comment]
I haven't really tested with a backslash, it was just a suspicion. The real
problem for me was that I had ../ in the middle of the path and this check
became a problem. I worked around it by putting the part ../uploads/etc in
the config in the filesystem root and then just provide the rest of the
path that does not contain ../ and thus che if is skipped.
Well I haven't really thought about a solution, mainly because I am new to
php and web development (I have more experience with C, C++ and mainly C#),
but I think there could be a function that checks if a dir is a subdir of a
given path already written. Sadly I dont have the time to search for it
now. I just wanted to get some attention to those lines of code as they
might be a problem sometimes.

Thanks for the reply and best of luck :)

With respect,
Bozhidar Stanchev

**Comment by antoligy** [comment]
I'll see what can be done in the FileLoader to make this experience a little easier.

First step I guess is to write a regression test testing loading an image with a backslash - Contributions for this would be appreciated!
