### ISSUE TITLE
BC break causing Length of either side cannot be 0 or negative error

### ISSUE THREAD

**Issue by deviprsd21** [liip/LiipImagineBundle#769]
I believe this has been a common error from time to time, **Length of either side cannot be 0 or negative, current size is 0x0** * in vendor\imagine\imagine\lib\Imagine\Image\Box.php at line 42*, this error is appearing with the new release 1.6.0 and not when I revert back to 1.5.3

**Comment by deviprsd21** [comment]
Figured out the problem, it is PR #696 since I was using the DownScale filter, and specifically this [line of code](https://github.com/aminin/LiipImagineBundle/blob/0def3193de0f1c8cbc82050c18a7dd8a72dcc0d5/Imagine/Filter/Loader/DownscaleFilterLoader.php#L33) (is the problem). I sometimes use downscale filter with only one property, like `downscale: { max: [null, 152] }` (a good feature when you only want the width or height fixed and don't care about the other), but the `min($widthRatio, $heightRatio)` returns `0` since one argument is `null`.

**Comment by fancyweb** [comment]
I have the exact same problem, I hope your fix will be merged.

**Comment by deviprsd21** [comment]
@fancyweb Got positive responses so far, so hope so it gets merged :+1:

**Comment by fancyweb** [comment]
I think this issue should be closed because the fix made it into the master branch :wink:
