### ISSUE TITLE
Work with images from database

### ISSUE THREAD

**Issue by promarcel** [liip/LiipImagineBundle#771]
Hi

In future I would like use the `LiipImagineBundle` \w Symfony 3, for generate thumbnails in my gallery project. But there is a question I find no current answer:

We does store all images in our database, is there any way to access our database images with this awesome bundle? I've not seen any of this feature. The image blob is stored to a twig variable, so I can access there in twig.

I am glad to hearing from you!

**Comment by antoligy** [comment]
Yes this is completely possible, and there are already working implementations of this including in [ezplatform](https://github.com/ezsystems/ezpublish-kernel/tree/master/eZ/Bundle/EzPublishCoreBundle/Imagine).

You will need either need to implement a custom resolver, or load the image blob into the Binary model which this can then run on.

**Comment by marceldeglau** [comment]
@antoligy Thank you for your comment. But I don't see how to implement this. 

Can you help me or send me an little example?
Currently I am trying to use `imagine_filter('thumbnail')` directly behind the object they contain the blob data: `Image.getImageData|imagine_filter('thumbnail')`.

Symfony says exception: `An exception has been thrown during the rendering of a template ("Warning: ltrim() expects parameter 1 to be string, resource given") `

**Comment by antoligy** [comment]
Hey, the Twig extension doesn't currently accept resources as it expects a path to an asset.  Right now it's a [simple wrapper around the Cache Manager](https://github.com/liip/LiipImagineBundle/blob/master/Templating/ImagineExtension.php) which expects and returns a URL, though it may be possible to change this.

Could you reference files directly from the filesystem?  If not, it's questionable whether or not the CacheManager really offers you much, and so it might be worth directly interfacing with the FilterManager via a new Twig extension.

**Comment by marceldeglau** [comment]
For the future there are no images directly stored on in the filesystem. All images should be stored in the database as an blob. At the moment the images are via an GET /image/{id} accessable. This url returns the whole image as content. 

Do you have any ideas how to continue to using the LiipImagineBundle?

**Comment by lsmith77** [comment]
we build a loader for the CMF that can load images via Doctrine PHPCR ODM:
https://github.com/symfony-cmf/media-bundle/blob/master/Adapter/LiipImagine/CmfMediaDoctrineLoader.php

**Comment by ncmf** [comment]
@promarcel tell me, please, did you find a solution?

**Comment by promarcel** [comment]
@ncmf I'm sorry about it but I have stopped working with the bundle and continue with an own solution.

**Comment by michellesanver** [comment]
I am going through all issues to sort and prioritise. Is this still an issue for anyone? Since this is so old, please open a new issue if that is the case and we will prioritise accordingly. Thanks a lot! :)
