### ISSUE TITLE
Create thumbnails with a response of another controller

### ISSUE THREAD

**Issue by QuentinPi** [liip/LiipImagineBundle#772]
Hi everyone,
I would like to know if there is a good way to generate a thumbnail with LiipImagineBundle from a picture returned by another Symfony controller.
The other controller returns a reading of the picture (with readfile).
I try to generate a thumbnail from http://127.0.0.1/app_dev.php/controller_action/img_param but "app_dev.php" appears in the exit path automatically generated by LiipImagineBundle.
Is there a possible way to choose a better exit path for the thumbnail or to use my controller response in a proper way ?

(I use an absolute path instead of a relative path in order to protect the path and the name of the real files).

Thank you in advance !

**Comment by lsmith77** [comment]
I would recommend to refactor to controller to read images via a custom loader (see also #771)
