### ISSUE TITLE
FileSystemLoader and symbolic links

### ISSUE THREAD

**Issue by wtorsi** [liip/LiipImagineBundle#783]
Hello,

The recent changes in FileSystemLoader now prevent using assets installed through link option.
Realpath expands all symbolic links and further comparison to root path of course returns false.

What is the reason to make comparison to the root path? 
Is it good or not?

**Comment by robfrawley** [comment]
See https://github.com/liip/LiipImagineBundle/issues/780#issuecomment-244090262. You can still absolutely use symbolic links, you just need to set the `data_root` configuration option appropriately.

The check is intended as a security measure to ensure files aren't read from random locations on the filesystem (effectively, activity is "chrooted" into the data_root).

**Comment by lsmith77** [comment]
does that answer your question @wtorsi ? if yes please close the ticket .. if no please respond. thank you.

**Comment by wtorsi** [comment]
Yes, it's clear now.
