### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by antoligy** [liip/LiipImagineBundle#786]
Hey,

#781 reminds me that [we have a CHANGELOG.md](https://raw.githubusercontent.com/liip/LiipImagineBundle/1.0/CHANGELOG.md), only it hasn't been updated since 2013!

I propose that we try and generate something based on [our Github releases](https://github.com/liip/LiipImagineBundle/releases), or do we flat-out remove it?

If we opt for the former, [something like this might suffice](https://github.com/skywinder/github-changelog-generator).

Cheers,
Alex

**Comment by robfrawley** [comment]
Initial stab at auto-generating a CHANGELOG.md  in #788 using skywinder/github-changelog-generator.

My preference is to retain a changelog.

**Comment by antoligy** [comment]
Agreed (personally CHANGELOGs are a preferred way of finding out why <X> upgrade has broken <Y> thing), and yeah that format looks pretty great!

There's a bit of visual weirdness around here, I wonder where that comes from - https://github.com/robfrawley/LiipImagineBundle/blob/90584f608ce98dbc2937a347d7adaa20891a6bf5/CHANGELOG.md#unreleased

**Comment by robfrawley** [comment]
@antoligy Good catch: looks like the `github-changelog-generator` command concatenates on sequential runs so the file was duplicated multiple times. New version pushed live:

https://github.com/robfrawley/LiipImagineBundle/blob/1c5302fa27e9425348732d08e51f81fd1e9bdd2f/CHANGELOG.md

**Comment by antoligy** [comment]
Nice one! 😄

**Comment by robfrawley** [comment]
@antoligy Looks like #788 was merged.

**Comment by antoligy** [comment]
Perfect, thanks for tackling this! Should be a bit easier going forward now.
