### ISSUE TITLE
[Documentation] Create detailed tutorial on compiling RST locally for testing purposed

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#798]
Having struggled through the difficulty of compiling and testing my updating RST documentation (see PR #789), I believe it would be a good idea to offer documentation on _how to build the RST documentation_, as well as possibly include a build script to do it automatically on compatible systems. This may make it easier for others to contribute (and test their contributions) to the RST docs.

Having said that, the exact steps used by Symfony to perform documentation compilation don't seem to be published anywhere, so I was hoping @javiereguiluz could provide some insight into this, given his extensive involvement with the official Symfony docs.

I used the below procedure to test the above-referenced PR locally:
- Install `python-sphinx` (using `apt` on Ubuntu with `sudo apt install python-sphinx`).
- Install `sphinx-php` python module per [directions from the README](https://github.com/fabpot/sphinx-php/blob/master/README.md).
- Clone this repo and enter the directory (likely `./LiipImagineBundle`).
- Clone [symfony/symfony-docs.git](https://github.com/symfony/symfony-docs) (to `./LiipImagineBundle/symfony-docs`).
- Copy the docs from _this repo_ (at `Resources/doc`) to a _new folder_ within the cloned symfony-docs repo (to `./LiipImagineBundle/symfony-docs/liipimaginebundle`).
- Add this new folder (`liipimaginebundle`) to any random `doctree` block in the symfony-docs `index.rst` file (at `./LiipImagineBundle/symfony-docs/index.rst`).
- Enter the symfony-docs build directory (at `./LiipImagineBundle/symfony-docs/_build/`) and build HTML using the included `Makefile` (issue `make html`).
- View in Chrome (or another browser) using `google-chrome symfony-docs/_build/html/liipimaginebundle/index.html`

@javiereguiluz Are there any steps missing or, perhaps, easier ways to accomplish a similar result?

**Comment by robfrawley** [comment]
Ping @javiereguiluz - any insights would be amazing.

**Comment by robfrawley** [comment]
Initial wiki article detailing basic RST build now available: https://github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation

**Comment by antoligy** [comment]
Very nice!  What's next?

I'm happy to contribute instructions for building in a MacOS environment based on what you've written for Debian.

**Comment by robfrawley** [comment]
@antoligy Adding build instructions for additional operating systems would be much appreciated, and should be relatively easy for other *nix-based environments. If I am not mistaken, assuming the Xcode Command Line Tools are installed, the instructions should be the same short of installation of the Python dependencies.

If you could play around and figure out the requirements, that would be amazing.

If you have a direct access to the wiki, feel free to update it with the info. And if you don't, post the markdown here and I'll update the page.

Thanks!

**Comment by robfrawley** [comment]
Here is an exerpt from the Homebrew install script to automate installation of the Xcode Command Line Tools (written in Ruby, it seems):

```
if should_install_command_line_tools?
  ohai "Searching online for the Command Line Tools"
  # This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
  clt_placeholder = "/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
  sudo "/usr/bin/touch", clt_placeholder
  clt_label = `softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | head -n1`.chomp
  ohai "Installing #{clt_label}"
  sudo "/usr/sbin/softwareupdate", "-i", clt_label
  sudo "/bin/rm", "-f", clt_placeholder
  sudo "/usr/bin/xcode-select", "--switch", "/Library/Developer/CommandLineTools"
end

# Headless install may have failed, so fallback to original 'xcode-select' method
if should_install_command_line_tools?
  if STDIN.tty?
    ohai "Installing the Command Line Tools (expect a GUI popup):"
    sudo "/usr/bin/xcode-select", "--install"
    puts "Press any key when the installation has completed."
    getc
    sudo "/usr/bin/xcode-select", "--switch", "/Library/Developer/CommandLineTools"
  else
    abort "Error: Cannot proceed with manual Command Line Tools install without user input!"
  end
end
```

**Comment by robfrawley** [comment]
Can anyone with access to a Debian/Ubuntu based system review the procedure I wrote up [on the wiki](https://github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation). I just moved this issue to [the in peer review](https://github.com/liip/LiipImagineBundle/projects/1) stage on the project board. (We'll move it back to in-progress if @antoligy elects to pursue OSX support).

**Comment by robfrawley** [comment]
@antoligy Do you plan to offer OSX updates? If so I'll keep this open for now. If not I was going to mark this as complete for the time being to clean up out issue tracker.

**Comment by antoligy** [comment]
Hey, I've been a little busier than anticipated lately so slow on all fronts here- I'm still quite keen to contribute OSX docs (and then some), and so to avoid holding this back it might be best to do that in a further PR.

If nobody else gets a chance to review for Debian/Ubuntu, I'll make an effort to free up a few minutes in the coming days and to take a look so that we can move this forward!

**Comment by robfrawley** [comment]
@antoligy Thanks for the clarification.

**Comment by robfrawley** [comment]
@alexwilson Since this issue was only just recently closed by @dbu (based on, I can quick obviously imagine, its complete lack of any recent activity whatsoever ;-), I wanted to quickly re-open it and reach out to you (@alexwilson) so as to request that you provide a response on the record; pending your affirmative response, dissenting response, or lack of a response, this issue will then be either kept opened or re-closing (following three weeks from 2021-11-20 for a response).

Without implying any pressure or otherwise intending to push you into performing this work, can you clarify if you are still available and interested in volunteering your time (or, in the alternative, no longer able to assign any of your time) as to the creation of a new __OSX__-specific wiki instructions page that mirrors my [__Linux/Unix/Solarus/etc__-specific wiki instructions page](https://github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation) and similarly detailing the RST documentation build process for this Symfony bundle (but tailored for OSX users)?

Again, no pressure either way; I only want to inquire as to your intentions before this issue is entirely closed for good. Please let me know and I'll update this issue's status accordingly.

Thanks! All the best.

---

@dbu Also, please let me know if this issue was solved in another manner or by another individual already and, therefore, can be closed as being entirely moot.

**Comment by robfrawley** [comment]
@alexwilson @dbu Actually, never mind. You can safely ignore my prior comment in its entirety. :-) It looks like __some__ OSX-specific documentation was already added to [github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation](https://github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation). Moreover, I've decided to actually take some time myself to go through that wiki page and make sure everything is up to date and working for the Linux and OSX instructions, as well as add additional instructions specifically for Windows environments.

Anyway, sorry for bothering you both with some needless GitHub notifications. All the best!

**Comment by robfrawley** [comment]
Following up in #1433.

**Comment by dbu** [comment]
no worries about the notifications, and thanks for looking into it!

as you probably noticed, i started to put some time into managing this bundle. to get a grip on the open issues, i closed lots of old things that looked inactive to me. that was not meant to discourage contributions, but just to reduce the backlog of things that i don't know if anyone works on.

thanks for #1433, will look at it now.
