### ISSUE TITLE
Refactor controller business logic to service(s)

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#806]
With the `1.x` codebase, the controller defines a large subset of routing and conditional logic between the different objects required to successfully generate and cache a transformed image, and as the current controller interface requires a request object, such must be mocked when called outside a context where a request object is natively available.

This is inconvenient, and can be improved.

This `2.x` feature is to tear the vast majority of business logic out from the controller and define a collection of (or one?) services that implement the required logic to "glue" together the different layers needed. Most importantly, this new functionality should be request-agnostic.

**Comment by robfrawley** [comment]
Current work on this feature is being contributed by @jehaby in my [sandbox repository clone](https://github.com/src-run/liip-imagine-bundle-sandbox/pull/2). A formal PR will originate from the sandbox repo once an implementation is finalized, for inclusion in this repo's `2.x` branch.

**Comment by robfrawley** [comment]
@jehaby Just moved this to the ["in peer review"](https://github.com/liip/LiipImagineBundle/projects/1) stage on the [project tracker](https://github.com/liip/LiipImagineBundle/projects/1). I will be taking a look over the next few days to provide feedback on this initial stab at implementing this feature!

**Comment by dbu** [comment]
the controller seems cleaned up now, i think this has been done.
