### ISSUE TITLE
Migrate from PHPUnit 4.x to 5.x

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#807]

**Comment by robfrawley** [comment]
@lsmith77 I just re-assigned and and re-labeled this (I thought it didn't save the first time or something), and then subsequently removed the assignment and label (after seeing you has actually done it). Was that intentional?

**Comment by antoligy** [comment]
How much is there to do on this, would it be possible to break down the various steps we'd need to take?

[As far as I can tell there isn't much by the way of deprecated functionality](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.0.0) in 5 so this could be quite an easy win...

**Comment by robfrawley** [comment]
@antoligy You'r right that there are not a huge amount of deprecations, but there are some, as well as some general cleanup and consistency alterations I'd like to implement. This has to be a 2.x change as PHPUnit dropped support for PHP 5.3, which the 1.x release of this bundle supports.

Here is a brief breakdown of my goals:
- Move from `$this->getMock('The\Namespaced\Class')` to `$this->getMockBuilder('The\Namespaced\Class')->getMock()` (the former is deprecated)
- Remove all expected exception annotations in favor of explicit method calls to `expectException`, `expectExceptionMessage`, and `expectExceptionMessageRegex`
- Remove all hard-coded classes as strings (for mocks, exceptions, etc) in favor of using `::class` (for example, change `expectException('The\Namespaced\ExceptionClass')` to `expectException(ExceptionClass::class)`

The last item is the reason for removal of expected exception annotations, which by definition have to be hard-coded class path strings.

I'm sure there is more, but those are initial thoughts.

**Comment by lsmith77** [comment]
One thing .. phpUnit's mock API never has been all that great. another possibility would be to use prophecy for this instead for example.

**Comment by makasim** [comment]
> Move from $this->getMock('The\Namespaced\Class') to $this->getMockBuilder('The\Namespaced\Class')->getMock() (the former is deprecated)

better to use`createMock` method

**Comment by robfrawley** [comment]
@lsmith77 @makasim @antoligy I'm actually very much in favor of a move to Prophecy (as @lsmith77  suggested) as its API is crazy clean in comparison. Doing this does complicate and balloon the work needed for this, but it may be worth it.

Can we get a thumbs up/down on this comment for everyone to vote for or against this change?

**Comment by makasim** [comment]
FYI: I've never had problems with Phpunit mock so I am not sure the migration worth it. I tried Prophecy several times but failed to "get it".

**Comment by antoligy** [comment]
Completely in favour of moving away from PHPUnit mocks, they're okay, but I get the distinct impression that much of their adoption is down to the convenience of them being available directly through PHPUnit.

**Comment by xabbuh** [comment]
> better to use `createMock` method

@makasim This would drop compatibility with PHPUnit before 5.4 which isn't a good idea as this bundle still supports PHP 5.3 for which you need PHPUnit 4.x (PHPUnit 5.x dropped support for PHP < 5.6). So I would either update the current tests to make use of `getMockBuilder()` in all places or move to something else (like Prophecy).

**Comment by antoligy** [comment]
That's fine as this would only be for v2, which (at time of writing) raises our minimum level of support.

I don't believe there are plans to backport this to v1, though please correct me if I am wrong!

**Comment by makasim** [comment]
Pay attention to the fact that it will be harder to maintain both versions of the bundle (if we migrate to prophecy or change tests significantly). Imagine someone sends a PR with a fix for v1 which is make sense for v2 too. 

This argument is only valid If we do plan to support v1

**Comment by robfrawley** [comment]
@makasim While I think it would be good to support bug fixes and security fixes v1 for some time after the release of v2, I don't envision the codebases or the test suites to be particularly compatible or similar, so PR compatibility isn't a factor from that point of view.

Where others envisioning more similarity between the two?

**Comment by robfrawley** [comment]
We are now fully compatible with PHPUnit `5.x`. As for the prophecy discussion, I've moved [that issue](https://github.com/liip/LiipImagineBundle/issues/811) to the [`2.1.0` milestone](https://github.com/liip/LiipImagineBundle/milestone/17). Any additional discussion about prophecy should be discussed there.
