### ISSUE TITLE
Some image cache are not created ?

### ISSUE THREAD

**Issue by lucFM** [liip/LiipImagineBundle#810]
Hi, thanks for your work.

I have a strange issue in prod env, all works fine, but just some image are not found and cache is notre created.
Source image exists and cache works in dev env.

Here nginx log for one of this error:
[error] 28686#0: *23 open() "/mysfpath/web/app.php//media/cache/resolve/news_recent/uploads/media/v1/fotolia_87219112_s_0.jpg" failed (20: Not a directory), request: "GET /media/cache/resolve/news_recent/uploads/media/v1/fotolia_87219112_s_0.jpg HTTP/1.1"

His someone can help me ?

Regards

**Comment by lsmith77** [comment]
hmm .. is there anything special about those images? does the image work correctly if you by pass the Bundle?

**Comment by JulienItard** [comment]
Same error here. works on dev not prod.

**Comment by robfrawley** [comment]
The first thing that stood out to me was the double slashes that exist after `app.php`, which I remember has cause me grief quite some time ago... Assuming Nginx still doesn't play nice with such, I would investigate how to ensure your request is built as expected.

```
/mysfpath/web/app.php//media/cache/resolve/news_recent/uploads/media/v1/fotolia_87219112_s_0.jpg
                     ^^ (those double slashes there)
```

I could be wrong and this may have everything to do with something else, but I **do** know that has cause me grief a long while back.

**Comment by dbu** [comment]
i am cleaning up old issues. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
