### ISSUE TITLE
Images are not resolved in some browsers

### ISSUE THREAD

**Issue by Tetragramat** [liip/LiipImagineBundle#812]
Hi, some time ago I updated to liip/imagine-bundle 1.5.3. Today I found out in some browsers, for uploaded images, cache is not resolved.
In network console these reguests have response code 406 Not Acceptable.
In log is following exception:

> Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: "No matching accepted Response format could be determined" at /my_project/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/FormatListener.php line 74
> Context: { "exception": "Object(Symfony\\Component\\HttpKernel\\Exception\\NotAcceptableHttpException)" }

I have no idea what I did wrong.

### Some additional info

Where it does work?

Linux | OSX | Windows
-------- | -------- | -----------
firefox | firefox
 | safari

Where it does **not** work?

Linux | OSX | Windows
-------- | -------- | -----------
chrome | chrome | chrome
 |  | firefox
 |  | Edge
 |  | IE 11

Yaml configuration

```
liip_imagine:
    filter_sets:
        cache: ~
        my_thumb_120_90:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: inset }
        my_thumb_400_300:
            quality: 75
            filters:
                thumbnail: { size: [400, 300], mode: inset }
        my_thumb_400_180:
            quality: 75
            filters:
                thumbnail: { size: [400, 180], mode: inset }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: force
        formats:
            xml:  true
            json: true
        templating_formats:
            csv: true
            html: true
        force_redirects:
            html: false
        mime_types:
            css: 'text/css'
            js: 'application/javascript'
            csv: 'text/csv'
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: ^/, priorities: [ html, js, css, csv ], fallback_format: ~, prefer_extension: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    disable_csrf_role: ROLE_API
    serializer:
        serialize_null: true
```

**Comment by antoligy** [comment]
Hey, 

Cheers for reporting! - It might be helpful to post more information about which versions of those browsers work, and if they've got any extensions installed which might interfere with network requests.

At a glance it sounds like the FOSRestBundle is intercepting requests meant for the resolver.  This is likely due to those browsers sending down content negotiation headers (or not sending content negotiation headers) which are hitting a conditional before the `liip_imagine_filter ` route.

What versions of the FOSRestBundle and of Symfony are you running?
What happens if you attempt to access those images directly in the browsers where it doesn't work?
Can you access them if you attempt to run a `curl -v https://path/to/images`?

Cheers,
Alex

**Comment by Tetragramat** [comment]
Thank you for the answer.

All browsers have no extensions loaded.
I got different results for OSX and Windows, because I tested it on different computers.

For next list, indirect access means that image is linked in \<img src="IMAGE_URL"\>. Direct access means opening IMAGE_URL in browser directly.

- Linux Chrome 52.0.2743.116 (64-bit)
  - indirect access not working
  - direct access working
- Linux Firefox 48.0
  - indirect access working
  - direct access working
- OSX Chrome 53.0.2785.143 (64-bit)
  - indirect access not working
  - direct access working
- OSX Firefox 46.0.1
  - indirect access not working
  - direct access working
- OSX Safari 10.0 (11602.1.50.0.10)
  - indirect access working
  - direct access working
- Windows Chrome 53.0.2785.143
  - indirect access not working
  - direct access working
- Windows Firefox 49.0.1
  - indirect access working
  - direct access working
- Windows IE 11.321.14393.0
  - indirect access not working
  - direct access working
- Windows Edge 38.14393.0.0
  - indirect access not working
  - direct access working

If I access unresolved image with curl, it responses 301 and redirects to the resolved image.
It looks like all browsers which send header `Accept:"*/*"` with changed weight or without `Accept:"*/*"` header does not work.

I tested behaviour using curl by setting different Accept headers and everytime where there was not `Accept: */*` with default weight, the exception occured.

Installed packages
```
symfony/symfony                         v2.8.9
friendsofsymfony/rest-bundle            1.8.0
liip/imagine-bundle                     1.5.3
```

**Comment by Tetragramat** [comment]
It was wrong FOSRestBundle configuration for root path.
Following configuration of format_listener under fos_rest is working correctly.
```
fos_rest:
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: ^/ }
```

Thank you for your help.
