### ISSUE TITLE
Mode parameter

### ISSUE THREAD

**Issue by devozanges** [liip/LiipImagineBundle#813]
Hi , I dont find any documentation for the MODE parameter ?
thanks

**Comment by devozanges** [comment]
sorry I finally found it

http://symfony.com/doc/master/bundles/LiipImagineBundle/filters/sizing.html

**Comment by robfrawley** [comment]
@devozanges For future reference, all build-in filters are indexed at [LiipImagineBundle/filters.html#built-in-filters](http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html#built-in-filters)

**Comment by devozanges** [comment]
yes but I wanted to know if other parameters like "inset" or "outbound" exists

**Comment by robfrawley** [comment]
@devozanges Are those parameters missing from the documentation somewhere?

**Comment by devozanges** [comment]
I just think ca deserves to be clearer, as these are common parameters

**Comment by robfrawley** [comment]
@devozanges Are you specifically speaking about the `mode` values? (http://symfony.com/doc/master/bundles/LiipImagineBundle/filters/sizing.html#thumbnail-options) Do you have any examples of how it could be more clearly described? If not a PR, please describe how it wold be better written up do I can refine the documentation, as the latest main revision of those docs are my doing.

**Comment by devozanges** [comment]
I think the most common parameters must always appear very clearly (on github too) without having to search very far. Otherwise, thank you for your work
