### ISSUE TITLE
Broken "Edit this page" links in documentation

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#814]
Documentation pages generated from our RST files and deployed within the bundles sub-section of the Symfony docs provide an "Edit this page" button on the top right of all pages. For example, consider the [Size Filter page](http://symfony.com/doc/master/bundles/LiipImagineBundle/filters/sizing.html).

The page links to a 1.3 branch (which does not exist). Can we somehow configure our docs to link to master, the correct branch name (1.0), or should we perhaps rename 1.0 to 1.3? Are there other options available to us? Is this important?

**Comment by lsmith77** [comment]
@javiereguiluz do you know about this?

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. We can reproduce it, so it's already fixed ... but we'll need to wait until the next symfony.com redeploy. Thanks!

**Comment by robfrawley** [comment]
Wonderful; thanks @javiereguiluz
