### ISSUE TITLE
Custom resolvers can only be used on a per filterset basis, not as default resolver

### ISSUE THREAD

**Issue by rpkamp** [liip/LiipImagineBundle#822]
For a very specific use case I needed the resolver cache completely disabled, so I tried to use the `\Liip\ImagineBundle\Imagine\Cache\Resolver\NoCacheWebPathResolver` resolver, which according to `imagine.xml` should be available as a `no_cache` resolver.

```xml
<service id="liip_imagine.cache.resolver.no_cache_web_path" class="%liip_imagine.cache.resolver.no_cache_web_path.class%" public="true">
    <argument type="service" id="router.request_context" />
    <tag name="liip_imagine.cache.resolver" resolver="no_cache" />
</service>
```

However, when I use that value like

```
liip_imagine:
    resolvers:
        default:
            no_cache: ~
```

I get the following exception:

>InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "no_cache" under "liip_imagine.resolvers.default"

Looking into this some more I found that the `\Liip\ImagineBundle\DependencyInjection\Configuration` is dependent on the factories it receives from `\Liip\ImagineBundle\DependencyInjection\LiipImagineExtension`. However, `\Liip\ImagineBundle\Imagine\Cache\Resolver\NoCacheWebPathResolver` does not have a factory, so the configuration fails with this errors.

There are two possible solutions here that I can think of:

1) Make factories required for all resolvers, including the `NoCacheWebPathResolver`, which would be nice in terms of configuration, but more work for people who want to implement their own custom resolver because they need to implement a factory as well. Also, there would need to be a way to register factories for non-default resolvers.
2) Allow resolvers to work without a factory, this would be more loose in terms of configuration (if we don't recognise the resolver just assume it exists and pass it the configuration we got passed and hope for the best), but easier to implement for people who want to implement their own resolver because don't need to think about a factory.

I'd be happy to provide a PR for either one of those options, but since I'm not sure which direction you would like to go I thought I'd report an issue first.

Also, this bug applies to loaders as well.

**Comment by robfrawley** [comment]
I generally prefer option 2. @lsmith77 @antoligy Thoughts?

**Comment by lsmith77** [comment]
I don't feel strongly either way, but lean a it towards option 2 as well.

**Comment by rpkamp** [comment]
Alternatively, we could add a `custom` option with a `CustomFactory` where the config would look something like

```
my_custom_resolver:
    class: My\Custom\Resolver

liip_imagine:
    resolvers:
        default:
            custom:
                service: my_custom_resolver
```

The only thing is that this won't work with the compiler passes so those would have to go. Seeing how they don't work at the moment it won't be a real BC I think.

Thoughts?

**Comment by antoligy** [comment]
Sorry, thought I'd hit send two weeks ago but clearly not - I'm more inclined towards option 2 also, as it allows for greater flexibility and is more in-line with how data loaders are built.

A custom dataloader might be another solution, I've no strong stance on it if it doesn't break BC.  Might be worth seeing how it works out in practice?

**Comment by rpkamp** [comment]
So I've been diving into the code in order to see if I could fix this, and found that the Resolver CompilerPass does not do what I expected it to. What it does is load a cache resolver so it can be used for a specific filter in the configuration, like

```
liip_imagine:
  filters:
    foo:
      cache: no_cache
```

and that works fine. The thing that doesn't work, but from the looks of it was never supposed to work in the first place, is setting a resolver that was loaded through the CompilerPass as the default resolver.

If adding custom resolvers and setting them as default is something you guys are interested in I would suggest leaving 1.0 as is, and add it to 2.0, overhauling the complete system of loaders and resolvers.

**Comment by antoligy** [comment]
Yeah, I believe that's in-line with the rest of the roadmap for 2.0 so I'm happy to go down that road.  It seems like greater flexibility all-around, and one step closer towards the ultimate goal of cross-format conversion!

On that note I believe we should keep this issue open to track that change, but maybe adjust the title to avoid confusion.

**Comment by dbu** [comment]
i am going through old issues. ok if we close this one? is it still a problem with version 2?

**Comment by rpkamp** [comment]
I'm no longer on the project where this issue was found, so I couldn't tell. 

Since this issue is really old and the problem was really niche I would suggest to close it. People can always open a new issue if it pops up again.

**Comment by dbu** [comment]
thanks for the feedback. yeah lets close and see if it pops up again.

**Comment by gzhegow1991** [comment]
Opening again
Wanted ChainResolver to pass dynamic resolver for my env/host
Using local at home, and aws on production server. Also i have development server

Same error:
```
  Unrecognized option "chain" under "liip_imagine.resolvers.upload_resolver". Available options are "aws_s3", "flysystem", "web_path".
```

Have registered service:
```
services:
    App\Liip\ImagineBundle\Imagine\Cache\Resolver\ChainResolver:
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "chain" }
```

Should it be public?            - 

So my requirements looks that:
- upload_loader.chain.loaders: [ works well ]
- upload_resolver.chain.resolvers [ does not work ]
- local_prod_images_loader
- local_prod_images_resolver
- local_dev_images_loader
- local_dev_images_resolver
- aws_prod_images_loader
- aws_prod_images_resolver
- aws_dev_images_loader
- aws_dev_images_resolver

Also to upload we should use certain one, but it depends on env variables APP_ENV and UPLOAD_SOURCE.
But we should have resolver that can recognize by image postfix like image@prod_aws.jpg detect what URL is the right one.

Shit happens when we copy half of production database to development web-site to test some feature, and of course have the hell with ENV files + 99% photos is not available cause of resolver wants development image storage instead of production one.

Actually its not a problem for us (devs). It is a problem for managers, they ask "where is the photos????111"
