### ISSUE TITLE
Documenting common pitfalls

### ISSUE THREAD

**Issue by antoligy** [liip/LiipImagineBundle#828]
Continuing on from https://github.com/liip/LiipImagineBundle/pull/827...

Right now, while not strictly an issue regarding this repository, there's at the very least a common pitfall wherein without a correctly configured Symfony application + reverse proxy, we'll generate links with the wrong scheme (as we utilise Symfony's `Request` class).

I'm not sure if there are any other obvious ones, but I am thinking to remedy this we should start looking at building a FAQ?

**Comment by greg0ire** [comment]
Either a FAQ or maybe augment the [web path resolver](https://github.com/liip/LiipImagineBundle/blob/1.0/Resources/doc/cache-resolver/web_path.rst) docs? That's the class where I found this piece of logic.

**Comment by cedricziel** [comment]
I like the idea of adding the pitfalls  to the web path resolver docs, since other resolvers (may) have their own ways of obaining the correct path for their referenced assets. (think of flysystem for example)

**Comment by robfrawley** [comment]
All for improving the docs! For those not comfortable with RST, feel free to post the information you'd like added here and I'll be happy to push it into our RST documentation.

**Comment by greg0ire** [comment]
I went ahead and made #829 . Please review.
