### ISSUE TITLE
Update RST documentation to use `asset()` Twig function

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#830]
The `README.md` code examples now make use of the Twig `asset()` function, per #825. We should bring the relevant examples in the RST documentation in-line with this convention. While the prior mentioned PR affected only four `README.md` lines, I know that their are a few additional examples in the RST documentation, all of which should be consistent, IMHO.

**Comment by antoligy** [comment]
Agreed!  Have you got this covered or would you like me to have a crack at this?

**Comment by robfrawley** [comment]
I won't be about to get to it until next week, so if you have time, feel free to give it a go. Otherwise I'll take care of it in the coming weeks. A little crazy busy for me ATM. ;-)

**Comment by antoligy** [comment]
I've just resubmitted my PR under #836
