### ISSUE TITLE
Problem with the signer

### ISSUE THREAD

**Issue by Guite** [liip/LiipImagineBundle#837]
I am trying to generate thumbnails using runtime options and receive the following error:

```
Signed url does not pass the sign check for path "userdata/RKParkhausModule/bilder/fahrzeugbild/logo.png" and filter "zkroot" and runtime config {"thumbnail":{"size":["250","150"],"mode":"inset"}}
```

The configuration looks like this: https://github.com/zikula/core/blob/1.4/src/app/config/imagine.yml

Any idea what I am doing wrong?

**Comment by robfrawley** [comment]
@Guite: Looks like you resolved this in your own code @ Guite/MostGenerator#859, if so can you please close this issue.

**Comment by Guite** [comment]
@robfrawley no I just added an ugly hack as a workaround by adding a DummySigner which always returns `true` in it's `check` method. So this bypasses the issue, but does not fix it.

**Comment by Guite** [comment]
Here is the hack: https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/controller/util/ImageHelper.xtend#L282

**Comment by robfrawley** [comment]
@Guite Ah, ok. Thanks for the update. Will take a look at this at some point over the weekend to see if I can't derive a cause.

**Comment by mablae** [comment]
Hello, 

I am facing the same issue right now. I think the problem lies in the way the URL gets escaped? 

My usecase is an inline  `<style>` tag to set the `background-image` URL via media queries. 
The wrong encoding of the URL causes somehow to only the first filter element gets passed to the 
`$runTimeConfiguration`

**Comment by Perni1984** [comment]
don't know if that is related to your problem. But I had an issue when I used runtimeOptions in twig in a css context, whereas the runtimeOptions did contain an array. I guess the twig css filter somehow altered the url string.

The following code did throw a 'Signed url does not pass the sign check for path ...' BadRequestHTTPException:
```css
background: url('{{ image_url | imagine_filter(imagine_filter_name, runtimeConfig)');
```
whereas the following code did work out fine:
```css
background: url('{{ image_url | imagine_filter(imagine_filter_name, runtimeConfig | raw )');
```

**Comment by mablae** [comment]
What @Perni1984 said. I experienced this myself and used the same workaround

**Comment by Guite** [comment]
I had another use case, but I removed my hack mentioned above and could not reproduce the problem anymore. Happily closing :-)

**Comment by Perni1984** [comment]
FYI - in my concrete case I had a runtime config as follows:

```php
[
        'focalresize' => [
                'size'        => ["287", null],
                'focal_point' => $focalPoint,
            ],
        ];
}
```

The `null` above was converted to an empty string by the signer, but when generating the url for the image, the `null` parameter was completely omitted, thus resulting in a signature mismatch.

My solution was to convert the `null` from above to an empty string.

```php
[
        'focalresize' => [
                'size'        => ["287", ""],
                'focal_point' => $focalPoint,
            ],
        ];
}
```
