### ISSUE TITLE
Links on badges in README.md don't work

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipImagineBundle#839]
The links don't work: https://github.com/liip/LiipImagineBundle/blob/6ffb1bcb04b542ed43561ee3b4a82ec68ddfc97b/README.md#liipimaginebundle

Example of link: https://src.run/service/liip/LiipImagineBundle/1.0/travis

It looks like `https://src.run` doesn't work.

Update: it works with Chromium (a browser based on Chrome's code) but not with Firefox.

**Comment by robfrawley** [comment]
Seems to work on Chrome and Firefox for me (I wrote the, arguably ugly, Silex code that powers that website)... I also borrowed my roommate's MacBook and it also works on both Chrom and Safari on OSX as well. It's literally returning a redirect, so I'm unsure what the issue you are running into is.

**Comment by robfrawley** [comment]
Also, if you are receiving an error, please provide such. Stating "it doesn't work" doesn't provide much diagnostic information for fixing any issues that may exist. For example, do you get an exception? Is the page blank? If so, what does the developer console's "network" panel show in terms of activity? Etc. Thanks!

**Comment by alexislefebvre** [comment]
I had a blank page earlier today. I'm using Firefox right now, on another machine and another network, it works. I'll check again tomorrow and will provide more information.

**Comment by robfrawley** [comment]
Ok; thanks!

**Comment by alexislefebvre** [comment]
When I copy and paste the URL in the browser bar, nothing appear in the Network tab.

Because of my test environment, I use Firefox 45.0.2 which is not the last version. Maybe it comes from here. I'll close it for now since I can't reproduce this on another browser.
