### ISSUE TITLE
Question - Should we continue using temporary files for 

### ISSUE THREAD

**Issue by alexwilson** [liip/LiipImagineBundle#843]
Hey, I'm just going through the PostProcessors, trying to normalise them for `2.0`, and I've come across the fact that the MozJpeg and Pngquant Post Processors don't have the option to use temporary files before being passed to their respective tools.  Partially this is because both support input through `stdin`, but also this was initially a decision for performance.

In 2.0, it seems like we should be improving consistency - So, should I go ahead and remove temporary files from jpegoptim (stdin support as of 1.4), and leave in optipng (doesn't support yet), or should we introduce support for temprary files to Pngquant and MozJpeg?  Or, alternatively, do nothing?

# TODO # 

- [ ] Need to benchmark this for both time and memory usage.

**Comment by robfrawley** [comment]
I would love to get rid of temporary files in *as much of the code as humanly possible* as touching the disk is always going to cause additional (and in many cases, in the current code base, unnecessary) performance penalties.
