### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by lsmith77** [liip/LiipImagineBundle#844]
https://github.com/liip/LiipImagineBundle/compare/1.6.0...master

guess we should release 1.7.0 ?

wdyt @makasim @cedricziel @robfrawley @antoligy ?

**Comment by antoligy** [comment]
I've been thinking along the same lines now, it might very well be worth doing that given all of the bugfixes and updated docs.

We'll need to re-run the command for updating the changelog, but then other than that we should be good to go? ☺️

**Comment by cedricziel** [comment]
Yes, agreed. Let's do it. I'm not entirely sure i submitted #841 to the correct branch, since it's not in the comparison and the branch-alias 1.6-dev on the default branch (1.0) is still master. @robfrawley , @antoligy can you check that please?

**Comment by antoligy** [comment]
Yep, #841 is correct - I've gone ahead and cherry-picked the squashed commit into the 2.0 branch

When I get back later on, I'll go ahead and create a PR against 1.0 with an updated changelog, ready for tagging if there are no objections 😄

**Comment by robfrawley** [comment]
All good for a new minor release being tagged from my perspective!

**Comment by makasim** [comment]
I am for 1.7.0

**Comment by antoligy** [comment]
Cool, done in #845!

**Comment by antoligy** [comment]
Done - thanks for reviewing, I've also tagged and created a draft GH release - https://github.com/liip/LiipImagineBundle/releases/tag/1.7.0

Not sure if I've done this right, I notice that previous releases have a nice changelog summary (can't tell if it's auto-generated or not).  Happy to close + delete the tag, if this has been done incorrectly.  If this is correct, I am happy to surmise the various changes between 1.6.0 and 1.7.0.

**Comment by cedricziel** [comment]
I think it's okay to add the autogenerated changelog content and highlight noteworthy changes at the top. It's not autogenerated on the release record.

I've gone ahead an entered our changelog content from 1.6...1.7.

**Comment by antoligy** [comment]
Completely agreed, and thanks for that, it's looking much better!

Now, who wants to hit "publish"? 😄

**Comment by cedricziel** [comment]
Hehe. Since the tag is already set through git, people might already be having it. There's no reason to be shy :)

Since we're all fine with a new release, and because it's just a maintenance release I've gone ahead and published the Github release.

https://github.com/liip/LiipImagineBundle/releases/tag/1.7.0

Thank you all for collaborating! :tada:
