### ISSUE TITLE
Remove "master" branch, keep "1.0" as default

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#854]
@lsmith77 Can we officially remove the `master` branch at this point? We already have `1.0` set as the default branch, and any development is occurring directly on the `1.0` or `2.0`, so it's simply a duplication of effort (and needless time consumer) to continually ensure we are keeping `master` in-line with the other branches.

We had discussed this prior but never taken the step to pull the trigger and remove it. I can't do it myself, so go ahead and delete it if you're on board, or let me know otherwise if you are not. Thanks!

**Comment by robfrawley** [comment]
Ping @antoligy: let us know if feel contrary to my sentiment.

**Comment by lsmith77** [comment]
ok. will take care of it today

**Comment by lsmith77** [comment]
done

**Comment by cedricziel** [comment]
Thx to both of you! :)
