### ISSUE TITLE
Expose the ability to define custom process timeouts

### ISSUE THREAD

**Issue by alexwilson** [liip/LiipImagineBundle#857]
As of Symfony 2.4, we have the ability to define a custom timeout for processes created via the ProcessBuilder (currently only PostProcessors).

I am wondering if we should float this value to users, as I've seen in the eZ Community Slack that users are hitting the default of 60 seconds with higher levels of optimisation (in fact the default of 7!) when using optipng.

My thoughts are that either we allow a configuration variable exposing a global limit, or we add to the configuration of each individual post-processor (both general, and run-time configuration).  I lean towards the latter, as this offers more flexibility (i.e. filter `high_quality_notimeout` specifies a timeout of `null` which outright disables the ProcessBuilder timeout).

Does this make sense to implement?

**Comment by robfrawley** [comment]
:+1: The general idea is great, but I would love to see a bit more flexibility by allowing both a global configuration and a per-post-processor overwrite.

**Comment by robfrawley** [comment]
I'm working on a simple implementation that is compatible with the `1.x` branch (and by extension the `2.x` branch). It is actually relatively simple. More information to follow soon, as well as a PR. @antoligy I agree with your initial inclination that this is most useful when it can be configured individually for each post-processor. Currently, the implementation is as follows:

- No global timeout option
- Individual post-processor timeout options
  - When timeout option **is not** set, the `ProcessBuilder::setTimeout()` method is never called, resulting in the process using Symfony's default timeout value.
  - When timeout option **is** set, the `ProcessBuilder::setTimeout()` method is called to assign the timeout value (this includes integer values and `null` values to enable disabling the timeout completely).

Do the above declarations make sense? Anything about the behavior you would change or add/remove?
Are there any additional "features" that either @antoligy or @niponika can think of that would be of benefit, without greatly bloating the size of the changes? Currently, it is relatively small and simple.

For example, we could theoretically add a global timeout option, but the complexity of dealing with it (in combination with the possibility of other per post-processor timeouts that supersede it, doesn't seem worth it to me ATM.

Anyway, let me know. PR soon.

**Comment by niponika** [comment]
For me this sounds like the best thing to do!

As in the current version, the post processor can't be used by any user who has heavy inputs, or low system config (like a cheap VPS).

There is something I have been thinking about, but that isn't really an emergency.
In the current situation, when a timeout happens, the call from the client to the image returns a 500 timeout error, the browser therefore displays nothing. Although this is fine in a dev environment, in a prod environment, this could be frustrating for the user, but probably not be reported to the dev team.

I was thinking that in this situation a possible behaviour, could be to display the un-post-processed image for the user, this way he still sees the image, while logging the error to notify the devs.

Hope this all makes sens to you.

anyways, thanks to you and all the other lads who are working on the bundle for your hard work !

**Comment by franmomu** [comment]
This can be closed because of https://github.com/liip/LiipImagineBundle/pull/1219
