### ISSUE TITLE
"OutOfBoundsException" and Other Symfony 3.3 Issues

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#858]
I recently amended the `.travis.yml` build file in commit 52e2c1c224454760a2c1bea1b8d53eb1860043ee such that:

- Our default version of Symfony when testing against all versions of PHP is now `2.8` (instead of `2.7`)
- The current development version of Symfony (`3.3.x-dev`) and `master` branch are also included

---

The [subsequent Travis build log](https://travis-ci.org/liip/LiipImagineBundle/builds/195385055) shows we have some work to do toward supporting Symfony `3.3.x-dev`.

1) Cannot declare class Symfony\Component\DependencyInjection\DefinitionDecorator, because the name is already in use ([295](https://travis-ci.org/liip/LiipImagineBundle/jobs/195385425#L295))
2) Symfony\Component\DependencyInjection\Exception\OutOfBoundsException: 
  The index "1" is not in the range [0, -1] ([304 and more](https://travis-ci.org/liip/LiipImagineBundle/jobs/195385425#L304))
3) Symfony\Component\DependencyInjection\Exception\OutOfBoundsException: 
  The index "0" is not in the range [0, -1] ([312 and more](https://travis-ci.org/liip/LiipImagineBundle/jobs/195385425#L312))
4) Symfony\Component\DependencyInjection\Exception\OutOfBoundsException: 
  The index "2" is not in the range [0, -1] ([388 and more](https://travis-ci.org/liip/LiipImagineBundle/jobs/195385425#L388))

---

The majority of these errors likely have to do with the plethora of PRs and changes related to building the container that has been merged for this release, regarding auto-wiring and various other new features.

I do remember reading that `DefinitionDecorator` is being renamed to `ChildDefinition` (which *is* arguably a much more fitting name based on what it actually does), but I *thought* this wasn't the case until Symfony `4.x`. We'll have to research that a bit more, I guess.

---

Feel free to assign yourselves as well, @antoligy and @cedricziel, if you feel you also have some time to look into this. I won't be getting around to anything until the weekend, at best.

**Comment by cedricziel** [comment]
Closed through #860
