### ISSUE TITLE
Add GitHub Issue/PR Template

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#859]
Can we add an issue and PR template for GitHub? It's available in the settings panel for the repository and requires someone like @lsmith77 to change.

Taking a look at Symfony's, here is one example of what we could use for __issues__.

| Q | A
| --- | ---
| Bug Report? | yes/no
| Feature Request? | yes/no
| BC Break Report? | yes/no
| RFC? | yes/no
| Imagine Bundle Version | x.y.z

```
| Q | A
| --- | ---
| Bug Report? | yes/no
| Feature Request? | yes/no
| BC Break Report? | yes/no
| RFC? | yes/no
| Imagine Bundle Version | x.y.z

<!--
- Please take a moment to complete the template above by answering
- yes or no to the given questions and providing the bundle version.
-
- Afterward, replace this comment with the description of your issue,
- including the steps required to reproduce your issue.
-->
```

And for **PRs**

| Q | A
| --- | ---
| Branch? | 1.0 or 2.0 
| Bug fix? | yes/no
| New feature? | yes/no
| BC breaks? | yes/no
| Deprecations? | yes/no
| Tests pass? | yes/no
| Fixed tickets | 
| License | MIT
| Doc PR | 

```
| Q | A
| --- | ---
| Branch? | 1.0 or 2.0 <!--see comment below-->
| Bug fix? | yes/no
| New feature? | yes/no
| BC breaks? | yes/no
| Deprecations? | yes/no
| Tests pass? | yes/no
| Fixed tickets | <!-- #-pre-fixed issue number(s), if any -->
| License | MIT
| Doc PR | <!--highly recommended for new features-->

<!--
- Please take a moment to complete the template above by answering
- yes or no to the given questions and providing the bundle version.
-
- Afterward, replace this comment with the description of your PR.
-->
```

Can you take care of this, @lsmith77, assuming you do not object.

**Comment by lsmith77** [comment]
fine for me!

**Comment by cedricziel** [comment]
If I'm not mistaken, we can just drop them into the .github folder instead of having to add them through the settings, right?

**Comment by robfrawley** [comment]
#863 closed this; thanks!
