### ISSUE TITLE
Consider adding GitHub Topics to this repository

### ISSUE THREAD

**Issue by javiereguiluz** [liip/LiipImagineBundle#876]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | -

Dear bundle maintainer(s), if you want to make this bundle easier to discover and want to help us creating a stronger Symfony ecosystem, please consider adding some GitHub topics to this repository.

[The official Symfony recommendation](https://symfony.com/blog/standardizing-the-github-topics-for-symfony-repositories) is to add `php`, `symfony`, `bundle` and `symfony-bundle` topics ... and then, your own specific topics.

Thanks for your help!

**Comment by robfrawley** [comment]
@lsmith77 ^^

**Comment by lsmith77** [comment]
done
