### ISSUE TITLE
tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s)

### ISSUE THREAD

**Issue by kironet** [liip/LiipImagineBundle#877]
Hello,

I have a problem with this bundle. Everything works on my server(Plesk Onyx)
But after I moved my website to shared hosting, I'm getting this error. Where can I change path to the /tmp? 
BTW I tried to clear cache.

> Warning: tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/user02157/domain_name/www:/home/user02157/domain_name/.tmp:/home/user02157/domain_name/.session)

```
 public function guess($binary)
    {
        if (false === $tmpFile = tempnam(sys_get_temp_dir(), 'liip-imagine-bundle')) {
            throw new \RuntimeException(sprintf('Temp file can not be created in "%s".', sys_get_temp_dir()));
     }
```

Thank you

**Comment by cedricziel** [comment]
You should set your ini setting `sys_temp_dir` to a place you can actually write to :)

**Comment by kironet** [comment]
Thanks, but I don't have access to ini files. Can I change it in php? If so where I should place the code?

**Comment by cedricziel** [comment]
If you can't change it yourself, I'd say it's probably best to have your webhost change it for you to `/home/user02157/domain_name/.tmp`. 

Apart from that you can call `ini_set` or have your .htaccess manipulate that setting.

I'm going to close this issue now, since it's not really a problem with the bundle. - Please feel free to re-open if you think it is :)

**Comment by kironet** [comment]
I still think it is the bundle problem, because I've just printed `ini_get('upload_tmp_dir');`

and it returned this:  

> /home/user02157/domain_name/.tmp

not just

>  /tmp

**Comment by cedricziel** [comment]
Which is good - but `tempnam` uses `sys_get_temp_dir` here (https://github.com/liip/LiipImagineBundle/blob/2eafba4d25c16655b1e2937a802a1ed5357b5868/Binary/SimpleMimeTypeGuesser.php#L36) which is used for guessing the mime type. - This still leaves you with a misconfigured php environment and the bundle failing is just a symptom.

The ini settings `upload_tmp_dir` and `sys_get_temp_dir` are independant from each other and both need to be configured correctly. In your case one is, the other one isn't.

**Comment by kironet** [comment]
Oh, thanks now I get it. 
I can just say "Stupid hosting".

**Comment by cedricziel** [comment]
Hehe, good luck with that ;)
