### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#880]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | [1,2].x

I just recently created an Imagine Bundle [Slack](https://slack.com/) channel to serve as an *unofficial* support channel, as well as provide a medium for enthusiastic contributors to communicate real time and discuss code or structural changes, project directions, and other ideas.

Feel free to sign up now at https://slackinvite.me/to/imagine-php, then follow the instructions in the invitation e-mail sent to you to join the team.

**Comment by javiereguiluz** [comment]
@robfrawley is this a whole new Slack chat or a channel inside Symfony Slack? For bundles, we usually create a channel inside Symfony to leverage the existing community.

**Comment by robfrawley** [comment]
@javiereguiluz Ooh; didn't realize that. Thanks for the info!

**Comment by robfrawley** [comment]
For reference, you should use the following link to request an invite to the `symfony-devs` chat and then use the group `#imagine-bundle`.
