### ISSUE TITLE
[RFC] Consider removing the class parameters

### ISSUE THREAD

**Issue by javiereguiluz** [liip/LiipImagineBundle#885]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| Imagine Bundle Version | -

A while ago, the Symfony project decided that using `.class` parameters was a bad practice. More and more bundles are removing those parameters (e.g. https://github.com/symfony/monolog-bundle/pull/170)

Would you consider removing those parameters in your bundle? Thanks!

**Comment by antoligy** [comment]
I completely agree with this, and have started removing .class parameters elsewhere.

**Comment by robfrawley** [comment]
We currently rely on some parameters for functionality (such as the metadata reader), but I think this would be a solid feature for our next major release (`2.0.0`). Any takers on implementing this? ;-)

**Comment by rpkamp** [comment]
I'll take a stab at it :smiley:

**Comment by Koc** [comment]
done in #914

**Comment by garak** [comment]
It looks like this issue should be closed (just to be closer to release 2.0.0)

**Comment by robfrawley** [comment]
@garak Good call!
