### ISSUE TITLE
Wrong documentation imagine_filter filter

### ISSUE THREAD

**Issue by PGLongo** [liip/LiipImagineBundle#889]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| Imagine Bundle Version | 1.7.2

In the [documentation](http://symfony.com/doc/master/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails) is written:

```html
<img src="{{ asset('/relative/path/to/image.jpg') | imagine_filter('my_thumb') }}" />
```

But it doesn't work for me. I've to change as follow:

```html
<img src="{{ asset('/relative/path/to/image.jpg' | imagine_filter('my_thumb') ) }}" />
```

It's necessary to apply the filter before assets. 

Am I wrong?

**Comment by rpkamp** [comment]
I would suggest that it depends where you cache your processed images. If they are stored somewhere in your web directory both approaches work, but if they are stored outside of your web directory only the second approach works.

So the question is, what configuration are you using for the bundle / where are you storing cached images?

**Comment by homersimpsons** [comment]
I had to do this even with cache under `web/`. In fact I had this error:
```Source image not resolvable "project/web/uploads/24.png" in root path(s) "/home/www-data/html/project/web"```

If both should work but the second one is more general why the doc doesn't show only the second one (or at least both)

**Comment by dbu** [comment]
i am cleaning up old issues. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
