### ISSUE TITLE
 Changes in Aws Definition

### ISSUE THREAD

**Issue by plozmun** [liip/LiipImagineBundle#892]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | yes
| RFC? | yes
| Imagine Bundle Version | 1.7.3

When update at this version i got error:

`Cannot dump definition because of invalid class name ('\\Aws\\S3\\S3Client') `
Can be related to this [Changes in Aws Definition](https://github.com/liip/LiipImagineBundle/compare/1.7.2...1.7.3#diff-5584d98c341355797ea40fde49e441b1L28) ?

**Comment by Chrysweel** [comment]
+1

**Comment by cedricziel** [comment]
Please comment on #893 whether this fixes it for you. Thank you!
