### ISSUE TITLE
Failed to create (...) mkdir(): File exists.

### ISSUE THREAD

**Issue by thomas2411** [liip/LiipImagineBundle#898]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.1

I have a weird behavior on Symfony 3.2 and don't know if this is a configuration problem or what, but when I use Cache manager in Controller to resolve a path to the image I get this error:

> Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Failed to create "/home/admin/domains/[cutoff]/public_html/app/../web/media/cache/icon_api/uploads/icon/09FDD72-DFAE-D89E-4266-3905D5D69D9D": mkdir(): File exists." at /home/admin/domains/[cutoff]/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php line 100

I try to resolve a path to a filtered image (thumbnail with optimization). I get this error only for the first time, when the thumbnail is created. The thumbnail is created and served but the crash is shown. Any idea what is going on?

**Comment by endelwar** [comment]
This is still valid for symfony 4.2.8 with Imagine Bundle version 2.1.0

**Comment by angelomelonas** [comment]
Also getting this error on Symfony 5.

**Comment by christianostrem** [comment]
Also getting this error on Symfony 5.1
Version 2.5 of liip

[2021-09-06T08:28:17.841199+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Failed to create "/data/var/storage/default/cache/xxl/files/uploads/a920b8ad-4b04-11eb-9432-005056bf3d73/eb063493225441d08772633b4f2dddaa": mkdir(): File exists" at /srv/sites/x/htdocs/vendor/symfony/filesystem/Filesystem.php line 100 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Failed to create \"/data/var/storage/default/cache/xxl/files/uploads/a920b8ad-4b04-11eb-9432-005056bf3d73/eb063493225441d08772633b4f2dddaa\": mkdir(): File exists at /srv/sites/x/htdocs/vendor/symfony/filesystem/Filesystem.php:100)"} []

We have a very active image upload service with daily image uploads and get this  error a lot.

**Comment by dbu** [comment]
do you have a stack trace for it?

at this point, is there a file with the name at that location where it tries to create the directory?

looking at the code in Filesystem, i think if a directory would already exist, it would silently not do anything. but the check is `is_dir`, so if there is a file with that name, it will try to create a folder with the same name as the file.

i would be glad if you can debug this a bit and maybe propose a fix. my suspicion is that there is a file with the same name as the folder we try to create.

**Comment by ibrahim-zehhaf** [comment]
Hi @dbu 
I have the same pb since i migrated my infra on aws with EFS, I never see this error before migration when my app was on mono server.

now I have 2 servers with ELB, I think it caused by concurrency access because tow servers receive the same request at the same time.

**Comment by ibrahim-zehhaf** [comment]
The error is coming from Symfony FileSystem here https://github.com/symfony/filesystem/blob/e58d7841cddfed6e846829040dca2cca0ebbbbb3/Filesystem.php#L104

**Comment by dbu** [comment]
hi @ibrahim-zehhaf , i am no expert on distributed filesystems. looking at the linked thing from symfony Filesystem, it seems like it would try to continue and if the directory now exists, the process continues. are you sure that there is a directory and not a file at that place? 

can you post the exact message you get, maybe that gives a more precise hint what is happening?

maybe you could use the queue mechanism and implement a cache warmup, to reduce the risk of race conditions?

**Comment by ibra-iad** [comment]
Hi @dbu thank you for your response

Yes I am sur that there is a directory
here is my sf log 
```
Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Failed to create "/var/www/html/releases/20211211133942/web/upload/cache/small_370x210/upload/message/5d/c2/be": mkdir(): File exists" at /var/www/html/releases/20211211133942/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php line 104
Level
CRITICAL
```
yes I can warmup the image cache but this solution is not optimal for me, because I need preserve my EFS disk space, so I don't want to generate all the cache but only the visited images.

the cache is generated on the fly by the web liip filter  https://xxxx.com/media/cache/resolve/small_370x210/upload/message/5d/c2/be/5dc2be00d1938282886810.jpg

**Comment by dbu** [comment]
so weird, as the symfony Filesystem would skip the exception if creating the directory fails but the directory now exists, from how i read the code. are you sure that at that point, it is a directory and not a file?

another thing i could think of to work around the problem could be to add a semaphore system to avoid race conditions, using filter & filename as semaphore key.

does it happen very often? it seems unlikely to me that a race condition would constantly happen, you'd have to hit the same image within the same millisecond or so normally, unless the filesystem is somehow extremly slow...

**Comment by ibra-iad** [comment]
No it does not happen very often, I have 2 or 3 errors per day knowing that the image is cached by the CDN once generated.
I think the EFS is slow since I am on a low IOPS.

I remind you that on my old infra in mono server without NFS, I did not have this problem.

**Comment by dbu** [comment]
alright. i think your options are the semaphore, or to retry the whole thing on failure. 

i don't think we can do anything inside the bundle, as it must be some weird edge case of the filesystem setup (as Filesystem.php checks upon error if the directory now exists and continues without error in that case)

actually, maybe you could try to use the flysystem resolver instead of a cache resolver based on the (virtual) filesystem. maybe flysystem can handle the operations more reliable.

**Comment by Jalliuz** [comment]
If it can help anyone, the error stopped when I changed permissions on the folder
`chmod -R 755 path/to/web/media`
