### ISSUE TITLE
Watermark SVG not working

### ISSUE THREAD

**Issue by jeffsacco** [liip/LiipImagineBundle#899]
Anyone tried using an SVG for the watermark image?  I had success with regular images for the watermark but was looking to use an SVG. Totally died.  Couldn't read it.

Is it possible to use an SVG for the watermark image?

**Comment by pculka** [comment]
Just stumbled across this - would be a cool feature

**Comment by dbu** [comment]
i am cleaning up old issues. sorry that you got no response. if this is still relevant and keeps happening with the latest version of the bundle, please reopen the issue.
