### ISSUE TITLE
Removing manual image from cache

### ISSUE THREAD

**Issue by fkrauthan** [liip/LiipImagineBundle#90]
It would be greate if there is a service methode like `deleteImage(OriginalPath);` Which deletes this image from all caches if it exists. Or `deleteImage(OriginalPath, 'thumbName');` For deleting a image in a special thumb config. And a Console command for clearing the image cache would be also good (So there is no need to delete the complete cache just the image cache).

**Comment by wessel-techtribe-nl** [comment]
In symfony 4:

`
services.yaml
services:
    Liip\ImagineBundle\Imagine\Cache\CacheManager:
        alias: 'liip_imagine.cache.manager'

controller:
`
use Liip\ImagineBundle\Imagine\Cache\CacheManager;

    private $cacheManager;

    public function __construct(
        CacheManager $cacheManager
    ){
        $this->cacheManager = $cacheManager;
    }
`
