### ISSUE TITLE
Remove cache for a single source image

### ISSUE THREAD

**Issue by malas** [liip/LiipImagineBundle#901]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.4

is there any way to remove all filters cached images for a single source image?
This is a common use case for any CMS when previously stored images are deleted. I wanted to implement this via PRE_REMOVE event for an Image entity.

**Comment by robfrawley** [comment]
See the [cache manager documentation](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-manager.html#cache-removal) for more information.

**Comment by malas** [comment]
There is no information regarding single image's all filter removal. Currently i just hardcoded available filter paths and remove the files manually.

**Comment by robfrawley** [comment]
You need to specify the filters you want to remove. All operations are per-filter. If you'd like to submit a PR exposing the functionality you'd like, feed free to do so, though.
