### ISSUE TITLE
Is a thumbnail created while the original file is already small?

### ISSUE THREAD

**Issue by Kwadz** [liip/LiipImagineBundle#905]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.4

When I try to display a thumbnail with:

`<img src="{{ artiste.image.webPath | imagine_filter('my_thumb') }}" />`

I get the following error in the case the original picture is already small (no problem with large pictures):

`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "liip_imagine_filter" as such route does not exist.").`

**Comment by robfrawley** [comment]
@Kwadz You need to register the routes in your application. You should follow the [installation instructions](http://symfony.com/doc/current/bundles/LiipImagineBundle/installation.html#step-3-register-the-bundle-s-routes), specifically how to [register the routes](http://symfony.com/doc/current/bundles/LiipImagineBundle/installation.html#step-3-register-the-bundle-s-routes).

**Comment by Kwadz** [comment]
Indeed, I removed it by mistake.
Thanks

**Comment by robfrawley** [comment]
@Kwadz No worries; glad to help.
