### ISSUE TITLE
How to remove domain from URL while using imagine_filter ?

### ISSUE THREAD

**Issue by webtsx** [liip/LiipImagineBundle#907]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | yes
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 1.7.4

I am trying to use your bundle, but when I apply 
{{ asset(img) | imagine_filter('thumb') }} I get 
http://domain.com/media/cache/resolve/thumb/image.jpg
but I would like to get /media/cache/resolve/thumb/image.jpg without domain?
How can I do this ?

Thank you in advance.

**Comment by robfrawley** [comment]
By default, you are using the [`WebPathResolver`](https://github.com/liip/LiipImagineBundle/blob/1.0/Imagine/Cache/Resolver/WebPathResolver.php), which does include the domain. You can extend that resolver and make the required changes to have it return only the path. For additional information on writing your own cache resolver, and more importantly, registering and using that cache resolver, reference the [custom cache resolver documentation](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolvers.html#custom-cache-resolver).

**Comment by robfrawley** [comment]
FYI, the only method you need to change is [WebPathResolver.php#L68](https://github.com/liip/LiipImagineBundle/blob/1.0/Imagine/Cache/Resolver/WebPathResolver.php#L68).

**Comment by robfrawley** [comment]
@webtsx A more extensive answer describing custom cache resolvers is available here: https://github.com/liip/LiipImagineBundle/issues/910#issuecomment-294364254. Has your issue been resolved? Please close this issue if it has, or otherwise, let me know what issues you are facing.

**Comment by webtsx** [comment]
@robfrawley Sorry for my delayed response, but I didn't have much time to check this solution. 
It works like I needed. Thank you very much for your quick feedback!

**Comment by othbert** [comment]
Hi there,

Is this still the correct strategy? I took the default package and extended the webpathresolver, modified just the resolve command, and pass back just the path without the scheme and host/domain. But now I get errors with the bundle trying to create a 'cache' directory in my root filesystem /media directory! I can verify that with running the bin/console liip:imagine:cache:resolve command for the filter, it fails normally, but running it with sudo creates the directory in my filesystem root.

```
In Filesystem.php line 104:
                                                                               
  Failed to create "/media/cache/full_width/media/image/3a/37": mkdir(): Permission denied.
```

Would appear to be that the resolve method is used to calculate the file in filesystem location then?
