### ISSUE TITLE
How Create a resolver that create filters that points to a subdomain, a subdomain prefix

### ISSUE THREAD

**Issue by raphydev** [liip/LiipImagineBundle#915]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | ^.1.6

Please, I need a track
I use Liip_imagineBundle to crop my images, I upload my images to a folder pointing to a subdomain: / var / www / imgs => img.example.com, I have installed the Bundle LiipImagineBundle Have filters that crop images and stock into a subdomain folder too, for example: / var / www / imgs / thumbs / media / cache, and has the display I'd like to have img.example.com / Path-of-thumb-image. If someone has a track it will be of great help to me 4 days I block.

**Comment by robfrawley** [comment]
You can easily create a custom cache resolver, as [detailed in the official documentation](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolvers.html#custom-cache-resolver), and have it return whatever domains you'd prefer, as well as manage what directory structure you use to write and fetch the cached images. For additional information, see the https://github.com/liip/LiipImagineBundle/issues/910#issuecomment-294364254 I wrote a few days ago,

**Comment by raphydev** [comment]
Thanks @robfrawley , I'm looking for how to write a custom resolver and if it works then I would put the solution and then close the issue. I am always open to other proposals

**Comment by raphydev** [comment]
@robfrawley , Instead of creating a custom resolver, the ProxyResolver can set this history, but I can not configure it properly

**Comment by raphydev** [comment]
No solution

**Comment by robfrawley** [comment]
@raphydev Did you intend to close this? Anyway, you can absolutely do what you described by using a custom resolver (as I previously described). Have you tried that? If you have, what is the issue you are having with it?
