### ISSUE TITLE
How to display image without saving to disk

### ISSUE THREAD

**Issue by marcobarcaro** [liip/LiipImagineBundle#916]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | master

Hi, is it possible to apply a filter and display the relative image without saving it to disk?

**Comment by makasim** [comment]
Take a filter manager service and pass image binary to its apply method, and a config as a second argument.

**Comment by marcobarcaro** [comment]
I created a custom filter:

`<?php
namespace AppBundle\Imagine\Filter\Loader;

use JMS\DiExtraBundle\Annotation as DI;
use Imagine\Image\Box;
use Imagine\Filter\Basic\Show;
use Imagine\Filter\Basic\Resize;
use Imagine\Image\ImageInterface;
use Liip\ImagineBundle\Imagine\Filter\Loader\LoaderInterface;

/**
 * @DI\Service("filter.show_filter")
 * @DI\Tag("liip_imagine.filter.loader", attributes = {"loader" = "show_filter"})
 */
class ShowFilterLoader implements LoaderInterface
{
	/**
	 * @see Liip\ImagineBundle\Imagine\Filter\Loader\LoaderInterface::load()
	 */
	public function load(ImageInterface $image, array $options = array())
	{
		$width = isset($options['size'][0]) ? $options['size'][0] : null;
		$height = isset($options['size'][1]) ? $options['size'][1] : null;		
		$quality = isset($options['quality']) ? $options['quality'] : 90;
		
	    $size = $image->getSize();
        $origWidth = $size->getWidth();
        $origHeight = $size->getHeight();

        if (null === $width || null === $height) {
            if (null === $height) {
                $height = (int) (($width / $origWidth) * $origHeight);
            } elseif (null === $width) {
                $width = (int) (($height / $origHeight) * $origWidth);
            }
        }

        $filter = new Resize(new Box($width, $height));
		$image = $filter->apply($image);

        $filter = new Show('jpg', array(
        	'jpeg_quality'=>$quality
        ));
        
        return $filter->apply($image);
	}
}`

with a custom cache resolver with this methods:

`   /**
     * {@inheritdoc}
     */
    public function isStored($path, $filter)
    {
        return false;
    }

    /**
     * {@inheritdoc}
     */
    public function store(BinaryInterface $binary, $path, $filter)
    {
    }

    /**
     * {@inheritdoc}
     */
    public function remove(array $paths, array $filters)
    {
    } `

and it works!

**Comment by cedricziel** [comment]
Great - thank you for the feedback! :)
