### ISSUE TITLE
Create my thumb on a subdomain

### ISSUE THREAD

**Issue by raphydev** [liip/LiipImagineBundle#917]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? |no
| RFC? | no
| Imagine Bundle Version | ^.1.6

what I have done:

1. I upload my images to a subfolder of a subdomain called: http://img.labs.dev
2. My main domain is http://www.labs.dev
3. To retrieve an image source I configure the assets in config.yml in this way : 
`framework:`
    `assets:`
       ` packages:`
            `cssjs:`
                `base_urls: 'http://img.labs.dev/assets'`
            `images:`
               ` base_urls: 'http://img.labs.dev/tp_images'`

With this configuration I recover well my images of the subdomain

This is my problem: 
1. I want to create thumbs, which create the caches of images in a folder of the subdomain with LiipImagineBundle

2. Has the recovery of my caches create I want the images to be called with the absolute url of my sub-domain example: http://www.img.labs.dev/tp_images/resolver/media/cache/lien_de_image.jpg

3. how to do?

NB: Need a concrete solution it's been 10 days I block on the principle

**Comment by robfrawley** [comment]
Please do not pollute the issue tracker with intentionally created duplicates: #915.

**Comment by robfrawley** [comment]
I am having trouble following your English; perhaps you can post your issue description again using your native language? (I can then use https://translate.google.com/ and see if that gets us moving forward...)
