### ISSUE TITLE
Symfony documentation website versions selector issues

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#929]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes/no
| Imagine Bundle Version | 1.7 & 1.8 & 2.0

The Symfony documentation website, specifically [the `liip/imagine-bundle` section under `Bundles/`](http://symfony.com/doc/master/bundles/LiipImagineBundle/index.html), __incorrectly__ states version `1.3/master`, whereas it should display version `1.8`. Additionally, we also now have a `2.0` branch, which should be labeled as the `master` branch on the Symfony website. Moreover, we have a `1.7` version that has some incompatibilities with `1.8`, is there any way to show our `1.7` version as well?

@javiereguiluz @xabbuh I know you two are frequently involved with the Symfony documentation. Can you help with this? Or perhaps you can point us in the direction of who/where to talk about this with? Do we need to lay out our repository in a specific way for it to properly display versions? Thanks for any help you can provide.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. On symfony.com we can only list branches not tags, so we can't show the "1.7" version, but the "1.0" branch. I've changed the following:

### Before

![liip-imagine-before](https://cloud.githubusercontent.com/assets/73419/25887457/8d429c90-3562-11e7-81ac-6ca94fd12c7b.png)

### After

![liip-imagine-after](https://cloud.githubusercontent.com/assets/73419/25887463/915a066a-3562-11e7-938e-efef649360a1.png)

**Comment by robfrawley** [comment]
Thanks so much @javiereguiluz!

**Comment by javiereguiluz** [comment]
Note: this has been merged on the symfony.com repo but it could take a bit until is deployed on production.

**Comment by robfrawley** [comment]
I figured as much; no worries, and appreciate the quick turn around on this.
