### ISSUE TITLE
Working example for remote images via http?

### ISSUE THREAD

**Issue by StefanGlaesser** [liip/LiipImagineBundle#936]
Hello,

I need an working example for symfony 3.2 with custom data loader and custom cache. I've found nothing about that in documentation. My project needs to fetch the images through http [file_get_contents($remotePath)] and then cache them localy, before displaying it. 

Can anyone provide such an example please?

**Comment by robfrawley** [comment]
You can find information on [custom data loaders](http://symfony.com/doc/current/bundles/LiipImagineBundle/data-loaders.html#custom-data-loader) and [custom cache resolver](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolvers.html#custom-cache-resolver) in the documentation. I also suggest checking out the [documentation index](http://symfony.com/doc/current/bundles/LiipImagineBundle/index.html) which contains references to both of these items and more.

**Comment by robfrawley** [comment]
@StefanGlaesser Please feel free to re-open if this issue has persisted.
