### ISSUE TITLE
Retina

### ISSUE THREAD

**Issue by kironet** [liip/LiipImagineBundle#938]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | last one

Hey,

is it possible to somehow intergrate retina support? 
If retina show double size.

Or how to generate 2 images.
first one car.jpg
second one car@2x.jpg

Thanks

**Comment by robfrawley** [comment]
At the moment, you can just define two separate filter sets for normal and retina displays.

**Comment by kironet** [comment]
@robfrawley thank. Sorry, but how to generate two images with different name
car.jpg nad car@2x.jpg? 

Right now i'm doing it like it is shown in documentation:

`<img class="replace-2x" src="{{ asset('/path/to/car.jpg') | imagine_filter('thumb') }}" />`

Thanks
