### ISSUE TITLE
Best practice for a filter_set with multiple DataLoader

### ISSUE THREAD

**Issue by winzou** [liip/LiipImagineBundle#948]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 1.7.1

Hello,

I have a usecase where I need to apply the same filters on the images coming from 2 different data loader:
* A Stream loader, Gaufrette, where user-uploaded images are
* A Filesystem loader, where some static images are

What is the best practice to apply the same filters on these images? I didn't find anything like `CascadeDataLoader` that could return the first existing image in multiple data loaders. Or is it better to define 2 different filter_sets and find a way to factorize their parameter (same thumbnail size, same post_processors, etc.) ?

Thanks for your help!

**Comment by robfrawley** [comment]
Give #953 a try and let me know how it works for you.

**Comment by winzou** [comment]
Thanks, I went for the chained loader. It works like a charm!

**Comment by robfrawley** [comment]
@winzou Glad that the new `chain` loader worked out well for you!
