### ISSUE TITLE
Resolve image by url instead of filesystem path

### ISSUE THREAD

**Issue by pzaj2** [liip/LiipImagineBundle#955]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.2

Hi

I'm looking for information whether it is possible to resolve path based on provided URL? I'm not sure how to explain it, so let me do this using an example. I have a route: `https://example.org/uploads/{identifier}`, that leads to a controller which:
1. Check permissions
2. Resolve actual image path
3. return BinaryResponse containing the image

I would like to generate a thumbnail with watermark (although this is not relevant here) for this image, so ideally I would like to pass my URL or part of URL (`/uploads/{identifier}`) to imagine_filter twig filter and get thumbnail generated from actual image.

Any idea how this could be accomplished?

**Comment by robfrawley** [comment]
Reference the [custom data loader](http://symfony.com/doc/master/bundles/LiipImagineBundle/data-loaders.html#custom-data-loader) documentation.
