### ISSUE TITLE
PDF thumbnail generation

### ISSUE THREAD

**Issue by pzaj2** [liip/LiipImagineBundle#956]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 2.7.2

Hello

I would like to know whether PDF thumbnail generation is supported by this bundle in any way? I didn't find anything in documentation and I'm not very familiar with bundle nor Imagine internals, so I thought of asking. I believe this question has two parts, one being if this bundle supports it and the second is if Imagine supports it at all, since as far as I understand, to build a filter for the bundle Imagine needs to support it, right?

Any tips will be highly appreciated :)

P.S.
I did find an open issue, but it is dated back at 2014 and refers to 0.x - 1x version of this bundle, whereas I believe there has been a lot of changes since then.

I know this could be easily done directly, outside the bundle, but I'd like to keep this as a part of the bundle if possible.

**Comment by robfrawley** [comment]
[Imagine](https://imagine.readthedocs.io/en/latest/), the underlying library used by this bundle, uses one of three drivers, "gd", "imagick", or "gmagick", which are PHP extensions. While I know "imagick" and "gmagick" can read in PDFs, I believe "gd" can as well. File version support will, however, be constrained by the driver you use. See the documentation for [gd](https://secure.php.net/manual/en/book.image.php), [imagick](http://php.net/manual/en/book.imagick.php), and [gmagick](http://php.net/manual/en/book.gmagick.php) for additional information. Once you have settled on and installed the driver you'd like, activate it via the `liip_imagine.driver` configuration option:

```yml
# app/config/config.yml

liip_imagine:
  driver: "gd" # or "imagick" or "gmagick"
```

**Comment by pzaj2** [comment]
thank you @robfrawley these are the thing I'm aware of already. I'm actually looking for a configuration reference that would allow such PDF -> jpg thumbnail generation or, if LiipImagine does not have buil-in support for that, any suggestions of how to implement this. I know how to do this with imagick in vanilla PHP, but I'm not that familiar with Imagine's internals and relation between all the classes it consists of

**Comment by cedricziel** [comment]
Most webservers are configured to add headers by file extension. I think what you want is not possible in `LiipImagineBundle`s current state, since we rely heavily on the correctness of file extensions for everything we do.

All you could do is to either modify the existing namers, loaders and resolvers to be able to use a file extension such as `*.pdf.jpg`. To have pseudo-correct file names for resolving them

**Comment by robfrawley** [comment]
Give the following a try:

```
use Liip\ImagineBundle\Binary\SimpleMimeTypeGuesser;
use Liip\ImagineBundle\Model\Binary;
use Liip\ImagineBundle\Model\FileBinary;
use Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesserInterface;

class PdfToJpegDataLoader implements LoaderInterface
{
    /**
     * @var SimpleMimeTypeGuesser
     */
    protected $blobMimeGuesser;

    /**
     * @var ExtensionGuesserInterface
     */
    protected $extensionGuesser;

    /**
     * @var FileSystemLoader
     */
    protected $fileSystemLoader;

    /**
     * @param SimpleMimeTypeGuesser     $blobMimeGuesser
     * @param ExtensionGuesserInterface $extensionGuesser
     * @param FileSystemLoader          $fileSystemLoader
     */
    public function __construct(SimpleMimeTypeGuesser $blobMimeGuesser, ExtensionGuesserInterface $extensionGuesser, FileSystemLoader $fileSystemLoader)
    {
        $this->blobMimeGuesser = $blobMimeGuesser;
        $this->extensionGuesser = $extensionGuesser;
        $this->fileSystemLoader = $fileSystemLoader;
    }

    /**
     * {@inheritdoc}
     */
    public function find($path)
    {
        $file = $this->fileSystemLoader->find($path);

        if(false === strpos($file->getMimeType(), 'pdf')) {
            throw new \LogicException(sprintf('The mime type of pdf %s must be application/pdf got %s.', $path, $file->getMimeType()));
        }

        return $this->convertToJpeg($file);
    }

    /**
     * @param FileBinary $file
     *
     * @return Binary
     */
    private function convertToJpeg(FileBinary $file)
    {
        $im = new \Imagick();
        $im->setResolution(300, 300);
        $im->setColorspace(\IMagick::COLORSPACE_RGB);
        $im->readImage(sprintf('%s[0]', $file->getPath()));
        $im->setImageFormat('jpeg');

        $blob = $im->getImageBlob();
        $mime = $this->blobMimeGuesser->guess($blob);

        return new Binary($blob, $mime, $this->extensionGuesser->guess($mime));
    }
}
```

**Comment by pzaj2** [comment]
@cedricziel to be honest, I would think that the browser checks mime type of the file before opening it, but apparently it does not.

Well, for now I found an ugly workaround that works just fine, but I thought there was a proper way for LiipImagineBundle. Anyway, if anyone would like to use similar approach:

1. Replace the extension on the path BEFORE passing to twig filter (or however you pass the path to `LiipImagineBundle`).

**Comment by cedricziel** [comment]
Well, it does - if the mime type is generic such as `application/octet-stream`, but if the headers are specific, why should the browser bother ? :)

**Comment by pzaj2** [comment]
@cedricziel 
You're probably right, but doesn't this create a vulnerability where you can prepare a file to be recognized as another type and try to run arbitrary code in browser? Of course I'm just thinking loud, I suppose browsers are secured in case of this. Anyway, I will stick to my solution for now and perhaps when I have a bit more time I will dive deeper into bundle's internals and try to find a better way. Thanks :)

**Comment by cedricziel** [comment]
Sure thing - there have been such attacks in the past and that's why encryption is vital to every part of the web and we need to enforce it with every breath we take :)
