### ISSUE TITLE
Rotate PNG files

### ISSUE THREAD

**Issue by pengend** [liip/LiipImagineBundle#964]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.3

Hello, 

I tried to rotate an PNG file with transparent area using GD driver, and the area becomes black after the rotation. Then I read several posts about this issue, apparently some image manipulation functions must be executed before the rotation to keep the image transparency, but this is not done in the method of the class `Imagine\Gd\Image`, unless we add other options like `crop`, `resize` etc.

**Comment by robfrawley** [comment]
I'd be happy to review a PR amending the rotation filter!

**Comment by antoligy** [comment]
Hey!  As a pointer to any possible contributors, would you mind sending through any information you already have about the issue at hand @pengend?

Cheers!

**Comment by pengend** [comment]
Yea, of course. 

The private method createImage of the class `Imagine\Gd\Image`generates a image ressource which already allows manipulation with PNG image transparency. 

`
        $transparent = imagecolorallocatealpha($resource, 255, 255, 255, 127);
        imagefill($resource, 0, 0, $transparent);
        imagecolortransparent($resource, $transparent);
`

if this method is not called, the property `resource` `Imagine\Gd\Image` does not consider the file like PNG files, and manipulates it like a JPEG one. 

The problem is this method is used only in `copy`, `crop`, `resize`, `slip` methods, and NOT IN `rotate`, that's why the transparency is not kept when we call only `rotate` method.

**Comment by robfrawley** [comment]
So, this is a change that needs to be reported to [avalanche123/Imagine](https://github.com/avalanche123/Imagine) then, right? Or is there something we can do in *this* bundle to resolve it?

**Comment by pengend** [comment]
Right, my mistake, this should be reported to [avalanche123/Imagine)](https://github.com/avalanche123/Imagine).

**Comment by robfrawley** [comment]
Please link to this issue from the new issue you create in the [avalanche123/Imagine](https://github.com/avalanche123/Imagine) repository. That way others who may experience the same issue can easily find and track progress. Thanks!
