### ISSUE TITLE
Using a CDN and filters without cache

### ISSUE THREAD

**Issue by pdoreau** [liip/LiipImagineBundle#971]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.8.0

I'd like to use filters with dataloaders and image manipulations but no caching. The controller would simply return the manipulated images as binary respone every time. The idea is to let my CDN store the response.

The advantages are : 

 * get rid of resolvers complexity (cache location and configuration, enqueue etc.)
 * do not rely on a Redirect response to avoid issues with Varnish for example
 * manipulations would still be done once, just like if a resolver was used

Is that possible ? What would be the disadvantages if any ?

**Comment by tux240** [comment]
Same issue for me

Any idea ?

**Comment by robfrawley** [comment]
Can't you simply implement your own null-cache? We support custom cache implementations, so you should be able to handle this however you'd like using the current architecture, no?

**Comment by pdoreau** [comment]
@robfrawley cache resolvers are supposed to store manipulated images somewhere but I'd like to store nothing neither provide a resolved string.
So how can I implement a null-cache in such way image manipulation are done for every calls ?

**Comment by robfrawley** [comment]
Right, I answered without thinking: the architecture requires you store the initial manipulated image somewhere, as it is not directly served by the same route as it is created.

**Comment by pdoreau** [comment]
Well, the main issue is response time, which is slow when the response contains images urls. Indeed, storage backend calls has to be done for each images to check it they are cached or not.

I can cache those backend calls (with [flysystem-cached-adapter](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/filesystem_cache.md) for example) but I'm working with containers which are killable at anytime (Kubernetes) so nothing has to be store on it. I guess Redis would be appropriated for this kind of cache. Still, the first response would be slow...unless I properly use `enqueue` and don't forget it when a new resource is created for example.

So with the current architecture, I would need to add and configure (tell me if I'm wrong) : flysystem-cached-adapter, Redis, enqueue (without forgetting in actions).
With a controller without cache (just manipulation / filters), I would only need a CDN and the bundle itself.

Right, I don't use Varnish but it's mentioned in the [documentation](https://symfony.com/doc/current/bundles/LiipImagineBundle/resolve-cache-images-in-background.html) : 
> The varnish may cache the page with those links to the resolve controller. A browser keeps sending requests to it though there is no need for it after the first call.

That would also be solved with a controller without cache and a CDN.

**Comment by pdoreau** [comment]
I finally coded a custom filterAction which basically do 3 things :

* find the original image
* compute the manipulated version
* return the data as a Response
```
$binary = $this->dataManager->find($filter, $path);
$binary = $this->filterManager->applyFilter($binary, $filter);
return new Response($binary->getContent(), 200, ['Content-Type' => $binary->getMimeType()]);
```
I use the associated route when images urls are generated, concatenated with my CDN base.
It works well. Do you see any drawback ? Would it be interesting / difficult to make this code available in the bundle ?

**Comment by robfrawley** [comment]
Happy to hear you resolved the issue. Feel free to submit a PR if you believe the feature you've created adds value for others.

**Comment by picks44** [comment]
Hi @pdoreau, I'd be very interesting in seeing your solution, I'm currently migrating to Azure Cloud with a CDN and I want to be able to use this bundle with it. Can you help ?
