### ISSUE TITLE
Could not load type "file" in symfony 3

### ISSUE THREAD

**Issue by jorisros** [liip/LiipImagineBundle#976]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 2.0

After using the ImageType of the LiipImagineBundle in a form i receive the error 'Could not load type "file"'.

**Comment by jorisros** [comment]
There is a pull request for solving this issue #975

**Comment by robfrawley** [comment]
Closed via #975.
