### ISSUE TITLE
Thumbnail only show with "app.php" in url

### ISSUE THREAD

**Issue by afsharfarnia** [liip/LiipImagineBundle#977]
This is my first page URL with many images. I want to filter them with LiipImagineBundle and make their thumbnails.
http://fkcc.afshar/news

Unfortunately, thumbnails are not created. But when I add "app.php" to the URL, it works and I can see all thumbnails.
Like that: http://fkcc.afshar/app.php/news

What is the problem?

**Comment by cedricziel** [comment]
It's most likely a problem with your rewrite configuration on the webserver. Many webservers like nginx have a standard rewrite configuration that short circuits requests when file extensions like `.jpg` or `.png` are encountered.

**Comment by afsharfarnia** [comment]
Thanks for your answer.
My nginx configuration is like following. Please let me know which part must be changed?

upstream rayshp {
    server unix:/var/run/php/php7.0-fpm-RaySHP.sock;
}

server {
    listen      80 default_server;
    listen      [::]:80;

    server_name RaySHP.localhost www.RaySHP.localhost;
    root        /srv/www/RaySHP/web;

    tcp_nopush on;
    tcp_nodelay on;

    server_tokens off;
    autoindex off;

    client_max_body_size 1M;

    add_header      X-Content-Type-Options          "nosniff"                   always;
    add_header      X-Frame-Options                 "deny"                      always;
    add_header      X-XSS-Protection                "1; mode=block"             always;

    add_header      X-Ray                           "RayvarzSE Portal Team"     always;
    add_header      X-Powered-By                    "RaySHP"                    always;

    error_log /var/log/nginx/error.RaySHP.log;
    access_log /var/log/nginx/access.RaySHP.log;

    include snippets/RayGZIP.conf;

    location / {
        try_files $uri /maintenance.html /app.php$is_args$args;
    }

    location ~ ^/(app|app_dev)\.php(/|$) {
        fastcgi_pass rayshp;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ \.php$ {
        return 404;
    }

    location /nginx-status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ \.(?:jpg|jpeg|png|gif|ico|css|js|txt|ttf|ttc|otf|eot|woff|woff2)$ {
        expires 14d;
    }

}

**Comment by cedricziel** [comment]
What's in that inlcuded snippet?

**Comment by afsharfarnia** [comment]
Its as following:

gzip                    on;
gzip_http_version       1.1;
gzip_types
    # text/html is always compressed by gzip module
    text/css
    text/javascript
    text/xml
    text/plain
    text/x-component
    application/javascript
    application/x-javascript
    application/json
    application/ld+json
    application/manifest+json
    application/x-web-app-manifest+json
    application/xml
    application/xhtml+xml
    application/rss+xml
    application/atom+xml
    font/truetype
    font/opentype
    application/vnd.ms-fontobject
    application/x-font-ttf
    image/bmp
    image/svg+xml
    image/x-icon;
gzip_proxied            any;
gzip_disable            "msie6";
gzip_vary               on;
gzip_comp_level         6;

**Comment by afsharfarnia** [comment]
I deleted this line:
`include snippets/RayGZIP.conf;`

But I have still that problem.
Please help me to solve that.

**Comment by robfrawley** [comment]
See the following comment for a working Nginx example: https://github.com/liip/LiipImagineBundle/issues/784#issuecomment-320150743.

**Comment by robfrawley** [comment]
@afsharfarnia Are you still experiencing any problems or can this issue be closed?

**Comment by afsharfarnia** [comment]
In nginx configuration file, I deleted following sentence and it works.

```
location ~ \.(?:jpg|jpeg|png|gif|ico|css|js|txt|ttf|ttc|otf|eot|woff|woff2)$ {
        expires 14d;
}
```
