### ISSUE TITLE
ChainLoader is not part of any tag

### ISSUE THREAD

**Issue by mmp4k** [liip/LiipImagineBundle#978]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.8

Hi guys,

version 1.8 (the newest) doesn't contain ChainLoader.php, so it's not possible to use when you install bundle by composer.

**Comment by antoligy** [comment]
Hey @mmp4k!

Thanks for reporting.  This is actually intentional as we haven't yet released 1.9, of which the ChainLoader will be a part.

Cheers!
Alex

**Comment by robfrawley** [comment]
@mmp4k To clarify, the docs get build automatically whenever changes are merged, not when changes are released under a new tag. The documentation tracks the `1.0` and `2.0` branches, and nothing else.
