### ISSUE TITLE
Process timeout

### ISSUE THREAD

**Issue by niponika** [liip/LiipImagineBundle#987]
| Q | A |
| --- | --- |
| Bug Report? | yes |
| Feature Request? | yes |
| BC Break Report? | no |
| RFC? | no |
| Imagine Bundle Version | 1.9.0 |

Hello,
First of all, it's the first time I ever do such a report, so please tell me if I forgot to include any element.
I encountered a problem when applying post processors to large files (OptiPNG & PNGquant specifically) . Symfony throws a ProcessTimedOutException whenever the process exceeds it's timeout value.

I saw that the process was generated using Symfony's ProcessBuilder, however no timeout value is specified, therefore the default value of 60 seconds is applied. However, this can fall a bit short for these post processors when they do heavy compression on large files.

Do you think it could be possible to implement some sort of timeout configuration in the filter's configuration, or simply apply longer default timeouts for the post processors ?

Best regards !

**Comment by niponika** [comment]
Sorry, just saw that an issue was already opened for this. Please link it to #857

**Comment by robfrawley** [comment]
Closing as duplicate, but *please do* continue the discussion in #857.
