### ISSUE TITLE
Too Many Redirects and No generated Thumbnails

### ISSUE THREAD

**Issue by Dannebicque** [liip/LiipImagineBundle#989]
Q | A
-- | --
Bug Report? | yes
Feature Request? | no
BC Break Report? | yes
RFC? | no
Imagine Bundle Version | 1.9.0

Hello,

I have some problems with this bundle.
I update my project on Symfony 3.3, and I use LiipImagine 1.9.

I have no thumbnail generated, and I have a "too many redirects" error on the inspector.

I have this link for the supposed generated thumbnail

GET http://localhost:8888/intranet/web/app_dev.php/media/cache/resolve/gallerie/uploads/img/1/etudiants/21605191.jpg 404 (Not Found)

And this is my config.yml

````
liip_imagine:
    resolvers:
        default:
            web_path: ~
              #web_root: "%kernel.root_dir%/../web"
             #cache_prefix: /media/cache

    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        #cache: ~
        avatar:
            jpeg_quality: 80
            filters:
                thumbnail: { size: [35, 35], mode: outbound }
        vignette:
            jpeg_quality: 80
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        profil:
            jpeg_quality: 80
            filters:
                thumbnail: { size: [256, 256], mode: outbound }
        gallerie:
            jpeg_quality: 80
            filters:
                thumbnail: { size: [150, 198], mode: outbound }
````

I have read some post about that, but they have no answers.

If you can explain why the "resolve" words appears in the URL ?

When I use the console, the thumbnail is generate.

Thanks

**Comment by robfrawley** [comment]
@Dannebicque An initial page request will return a url containing "resolve" as that is actually a Symfony route used to generate the transformed image and cache it. Subsequent requests will not.

All the above is assuming that the "resolve" action is succeding, which in your case it isn't (you said the route returns a `404`, so it isn't a successful request. The most likely culprit is your web server configuration. You should share your Nginx/Apache server/virtual-host file so we can further help you along, but there are a few items which I can mention for you to check immediately.

- Have you included [our routing file](https://github.com/liip/LiipImagineBundle/blob/1.0/Resources/config/routing.yaml) in your application? See our [documentation](http://symfony.com/doc/master/bundles/LiipImagineBundle/installation.html#step-3-register-the-bundle-s-routes) for additional info.
- Is your web server setup such that the image resolution route is interpreted as PHP? Perhaps it's simply asking the file system if that file exists (which it does not).
- Lastly, see the discussion in #784 where similar problems were solved already.

**Comment by Dannebicque** [comment]
Thanks for your answers.

I have, I think, found the solution in the issue #784. 

I had theses lines in my Nginx configuration

    location /media/cache/resolve {
        try_files $uri @rewriteapp;
    }
