### ISSUE TITLE
Cache clear with FOS User Bundle

### ISSUE THREAD

**Issue by bettinz** [liip/LiipImagineBundle#997]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9.1

Hello, I'm using FOS User Bundle with defaults template and controllers: I've override form, extended user entity and override templates so a user can upload an image (with Vich Uploader Bundle). Everything works as expected but I can't understand how to remove the cached thumb after the form is submitted.
I've seen only controllers functions in documentation but I'm not overriding the controller so I can't understand.
Thank you

**Comment by cedricziel** [comment]
The easiest thing would be a call to the resolver (which is a cache for your generated images) method `remove`, after upload.

Simplified example:

```php
$this
  ->get('liip_imagine.cache.resolver.prototype.web_path')
  ->remove(['uploads/images/bar/baz.jpg'], ['my_filter'])
;
```
Note that you should preferrably do this through an event listener or subscriber.

**Comment by robfrawley** [comment]
You likely want to request `liip_imagine.cache.resolver.default` instead as `prototype.web_path` is marked abstract:

```php
$this
  ->get('liip_imagine.cache.resolver.default')
  ->remove(['uploads/images/bar/baz.jpg'], ['my_filter']);
```

**Comment by bettinz** [comment]
Hello, I've tried like that:
CacheImageListener.php
```php
<?php

namespace AppBundle\Listener;

use Vich\UploaderBundle\Event\Event;


class CacheImageListener
{
    private $cacheManager;

    public function __construct($cacheManager)
    {
        $this->cacheManager= $cacheManager;
    }

    public function onVichUploaderPreRemove(Event $event){
        $entity= $event->getObject();
        $browserPath= $this->cacheManager->resolve($entity->getImageName(), 'profile_thumb');
        $this->cacheManager->remove($browserPath);

    }


}
```
in services.yml I've:
```php
app.cacheimage_listener:
    class: AppBundle\Listener\CacheImageListener
    arguments: ["@liip_imagine.cache.manager"]
    tags:
      - {name: kernel.event_listener, event: vich_uploader.pre_remove}
```
But cached file isn't removed. I can't understand what is wrong with my code 😃

**Comment by bettinz** [comment]
Ok, so the problem was that CacheManager need relative path for remove.
As reference, I've solved with:
services.yml:
```yml
app.cacheimage_listener:
    class: AppBundle\Listener\CacheImageListener
    arguments: ["@liip_imagine.cache.manager", "@vich_uploader.templating.helper.uploader_helper"]
    tags:
      - {name: kernel.event_listener, event: vich_uploader.pre_remove}
```
```php
<?php

namespace AppBundle\Listener;

use Vich\UploaderBundle\Event\Event;


class CacheImageListener
{
    private $cacheManager;
    private $vichUploaderStorage;

    public function __construct($cacheManager, $vichUploaderStorage)
    {
        $this->cacheManager= $cacheManager;
        $this->vichUploaderStorage= $vichUploaderStorage;
    }

    public function onVichUploaderPreRemove(Event $event){
        $entity= $event->getObject();
        $browserPath= $this->vichUploaderStorage->asset($entity, 'imageFile');
        $this->cacheManager->remove($browserPath);
    }


}
```
Hope this help someone 😃
